In [11]:
import sys
!{sys.executable} --version

# ! export CMAKE_PREFIX_PATH="/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v4/Compiler/gcccore/symengine/0.14.0"
# sys.path.insert(0, "/project/6006115/gjones/molrep/lib/python3.10/site-packages")
# !{sys.executable} -m pip uninstall numpy --yes
# !{sys.executable} -m pip install --no-index --upgrade pip
# !{sys.executable} -m pip install -e /home/gjones/projects/def-jacobsen/gjones/qiskit-addon-dice-solver/
# !{sys.executable} -m pip install numpy==1.26.4
# !{sys.executable} -m pip install -e /scratch/gjones/distributed_LUCJ/
# !pip install -e /home/gjones/projects/def-jacobsen/gjones/qiskit-addon-dice-solver/
# !pip install -e /scratch/gjones/distributed_LUCJ/
# !{sys.executable} -m pip install pandas


import psutil
from functools import partial
 
import joblib
import time
from shutil import copy
import numpy as np
import pandas as pd
#import tensorflow as tf
import os
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import pickle
# import xgboost as xgb

from glob import glob
# import psi4
# from helper_CC_ML_spacial import *

import pyscf
from pyscf import gto, scf, mcscf, cc

import ffsim
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from qiskit import QuantumCircuit, QuantumRegister
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager

from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit_ibm_runtime import SamplerV2 as Sampler

from qiskit_addon_sqd.fermion import SCIResult, diagonalize_fermionic_hamiltonian
from qiskit_addon_sqd.counts import bit_array_to_arrays
from qiskit.primitives import StatevectorSampler, BitArray


from ansatzmap import get_zigzag_physical_layout

from tqdm import tqdm

from DDLUCJ import DDLUCJ, GrabAmps    
font_path = 'Futura Book.ttf'
font_manager.fontManager.addfont(font_path)
prop = font_manager.FontProperties(fname=font_path, size='large')
plt.rcParams['font.family'] = prop.get_name()
plt.rcParams.update({'font.size': 12})

Python 3.13.7

In [12]:
UofT_palette = [ "#1E3765",
                 "#007FA3", 
                 "#6D247A", 
                 "#DC4633",
                 "#6FC7EA",
                 "#00A189",
                 "#AB1368",
                 "#0D534D",
                 "#F1C500",
                 "#8DBF2E"
               ]

palette = sns.color_palette(UofT_palette)

In [13]:
datadf = pd.read_csv("../../../DDLUCJ_active_spaces_unfrozen.csv",delimiter=';').dropna(axis=1)

In [14]:
datadf

                  molecule formula                  xyz  No  Ne
0                  ammonia     NH3       ammonia157.xyz   8  10
1                  methane     CH4        methane50.xyz   9  10
2                 ethylene    C2H4       ethylene42.xyz  14  16
3                   ethane    C2H6         ethane28.xyz  16  18
4                    water     H2O         water183.xyz   7  10
5             formaldehyde    CH2O  formaldehyde138.xyz  12  16
6                 methanol   CH3OH       methanol22.xyz  14  18
7               fluoroform    CHF3          GDB04_5.xyz  21  34
8           buta-1,3-diene    C4H6         GDB04_53.xyz  26  30
9                but-1-yne    C4H6         GDB04_49.xyz  26  30
10          prop-2-en-1-ol   C3H6O         GDB04_33.xyz  26  32
11  (Z)-1-fluoroprop-1-ene   C3H5F         GDB04_65.xyz  25  32

In [15]:
dim_df = pd.read_excel("Dimensions.xlsx",index_col=0)

In [16]:
structure_path_dict = dict(zip(datadf['molecule'], datadf['xyz']))

structure_path_dict = {
    name: os.path.join("../../../classical/structures", xyz)
    for name, xyz in structure_path_dict.items()
}

In [17]:
moldf = pd.read_csv('molecules.csv')
activespacedf = pd.read_csv("active_spaces.csv")

In [18]:
# "No recovery" baseline: a single round of hamming-weight postselection on the
# raw quantum samples, diagonalized directly with Fulqrum -- no configuration
# recovery iterations. See DDLUCJ.PostprocessFulqrum(use_recovery=False).
num_batches = 1
samples_per_batch = 1000  # cap on unique half-strings included in the subspace

In [19]:
energy_data = []
for i in tqdm(sorted(glob("./counts/*npz"))):
    parts = os.path.basename(i).replace('.npz', '').split('_')
    name, _, rawlayers, basis = parts[:4]
    injection = '_'.join(parts[4:])
    layer = int(rawlayers.strip("L"))

    moldict = moldf[moldf['molecule'] == name]
    if moldict.empty:
        print(f"MISSING IN MOLECULES.CSV: {name}")
        continue
    n_electrons = moldict['n_electrons'].values[0]
    num_orbitals = moldict['num_orbitals'].values[0]
    xyzname = moldict['mol_filename'].values[0]
    pathxyz = os.path.join("../../../classical/structures/", xyzname)

    print(f"Running {name}_LUCJ_L{layer}_{basis}_{injection}")

    ampdict = GrabAmps(name, basis)
    t1, t2 = ampdict[injection]

    dd = DDLUCJ(
        StructurePath=pathxyz,
        BasisSet=basis,
        NElec=int(n_electrons),
        NOrb=int(num_orbitals),
        injected=True,
        t1=t1,
        t2=t2,
        n_reps=int(layer),
        optimization_level=3,
        temp_dir="./",
        clean_temp_dir=True,
        n_jobs=-1,
        num_batches=1,          # see note below
        samples_per_batch=1000,
        verbose=True,
    )

    counts = np.load(i)
    bitstrings = BitArray.from_bool_array(counts['bitstrings'])

    energy, subspace = dd(
        postprocess=True,
        BitArray=bitstrings,
        usefulqrum=True,
        bitarraypath=i,
        use_recovery=False,
    )
    energy = float(np.ravel(energy)[0])

    energy_data.append((name, layer, basis, injection, energy, subspace))

  0%|                                                                                                                                                                                                                | 0/1080 [00:00<?, ?it/s]

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  267
  num selected half strs:  267
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.013388 seconds
  Subspace dimension: 267 x 267 = 71_289

  0%|▏                                                                                                                                                                                                    | 1/1080 [00:37<11:09:33, 37.23s/it]

  Operator projection took: 5.810299 seconds
  CSR matrix memory: 2.730381 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0145 seconds
  Electronic Energy: [-329.05716361]
  Total Energy: [-213.11648488]
  num carryover full strs: 6
Iter 0 took: 5.8551 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  173
  num selected half strs:  173
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005869 seconds
  Subspace dimension: 173 x 173 = 29_929

  0%|▎                                                                                                                                                                                                    | 2/1080 [01:10<10:27:20, 34.92s/it]

  Operator projection took: 2.658724 seconds
  CSR matrix memory: 0.844913 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-329.05715396]
  Total Energy: [-213.11647523]
  num carryover full strs: 5
Iter 0 took: 2.6813 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  198
  num selected half strs:  198
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.007714 seconds
  Subspace dimension: 198 x 198 = 39_204

  0%|▌                                                                                                                                                                                                    | 3/1080 [01:44<10:20:27, 34.57s/it]

  Operator projection took: 3.332452 seconds
  CSR matrix memory: 1.051579 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0073 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 3.3581 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  77
  num selected half strs:  77
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.001174 seconds
  Subspace dimension: 77 x 77 = 5_929

  0%|▋                                                                                                                                                                                                     | 4/1080 [02:15<9:56:54, 33.29s/it]

  Operator projection took: 0.877813 seconds
  CSR matrix memory: 0.122288 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0032 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 0.8872 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_STO-3G_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  161
  num selected half strs:  161
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005090 seconds
  Subspace dimension: 161 x 161 = 25_921
  Operator projection took: 2.481747 seconds
  CSR matrix memory: 0.543156 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...

  0%|▉                                                                                                                                                                                                     | 5/1080 [02:49<9:56:22, 33.29s/it]

  Eigensolving took: 0.0073 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 2.5030 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  207
  num selected half strs:  207
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.008086 seconds
  Subspace dimension: 207 x 207 = 42_849
  Operator projection took: 3.308214 seconds
  CSR matrix memory: 20.987232 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...

  1%|█                                                                                                                                                                                                     | 6/1080 [03:23<9:59:52, 33.51s/it]

  Eigensolving took: 0.0150 seconds
  Electronic Energy: [-329.06308729]
  Total Energy: [-213.12240855]
  num carryover full strs: 233
Iter 0 took: 3.3446 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_aug-cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  143
  num selected half strs:  143
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004025 seconds
  Subspace dimension: 143 x 143 = 20_449

  1%|█▎                                                                                                                                                                                                    | 7/1080 [03:47<9:06:49, 30.58s/it]

  Operator projection took: 1.517025 seconds
  CSR matrix memory: 0.469227 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-331.89036893]
  Total Energy: [-215.9496902]
  num carryover full strs: 5
Iter 0 took: 1.5352 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_aug-cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  201
  num selected half strs:  201
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.007998 seconds
  Subspace dimension: 201 x 201 = 40_401

  1%|█▍                                                                                                                                                                                                    | 8/1080 [04:13<8:39:39, 29.09s/it]

  Operator projection took: 2.741640 seconds
  CSR matrix memory: 1.049152 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0096 seconds
  Electronic Energy: [-331.89037135]
  Total Energy: [-215.94969262]
  num carryover full strs: 5
Iter 0 took: 2.7706 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  170
  num selected half strs:  170
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005639 seconds
  Subspace dimension: 170 x 170 = 28_900

  1%|█▋                                                                                                                                                                                                    | 9/1080 [04:38<8:15:58, 27.79s/it]

  Operator projection took: 1.981236 seconds
  CSR matrix memory: 0.588932 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0059 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 2.0021 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_aug-cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  155
  num selected half strs:  155
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005876 seconds
  Subspace dimension: 155 x 155 = 24_025
  Operator projection took: 1.850008 seconds
  CSR matrix memory: 0.508549 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...

  1%|█▊                                                                                                                                                                                                   | 10/1080 [05:04<8:04:55, 27.19s/it]

  Eigensolving took: 0.0082 seconds
  Electronic Energy: [-331.89036842]
  Total Energy: [-215.94968968]
  num carryover full strs: 3
Iter 0 took: 1.8735 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_aug-cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  191
  num selected half strs:  191
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.006873 seconds
  Subspace dimension: 191 x 191 = 36_481
  Operator projection took: 2.521707 seconds
  CSR matrix memory: 0.801563 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...

  1%|██                                                                                                                                                                                                   | 11/1080 [05:30<7:55:47, 26.70s/it]

  Eigensolving took: 0.0094 seconds
  Electronic Energy: [-331.89036912]
  Total Energy: [-215.94969038]
  num carryover full strs: 2
Iter 0 took: 2.5480 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_aug-cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  266
  num selected half strs:  266
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012865 seconds
  Subspace dimension: 266 x 266 = 70_756

  1%|██▏                                                                                                                                                                                                  | 12/1080 [05:56<7:56:01, 26.74s/it]

  Operator projection took: 3.790029 seconds
  CSR matrix memory: 41.114887 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0225 seconds
  Electronic Energy: [-331.89037686]
  Total Energy: [-215.94969813]
  num carryover full strs: 71
Iter 0 took: 3.8415 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  87
  num selected half strs:  87
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.001495 seconds
  Subspace dimension: 87 x 87 = 7_569

  1%|██▎                                                                                                                                                                                                  | 13/1080 [06:25<8:06:13, 27.34s/it]

  Operator projection took: 0.906278 seconds
  CSR matrix memory: 0.223209 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0038 seconds
  Electronic Energy: [-331.87764018]
  Total Energy: [-215.93696144]
  num carryover full strs: 3
Iter 0 took: 0.9171 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  125
  num selected half strs:  125
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003034 seconds
  Subspace dimension: 125 x 125 = 15_625

  1%|██▌                                                                                                                                                                                                  | 14/1080 [06:55<8:17:12, 27.99s/it]

  Operator projection took: 1.485481 seconds
  CSR matrix memory: 0.410725 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0047 seconds
  Electronic Energy: [-331.87765734]
  Total Energy: [-215.93697861]
  num carryover full strs: 5
Iter 0 took: 1.5003 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  107
  num selected half strs:  107
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.002350 seconds
  Subspace dimension: 107 x 107 = 11_449

  1%|██▋                                                                                                                                                                                                  | 15/1080 [07:24<8:22:51, 28.33s/it]

  Operator projection took: 1.244690 seconds
  CSR matrix memory: 0.238377 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0040 seconds
  Electronic Energy: [-331.87763996]
  Total Energy: [-215.93696123]
  num carryover full strs: 1
Iter 0 took: 1.2576 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  113
  num selected half strs:  113
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002487 seconds
  Subspace dimension: 113 x 113 = 12_769

  1%|██▉                                                                                                                                                                                                  | 16/1080 [07:53<8:26:36, 28.57s/it]

  Operator projection took: 1.324056 seconds
  CSR matrix memory: 0.339725 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-331.87766791]
  Total Energy: [-215.93698918]
  num carryover full strs: 2
Iter 0 took: 1.3376 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  149
  num selected half strs:  149
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004431 seconds
  Subspace dimension: 149 x 149 = 22_201

  2%|███                                                                                                                                                                                                  | 17/1080 [08:23<8:36:29, 29.15s/it]

  Operator projection took: 2.119108 seconds
  CSR matrix memory: 0.489002 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.1380 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  278
  num selected half strs:  278
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.014162 seconds
  Subspace dimension: 278 x 278 = 77_284

  2%|███▎                                                                                                                                                                                                 | 18/1080 [08:57<9:00:31, 30.54s/it]

  Operator projection took: 5.505545 seconds
  CSR matrix memory: 46.198124 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0255 seconds
  Electronic Energy: [-331.88242832]
  Total Energy: [-215.94174958]
  num carryover full strs: 348
Iter 0 took: 5.5622 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  125
  num selected half strs:  125
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003093 seconds
  Subspace dimension: 125 x 125 = 15_625

  2%|███▍                                                                                                                                                                                                 | 19/1080 [09:29<9:09:26, 31.07s/it]

  Operator projection took: 1.614720 seconds
  CSR matrix memory: 0.341465 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0049 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.6300 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_STO-3G_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  127
  num selected half strs:  127
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003168 seconds
  Subspace dimension: 127 x 127 = 16_129

  2%|███▋                                                                                                                                                                                                 | 20/1080 [10:01<9:13:14, 31.32s/it]

  Operator projection took: 1.722066 seconds
  CSR matrix memory: 0.339130 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0052 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.7376 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_STO-3G_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  145
  num selected half strs:  145
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004136 seconds
  Subspace dimension: 145 x 145 = 21_025

  2%|███▊                                                                                                                                                                                                 | 21/1080 [10:34<9:17:42, 31.60s/it]

  Operator projection took: 2.102426 seconds
  CSR matrix memory: 0.447117 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0061 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 2.1211 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_STO-3G_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  149
  num selected half strs:  149
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004382 seconds
  Subspace dimension: 149 x 149 = 22_201

  2%|████                                                                                                                                                                                                 | 22/1080 [11:06<9:22:22, 31.89s/it]

  Operator projection took: 2.225467 seconds
  CSR matrix memory: 0.475178 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0071 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 2.2458 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_STO-3G_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  119
  num selected half strs:  119
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002833 seconds
  Subspace dimension: 119 x 119 = 14_161

  2%|████▏                                                                                                                                                                                                | 23/1080 [11:38<9:21:58, 31.90s/it]

  Operator projection took: 1.526066 seconds
  CSR matrix memory: 0.297840 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0048 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.5412 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_STO-3G_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  229
  num selected half strs:  229
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.009869 seconds
  Subspace dimension: 229 x 229 = 52_441

  2%|████▍                                                                                                                                                                                                | 24/1080 [12:13<9:36:01, 32.73s/it]

  Operator projection took: 4.168042 seconds
  CSR matrix memory: 22.139301 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0135 seconds
  Electronic Energy: [-329.06144774]
  Total Energy: [-213.120769]
  num carryover full strs: 191
Iter 0 took: 4.2052 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_aug-cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  161
  num selected half strs:  161
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004892 seconds
  Subspace dimension: 161 x 161 = 25_921

  2%|████▌                                                                                                                                                                                                | 25/1080 [12:37<8:52:55, 30.31s/it]

  Operator projection took: 1.908779 seconds
  CSR matrix memory: 0.557758 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0074 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.9303 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_aug-cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  113
  num selected half strs:  113
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002546 seconds
  Subspace dimension: 113 x 113 = 12_769

  2%|████▋                                                                                                                                                                                                | 26/1080 [13:01<8:18:47, 28.39s/it]

  Operator projection took: 1.093778 seconds
  CSR matrix memory: 0.241398 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0056 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.1085 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  133
  num selected half strs:  133
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003560 seconds
  Subspace dimension: 133 x 133 = 17_689

  2%|████▉                                                                                                                                                                                                | 27/1080 [13:25<7:55:32, 27.10s/it]

  Operator projection took: 1.356016 seconds
  CSR matrix memory: 0.312717 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0060 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.3731 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_aug-cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  117
  num selected half strs:  117
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002714 seconds
  Subspace dimension: 117 x 117 = 13_689

  3%|█████                                                                                                                                                                                                | 28/1080 [13:49<7:37:32, 26.10s/it]

  Operator projection took: 1.092199 seconds
  CSR matrix memory: 0.300159 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0057 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.1073 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_aug-cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  131
  num selected half strs:  131
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003488 seconds
  Subspace dimension: 131 x 131 = 17_161

  3%|█████▎                                                                                                                                                                                               | 29/1080 [14:14<7:28:55, 25.63s/it]

  Operator projection took: 1.367759 seconds
  CSR matrix memory: 0.375843 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0048 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.3831 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_aug-cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  223
  num selected half strs:  223
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.009214 seconds
  Subspace dimension: 223 x 223 = 49_729

  3%|█████▍                                                                                                                                                                                               | 30/1080 [14:39<7:27:33, 25.57s/it]

  Operator projection took: 2.716709 seconds
  CSR matrix memory: 28.549046 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0151 seconds
  Electronic Energy: [-331.89040038]
  Total Energy: [-215.94972165]
  num carryover full strs: 127
Iter 0 took: 2.7538 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  149
  num selected half strs:  149
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004525 seconds
  Subspace dimension: 149 x 149 = 22_201

  3%|█████▋                                                                                                                                                                                               | 31/1080 [15:09<7:48:31, 26.80s/it]

  Operator projection took: 2.027324 seconds
  CSR matrix memory: 0.523106 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.0470 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  109
  num selected half strs:  109
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002454 seconds
  Subspace dimension: 109 x 109 = 11_881

  3%|█████▊                                                                                                                                                                                               | 32/1080 [15:38<7:58:27, 27.39s/it]

  Operator projection took: 1.259130 seconds
  CSR matrix memory: 0.246159 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0049 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.2731 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  105
  num selected half strs:  105
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.002068 seconds
  Subspace dimension: 105 x 105 = 11_025

  3%|██████                                                                                                                                                                                               | 33/1080 [16:06<8:05:09, 27.80s/it]

  Operator projection took: 1.189108 seconds
  CSR matrix memory: 0.230717 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0041 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.2012 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  89
  num selected half strs:  89
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.001582 seconds
  Subspace dimension: 89 x 89 = 7_921

  3%|██████▏                                                                                                                                                                                              | 34/1080 [16:35<8:08:33, 28.02s/it]

  Operator projection took: 0.984793 seconds
  CSR matrix memory: 0.141239 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 0.9965 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  121
  num selected half strs:  121
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002803 seconds
  Subspace dimension: 121 x 121 = 14_641

  3%|██████▍                                                                                                                                                                                              | 35/1080 [17:04<8:13:57, 28.36s/it]

  Operator projection took: 1.472014 seconds
  CSR matrix memory: 0.295460 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0053 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.4871 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L2_cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  238
  num selected half strs:  238
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011164 seconds
  Subspace dimension: 238 x 238 = 56_644

  3%|██████▌                                                                                                                                                                                             | 36/1080 [20:59<26:11:12, 90.30s/it]

  Operator projection took: 4.647287 seconds
  CSR matrix memory: 25.398624 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0168 seconds
  Electronic Energy: [-331.88009366]
  Total Energy: [-215.93941492]
  num carryover full strs: 182
Iter 0 took: 4.6901 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_STO-3G_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  93
  num selected half strs:  93
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.001699 seconds
  Subspace dimension: 93 x 93 = 8_649

  3%|██████▋                                                                                                                                                                                            | 37/1080 [23:59<33:55:48, 117.11s/it]

  Operator projection took: 1.136022 seconds
  CSR matrix memory: 0.149006 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0039 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.1471 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_STO-3G_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  99
  num selected half strs:  99
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.002008 seconds
  Subspace dimension: 99 x 99 = 9_801

  4%|██████▊                                                                                                                                                                                            | 38/1080 [24:59<28:59:44, 100.18s/it]

  Operator projection took: 1.268925 seconds
  CSR matrix memory: 0.185856 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0052 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.2818 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_STO-3G_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  125
  num selected half strs:  125
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003210 seconds
  Subspace dimension: 125 x 125 = 15_625

  4%|███████                                                                                                                                                                                            | 39/1080 [26:48<29:44:47, 102.87s/it]

  Operator projection took: 1.662476 seconds
  CSR matrix memory: 0.312855 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0061 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.6785 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_STO-3G_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  117
  num selected half strs:  117
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002690 seconds
  Subspace dimension: 117 x 117 = 13_689

  4%|███████                                                                                                                                                                                         | 40/1080 [1:03:43<212:45:07, 736.45s/it]

  Operator projection took: 1.400420 seconds
  CSR matrix memory: 0.267796 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0050 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.4147 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_STO-3G_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  97
  num selected half strs:  97
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.001809 seconds
  Subspace dimension: 97 x 97 = 9_409

  4%|███████▎                                                                                                                                                                                        | 41/1080 [1:27:18<271:19:51, 940.13s/it]

  Operator projection took: 1.134674 seconds
  CSR matrix memory: 0.174702 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.1466 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_STO-3G_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  261
  num selected half strs:  261
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012565 seconds
  Subspace dimension: 261 x 261 = 68_121

  4%|███████▍                                                                                                                                                                                        | 42/1080 [1:27:55<192:52:30, 668.93s/it]

  Operator projection took: 5.131393 seconds
  CSR matrix memory: 34.434361 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0301 seconds
  Electronic Energy: [-329.06712213]
  Total Energy: [-213.1264434]
  num carryover full strs: 365
Iter 0 took: 5.1900 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_aug-cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  127
  num selected half strs:  127
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003111 seconds
  Subspace dimension: 127 x 127 = 16_129

  4%|███████▋                                                                                                                                                                                        | 43/1080 [1:28:19<137:00:18, 475.62s/it]

  Operator projection took: 1.281760 seconds
  CSR matrix memory: 0.321735 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0058 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.2976 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_aug-cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  147
  num selected half strs:  147
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004247 seconds
  Subspace dimension: 147 x 147 = 21_609

  4%|███████▊                                                                                                                                                                                         | 44/1080 [1:28:44<97:58:34, 340.46s/it]

  Operator projection took: 1.667779 seconds
  CSR matrix memory: 0.397068 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0058 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.6855 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  121
  num selected half strs:  121
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002844 seconds
  Subspace dimension: 121 x 121 = 14_641

  4%|████████                                                                                                                                                                                         | 45/1080 [1:29:08<70:34:34, 245.48s/it]

  Operator projection took: 1.127728 seconds
  CSR matrix memory: 0.289875 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0050 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.1422 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_aug-cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  127
  num selected half strs:  127
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003181 seconds
  Subspace dimension: 127 x 127 = 16_129

  4%|████████▏                                                                                                                                                                                        | 46/1080 [1:29:32<51:24:59, 179.01s/it]

  Operator projection took: 1.217556 seconds
  CSR matrix memory: 0.327549 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0045 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.2322 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_aug-cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  129
  num selected half strs:  129
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003176 seconds
  Subspace dimension: 129 x 129 = 16_641

  4%|████████▍                                                                                                                                                                                        | 47/1080 [1:29:56<38:01:05, 132.49s/it]

  Operator projection took: 1.248391 seconds
  CSR matrix memory: 0.366123 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0051 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.2640 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_aug-cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  257
  num selected half strs:  257
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011940 seconds
  Subspace dimension: 257 x 257 = 66_049

  4%|████████▌                                                                                                                                                                                        | 48/1080 [1:30:22<28:49:33, 100.56s/it]

  Operator projection took: 3.366888 seconds
  CSR matrix memory: 46.558064 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0270 seconds
  Electronic Energy: [-331.89038876]
  Total Energy: [-215.94971002]
  num carryover full strs: 113
Iter 0 took: 3.4208 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  131
  num selected half strs:  131
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003462 seconds
  Subspace dimension: 131 x 131 = 17_161

  5%|████████▊                                                                                                                                                                                         | 49/1080 [1:30:51<22:39:47, 79.13s/it]

  Operator projection took: 1.599090 seconds
  CSR matrix memory: 0.363895 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0058 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.6156 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  109
  num selected half strs:  109
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002302 seconds
  Subspace dimension: 109 x 109 = 11_881

  5%|████████▉                                                                                                                                                                                         | 50/1080 [1:31:20<18:18:58, 64.02s/it]

  Operator projection took: 1.230350 seconds
  CSR matrix memory: 0.231190 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0050 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.2440 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  113
  num selected half strs:  113
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002509 seconds
  Subspace dimension: 113 x 113 = 12_769

  5%|█████████▏                                                                                                                                                                                        | 51/1080 [1:31:49<15:16:15, 53.43s/it]

  Operator projection took: 1.284997 seconds
  CSR matrix memory: 0.256962 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0057 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.2998 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  151
  num selected half strs:  151
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004455 seconds
  Subspace dimension: 151 x 151 = 22_801

  5%|█████████▎                                                                                                                                                                                        | 52/1080 [1:32:18<13:13:58, 46.34s/it]

  Operator projection took: 2.010762 seconds
  CSR matrix memory: 0.465473 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0054 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.0292 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  123
  num selected half strs:  123
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003006 seconds
  Subspace dimension: 123 x 123 = 15_129

  5%|█████████▌                                                                                                                                                                                        | 53/1080 [1:32:47<11:43:19, 41.09s/it]

  Operator projection took: 1.426668 seconds
  CSR matrix memory: 0.309681 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0046 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.4413 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L3_cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  268
  num selected half strs:  268
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.013277 seconds
  Subspace dimension: 268 x 268 = 71_824

  5%|█████████▋                                                                                                                                                                                        | 54/1080 [1:33:20<10:59:35, 38.57s/it]

  Operator projection took: 5.173987 seconds
  CSR matrix memory: 34.517323 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0197 seconds
  Electronic Energy: [-331.88058281]
  Total Energy: [-215.93990408]
  num carryover full strs: 196
Iter 0 took: 5.2234 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_STO-3G_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  131
  num selected half strs:  131
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003450 seconds
  Subspace dimension: 131 x 131 = 17_161

  5%|█████████▉                                                                                                                                                                                        | 55/1080 [1:33:52<10:27:30, 36.73s/it]

  Operator projection took: 1.688747 seconds
  CSR matrix memory: 0.328007 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.7061 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_STO-3G_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  109
  num selected half strs:  109
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002484 seconds
  Subspace dimension: 109 x 109 = 11_881

  5%|██████████                                                                                                                                                                                        | 56/1080 [1:34:24<10:01:02, 35.22s/it]

  Operator projection took: 1.691365 seconds
  CSR matrix memory: 0.236179 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0048 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.7060 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_STO-3G_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  119
  num selected half strs:  119
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002776 seconds
  Subspace dimension: 119 x 119 = 14_161

  5%|██████████▎                                                                                                                                                                                        | 57/1080 [1:34:55<9:40:26, 34.04s/it]

  Operator projection took: 1.436596 seconds
  CSR matrix memory: 0.308872 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0046 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.4512 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_STO-3G_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  121
  num selected half strs:  121
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002870 seconds
  Subspace dimension: 121 x 121 = 14_641

  5%|██████████▍                                                                                                                                                                                        | 58/1080 [1:35:27<9:25:12, 33.18s/it]

  Operator projection took: 1.474342 seconds
  CSR matrix memory: 0.284336 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0052 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.4893 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_STO-3G_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  141
  num selected half strs:  141
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004099 seconds
  Subspace dimension: 141 x 141 = 19_881

  5%|██████████▋                                                                                                                                                                                        | 59/1080 [1:35:59<9:18:43, 32.83s/it]

  Operator projection took: 1.888197 seconds
  CSR matrix memory: 0.419590 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.9068 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_STO-3G_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  249
  num selected half strs:  249
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011201 seconds
  Subspace dimension: 249 x 249 = 62_001

  6%|██████████▊                                                                                                                                                                                        | 60/1080 [1:36:33<9:24:12, 33.19s/it]

  Operator projection took: 4.403092 seconds
  CSR matrix memory: 25.716206 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0165 seconds
  Electronic Energy: [-329.06061186]
  Total Energy: [-213.11993312]
  num carryover full strs: 205
Iter 0 took: 4.4460 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_aug-cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  123
  num selected half strs:  123
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003157 seconds
  Subspace dimension: 123 x 123 = 15_129

  6%|███████████                                                                                                                                                                                        | 61/1080 [1:36:56<8:35:24, 30.35s/it]

  Operator projection took: 1.169809 seconds
  CSR matrix memory: 0.281528 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0045 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.1872 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_aug-cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  161
  num selected half strs:  161
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005082 seconds
  Subspace dimension: 161 x 161 = 25_921

  6%|███████████▏                                                                                                                                                                                       | 62/1080 [1:37:21<8:05:28, 28.61s/it]

  Operator projection took: 1.856489 seconds
  CSR matrix memory: 0.550617 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0067 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.8777 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  123
  num selected half strs:  123
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002916 seconds
  Subspace dimension: 123 x 123 = 15_129

  6%|███████████▍                                                                                                                                                                                       | 63/1080 [1:37:45<7:41:22, 27.22s/it]

  Operator projection took: 1.171347 seconds
  CSR matrix memory: 0.320988 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0037 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.1850 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_aug-cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  121
  num selected half strs:  121
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002850 seconds
  Subspace dimension: 121 x 121 = 14_641

  6%|███████████▌                                                                                                                                                                                       | 64/1080 [1:38:09<7:23:18, 26.18s/it]

  Operator projection took: 1.128412 seconds
  CSR matrix memory: 0.245564 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0048 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.1430 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_aug-cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  135
  num selected half strs:  135
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003674 seconds
  Subspace dimension: 135 x 135 = 18_225

  6%|███████████▋                                                                                                                                                                                       | 65/1080 [1:38:32<7:11:02, 25.48s/it]

  Operator projection took: 1.375254 seconds
  CSR matrix memory: 0.364658 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.3928 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_aug-cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  218
  num selected half strs:  218
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.008700 seconds
  Subspace dimension: 218 x 218 = 47_524

  6%|███████████▉                                                                                                                                                                                       | 66/1080 [1:38:58<7:09:39, 25.42s/it]

  Operator projection took: 2.571098 seconds
  CSR matrix memory: 22.397617 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0118 seconds
  Electronic Energy: [-331.8903924]
  Total Energy: [-215.94971367]
  num carryover full strs: 112
Iter 0 took: 2.6041 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  107
  num selected half strs:  107
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002284 seconds
  Subspace dimension: 107 x 107 = 11_449

  6%|████████████                                                                                                                                                                                       | 67/1080 [1:39:27<7:26:50, 26.47s/it]

  Operator projection took: 1.206202 seconds
  CSR matrix memory: 0.228580 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0047 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.2196 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  153
  num selected half strs:  153
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004663 seconds
  Subspace dimension: 153 x 153 = 23_409

  6%|████████████▎                                                                                                                                                                                      | 68/1080 [1:39:56<7:41:59, 27.39s/it]

  Operator projection took: 2.102678 seconds
  CSR matrix memory: 0.560490 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.1231 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  103
  num selected half strs:  103
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.002082 seconds
  Subspace dimension: 103 x 103 = 10_609

  6%|████████████▍                                                                                                                                                                                      | 69/1080 [1:40:25<7:47:50, 27.76s/it]

  Operator projection took: 1.144101 seconds
  CSR matrix memory: 0.232609 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-331.87764013]
  Total Energy: [-215.9369614]
  num carryover full strs: 3
Iter 0 took: 1.1563 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  159
  num selected half strs:  159
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004977 seconds
  Subspace dimension: 159 x 159 = 25_281

  6%|████████████▋                                                                                                                                                                                      | 70/1080 [1:40:55<7:57:02, 28.34s/it]

  Operator projection took: 2.234455 seconds
  CSR matrix memory: 0.524097 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.2551 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  117
  num selected half strs:  117
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002744 seconds
  Subspace dimension: 117 x 117 = 13_689

  7%|████████████▊                                                                                                                                                                                      | 71/1080 [1:41:23<7:59:14, 28.50s/it]

  Operator projection took: 1.338282 seconds
  CSR matrix memory: 0.267796 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0056 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.3535 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L4_cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  230
  num selected half strs:  230
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.009463 seconds
  Subspace dimension: 230 x 230 = 52_900

  7%|█████████████                                                                                                                                                                                      | 72/1080 [1:41:54<8:11:48, 29.27s/it]

  Operator projection took: 3.554344 seconds
  CSR matrix memory: 24.854847 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0149 seconds
  Electronic Energy: [-331.87858444]
  Total Energy: [-215.93790571]
  num carryover full strs: 161
Iter 0 took: 3.5925 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_STO-3G_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  157
  num selected half strs:  157
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004831 seconds
  Subspace dimension: 157 x 157 = 24_649

  7%|█████████████▏                                                                                                                                                                                     | 73/1080 [1:42:27<8:25:17, 30.11s/it]

  Operator projection took: 2.296997 seconds
  CSR matrix memory: 0.541416 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0059 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 2.3167 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_STO-3G_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  149
  num selected half strs:  149
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004345 seconds
  Subspace dimension: 149 x 149 = 22_201

  7%|█████████████▎                                                                                                                                                                                     | 74/1080 [1:42:58<8:32:10, 30.55s/it]

  Operator projection took: 2.086941 seconds
  CSR matrix memory: 0.481998 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0067 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 2.1064 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_STO-3G_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  131
  num selected half strs:  131
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003503 seconds
  Subspace dimension: 131 x 131 = 17_161

  7%|█████████████▌                                                                                                                                                                                     | 75/1080 [1:43:31<8:42:21, 31.19s/it]

  Operator projection took: 1.694450 seconds
  CSR matrix memory: 0.321827 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.7117 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_STO-3G_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  131
  num selected half strs:  131
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003442 seconds
  Subspace dimension: 131 x 131 = 17_161

  7%|█████████████▋                                                                                                                                                                                     | 76/1080 [1:44:02<8:42:48, 31.24s/it]

  Operator projection took: 1.675807 seconds
  CSR matrix memory: 0.357807 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0072 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.6937 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_STO-3G_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  117
  num selected half strs:  117
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002728 seconds
  Subspace dimension: 117 x 117 = 13_689

  7%|█████████████▉                                                                                                                                                                                     | 77/1080 [1:44:33<8:42:22, 31.25s/it]

  Operator projection took: 1.408154 seconds
  CSR matrix memory: 0.251728 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0052 seconds
  Electronic Energy: [-329.05714818]
  Total Energy: [-213.11646944]
  num carryover full strs: 1
Iter 0 took: 1.4226 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_STO-3G_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  237
  num selected half strs:  237
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010594 seconds
  Subspace dimension: 237 x 237 = 56_169

  7%|██████████████                                                                                                                                                                                     | 78/1080 [1:45:07<8:53:42, 31.96s/it]

  Operator projection took: 4.185167 seconds
  CSR matrix memory: 19.291035 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0147 seconds
  Electronic Energy: [-329.06390736]
  Total Energy: [-213.12322863]
  num carryover full strs: 148
Iter 0 took: 4.2248 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_aug-cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  173
  num selected half strs:  173
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005859 seconds
  Subspace dimension: 173 x 173 = 29_929

  7%|██████████████▎                                                                                                                                                                                    | 79/1080 [1:45:32<8:17:06, 29.80s/it]

  Operator projection took: 2.045522 seconds
  CSR matrix memory: 0.646931 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0076 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 2.0683 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_aug-cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  137
  num selected half strs:  137
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003756 seconds
  Subspace dimension: 137 x 137 = 18_769

  7%|██████████████▍                                                                                                                                                                                    | 80/1080 [1:45:56<7:48:03, 28.08s/it]

  Operator projection took: 1.386413 seconds
  CSR matrix memory: 0.361652 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.4041 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  147
  num selected half strs:  147
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004218 seconds
  Subspace dimension: 147 x 147 = 21_609

  8%|██████████████▋                                                                                                                                                                                    | 81/1080 [1:46:20<7:28:41, 26.95s/it]

  Operator projection took: 1.584292 seconds
  CSR matrix memory: 0.450901 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.6028 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_aug-cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  153
  num selected half strs:  153
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004607 seconds
  Subspace dimension: 153 x 153 = 23_409

  8%|██████████████▊                                                                                                                                                                                    | 82/1080 [1:46:44<7:14:36, 26.13s/it]

  Operator projection took: 1.694960 seconds
  CSR matrix memory: 0.462299 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0073 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.7151 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_aug-cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  165
  num selected half strs:  165
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005379 seconds
  Subspace dimension: 165 x 165 = 27_225

  8%|██████████████▉                                                                                                                                                                                    | 83/1080 [1:47:09<7:05:49, 25.63s/it]

  Operator projection took: 1.836813 seconds
  CSR matrix memory: 0.543919 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0071 seconds
  Electronic Energy: [-331.89036833]
  Total Energy: [-215.94968959]
  num carryover full strs: 1
Iter 0 took: 1.8582 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_aug-cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  192
  num selected half strs:  192
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.006631 seconds
  Subspace dimension: 192 x 192 = 36_864

  8%|███████████████▏                                                                                                                                                                                   | 84/1080 [1:47:34<7:01:06, 25.37s/it]

  Operator projection took: 2.015713 seconds
  CSR matrix memory: 20.334553 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0098 seconds
  Electronic Energy: [-331.89038328]
  Total Energy: [-215.94970455]
  num carryover full strs: 121
Iter 0 took: 2.0429 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_cc-pVDZ_CCSD
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  165
  num selected half strs:  165
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005410 seconds
  Subspace dimension: 165 x 165 = 27_225

  8%|███████████████▎                                                                                                                                                                                   | 85/1080 [1:48:03<7:22:32, 26.69s/it]

  Operator projection took: 2.310519 seconds
  CSR matrix memory: 0.581593 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.3318 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_cc-pVDZ_ML
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  141
  num selected half strs:  141
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.003838 seconds
  Subspace dimension: 141 x 141 = 19_881

  8%|███████████████▌                                                                                                                                                                                   | 86/1080 [1:48:33<7:35:32, 27.50s/it]

  Operator projection took: 1.844830 seconds
  CSR matrix memory: 0.393726 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0056 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.8621 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_cc-pVDZ_ML_exact
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  123
  num selected half strs:  123
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.002866 seconds
  Subspace dimension: 123 x 123 = 15_129

  8%|███████████████▋                                                                                                                                                                                   | 87/1080 [1:49:02<7:42:19, 27.93s/it]

  Operator projection took: 1.446303 seconds
  CSR matrix memory: 0.298420 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0052 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 1.4612 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_cc-pVDZ_MP2
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  151
  num selected half strs:  151
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.004673 seconds
  Subspace dimension: 151 x 151 = 22_801

  8%|███████████████▉                                                                                                                                                                                   | 88/1080 [1:49:31<7:50:08, 28.44s/it]

  Operator projection took: 2.070083 seconds
  CSR matrix memory: 0.500034 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-331.8776403]
  Total Energy: [-215.93696157]
  num carryover full strs: 3
Iter 0 took: 2.0890 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_cc-pVDZ_random
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  161
  num selected half strs:  161
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.005200 seconds
  Subspace dimension: 161 x 161 = 25_921

  8%|████████████████                                                                                                                                                                                   | 89/1080 [1:50:01<7:56:20, 28.84s/it]

  Operator projection took: 2.328220 seconds
  CSR matrix memory: 0.579777 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0076 seconds
  Electronic Energy: [-331.87763995]
  Total Energy: [-215.93696122]
  num carryover full strs: 1
Iter 0 took: 2.3500 seconds

Running (Z)-1-fluoroprop-1-ene_LUCJ_L5_cc-pVDZ_zeroes
Active Space Orbitals: 25, Electrons: 32, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  245
  num selected half strs:  245
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010714 seconds
  Subspace dimension: 245 x 245 = 60_025

  8%|████████████████▎                                                                                                                                                                                  | 90/1080 [1:50:33<8:09:44, 29.68s/it]

  Operator projection took: 4.046190 seconds
  CSR matrix memory: 23.809818 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0163 seconds
  Electronic Energy: [-331.87821723]
  Total Energy: [-215.9375385]
  num carryover full strs: 106
Iter 0 took: 4.0885 seconds

Running ammonia_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  54
  num selected half strs:  54
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000314 seconds
  Subspace dimension: 54 x 54 = 2_916

  9%|████████████████▌                                                                                                                                                                                  | 92/1080 [1:50:33<4:01:02, 14.64s/it]

  Operator projection took: 0.053159 seconds
  CSR matrix memory: 9.937458 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0062 seconds
  Electronic Energy: [-67.46460528]
  Total Energy: [-55.51992752]
  num carryover full strs: 755
Iter 0 took: 0.0639 seconds

Running ammonia_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  54
  num selected half strs:  54
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000329 seconds
  Subspace dimension: 54 x 54 = 2_916
  Operator projection took: 0.052493 seconds
  CSR matrix memory: 9.901707 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0060 seconds
  Electronic Energy: [-67.46460688]
  Total Energy: [-55.51992913]
  num carryover full strs: 772
Iter 0 took: 0.0611 seconds

Running ammonia_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

  9%|████████████████▊                                                                                                                                                                                  | 93/1080 [1:50:33<2:49:25, 10.30s/it]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  55
  num selected half strs:  55
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000341 seconds
  Subspace dimension: 55 x 55 = 3_025
  Operator projection took: 0.055281 seconds
  CSR matrix memory: 10.613636 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0062 seconds
  Electronic Energy: [-67.46455529]
  Total Energy: [-55.51987754]
  num carryover full strs: 711
Iter 0 took: 0.0646 seconds

Running ammonia_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  53
  num selected half strs:  53
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000301 seconds
  Subspace dimension: 53 x 53 = 2_809

  9%|████████████████▉                                                                                                                                                                                  | 94/1080 [1:50:33<1:59:17,  7.26s/it]

  Operator projection took: 0.051574 seconds
  CSR matrix memory: 9.320271 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0059 seconds
  Electronic Energy: [-67.46454634]
  Total Energy: [-55.51986859]
  num carryover full strs: 719
Iter 0 took: 0.0603 seconds

Running ammonia_LUCJ_L1_STO-3G_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000369 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058389 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

  9%|█████████████████▌                                                                                                                                                                                   | 96/1080 [1:50:34<59:38,  3.64s/it]

  Eigensolving took: 0.0066 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0743 seconds

Running ammonia_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  36
  num selected half strs:  36
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000142 seconds
  Subspace dimension: 36 x 36 = 1_296
  Operator projection took: 0.021692 seconds
  CSR matrix memory: 2.396305 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0022 seconds
  Electronic Energy: [-67.46352982]
  Total Energy: [-55.51885207]
  num carryover full strs: 511
Iter 0 took: 0.0250 seconds

Running ammonia_LUCJ_L1_aug-cc-pVDZ_CCSD

  9%|█████████████████▋                                                                                                                                                                                   | 97/1080 [1:50:34<42:50,  2.62s/it]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  55
  num selected half strs:  55
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000338 seconds
  Subspace dimension: 55 x 55 = 3_025
  Operator projection took: 0.054830 seconds
  CSR matrix memory: 10.613636 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0047 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0619 seconds

Running ammonia_LUCJ_L1_aug-cc-pVDZ_ML

  9%|█████████████████▉                                                                                                                                                                                   | 98/1080 [1:50:34<31:04,  1.90s/it]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  55
  num selected half strs:  55
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000346 seconds
  Subspace dimension: 55 x 55 = 3_025
  Operator projection took: 0.055329 seconds
  CSR matrix memory: 10.613636 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0042 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0619 seconds

Running ammonia_LUCJ_L1_aug-cc-pVDZ_ML_exact

  9%|██████████████████                                                                                                                                                                                   | 99/1080 [1:50:34<22:50,  1.40s/it]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  54
  num selected half strs:  54
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000323 seconds
  Subspace dimension: 54 x 54 = 2_916
  Operator projection took: 0.053424 seconds
  CSR matrix memory: 9.937458 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0041 seconds
  Electronic Energy: [-68.14998662]
  Total Energy: [-56.20530887]
  num carryover full strs: 69
Iter 0 took: 0.0599 seconds

Running ammonia_LUCJ_L1_aug-cc-pVDZ_MP2

  9%|██████████████████▏                                                                                                                                                                                 | 100/1080 [1:50:35<17:04,  1.05s/it]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  55
  num selected half strs:  55
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000328 seconds
  Subspace dimension: 55 x 55 = 3_025
  Operator projection took: 0.054813 seconds
  CSR matrix memory: 10.613636 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0047 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0619 seconds

Running ammonia_LUCJ_L1_aug-cc-pVDZ_random

  9%|██████████████████▎                                                                                                                                                                                 | 101/1080 [1:50:35<13:10,  1.24it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057218 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0700 seconds

Running ammonia_LUCJ_L1_aug-cc-pVDZ_zeroes

  9%|██████████████████▌                                                                                                                                                                                 | 102/1080 [1:50:35<10:05,  1.62it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  32
  num selected half strs:  32
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000112 seconds
  Subspace dimension: 32 x 32 = 1_024
  Operator projection took: 0.017356 seconds
  CSR matrix memory: 1.778019 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0019 seconds
  Electronic Energy: [-68.14998122]
  Total Energy: [-56.20530347]
  num carryover full strs: 67
Iter 0 took: 0.0203 seconds

Running ammonia_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 10%|██████████████████▋                                                                                                                                                                                 | 103/1080 [1:50:35<07:58,  2.04it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000345 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057387 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0665 seconds

Running ammonia_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  55
  num selected half strs:  55
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000317 seconds
  Subspace dimension: 55 x 55 = 3_025
  Operator projection took: 0.055414 seconds
  CSR matrix memory: 10.613636 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0660 seconds

 10%|███████████████████                                                                                                                                                                                 | 105/1080 [1:50:36<05:27,  2.98it/s]

Running ammonia_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000349 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057923 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0673 seconds

Running ammonia_LUCJ_L1_cc-pVDZ_MP2

 10%|███████████████████▏                                                                                                                                                                                | 106/1080 [1:50:36<04:42,  3.45it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  55
  num selected half strs:  55
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000333 seconds
  Subspace dimension: 55 x 55 = 3_025
  Operator projection took: 0.055161 seconds
  CSR matrix memory: 10.613636 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0062 seconds
  Electronic Energy: [-68.15140604]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0643 seconds

Running ammonia_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 10%|███████████████████▍                                                                                                                                                                                | 107/1080 [1:50:36<04:19,  3.74it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.000339 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057659 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0755 seconds

Running ammonia_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  31
  num selected half strs:  31
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000105 seconds
  Subspace dimension: 31 x 31 = 961
  Operator projection took: 0.016638 seconds
  CSR matrix memory: 1.612263 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0027 seconds
  Electronic Energy: [-68.15090079]
  Total Energy: [-56.20622303]
  num carryover full strs: 270
Iter 0 took: 0.0203 seconds

 10%|███████████████████▊                                                                                                                                                                                | 109/1080 [1:50:36<03:29,  4.63it/s]

Running ammonia_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000349 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057600 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0690 seconds

Running ammonia_LUCJ_L2_STO-3G_ML

 10%|███████████████████▉                                                                                                                                                                                | 110/1080 [1:50:37<03:23,  4.76it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000336 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058560 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0719 seconds

Running ammonia_LUCJ_L2_STO-3G_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 10%|████████████████████▏                                                                                                                                                                               | 111/1080 [1:50:37<03:19,  4.86it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000336 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057375 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0700 seconds

Running ammonia_LUCJ_L2_STO-3G_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000351 seconds
  Subspace dimension: 56 x 56 = 3_136

 10%|████████████████████▎                                                                                                                                                                               | 112/1080 [1:50:37<03:14,  4.99it/s]

  Operator projection took: 0.057948 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0066 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0705 seconds

Running ammonia_LUCJ_L2_STO-3G_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000345 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057753 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 11%|████████████████████▋                                                                                                                                                                               | 114/1080 [1:50:37<02:51,  5.65it/s]

  Eigensolving took: 0.0071 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0736 seconds

Running ammonia_LUCJ_L2_STO-3G_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  33
  num selected half strs:  33
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000125 seconds
  Subspace dimension: 33 x 33 = 1_089
  Operator projection took: 0.018751 seconds
  CSR matrix memory: 1.879948 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0020 seconds
  Electronic Energy: [-67.46247136]
  Total Energy: [-55.5177936]
  num carryover full strs: 486
Iter 0 took: 0.0218 seconds

Running ammonia_LUCJ_L2_aug-cc-pVDZ_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 11%|████████████████████▊                                                                                                                                                                               | 115/1080 [1:50:38<03:10,  5.07it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000338 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057810 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0659 seconds

Running ammonia_LUCJ_L2_aug-cc-pVDZ_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 11%|█████████████████████                                                                                                                                                                               | 116/1080 [1:50:38<03:23,  4.75it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000350 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058080 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0049 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0666 seconds

Running ammonia_LUCJ_L2_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000342 seconds
  Subspace dimension: 56 x 56 = 3_136

 11%|█████████████████████▏                                                                                                                                                                              | 117/1080 [1:50:38<03:32,  4.54it/s]

  Operator projection took: 0.058338 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0044 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0669 seconds

Running ammonia_LUCJ_L2_aug-cc-pVDZ_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000339 seconds
  Subspace dimension: 56 x 56 = 3_136

 11%|█████████████████████▍                                                                                                                                                                              | 118/1080 [1:50:38<03:37,  4.43it/s]

  Operator projection took: 0.057611 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0045 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0656 seconds

Running ammonia_LUCJ_L2_aug-cc-pVDZ_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136

 11%|█████████████████████▊                                                                                                                                                                              | 120/1080 [1:50:39<03:31,  4.54it/s]

  Operator projection took: 0.058754 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0044 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0727 seconds

Running ammonia_LUCJ_L2_aug-cc-pVDZ_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  34
  num selected half strs:  34
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000125 seconds
  Subspace dimension: 34 x 34 = 1_156
  Operator projection took: 0.019114 seconds
  CSR matrix memory: 2.161945 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0020 seconds
  Electronic Energy: [-68.14998547]
  Total Energy: [-56.20530772]
  num carryover full strs: 67
Iter 0 took: 0.0221 seconds

Running ammonia_LUCJ_L2_cc-pVDZ_CCSD

 11%|█████████████████████▉                                                                                                                                                                              | 121/1080 [1:50:39<03:24,  4.68it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000340 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057167 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0680 seconds

Running ammonia_LUCJ_L2_cc-pVDZ_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 11%|██████████████████████▏                                                                                                                                                                             | 122/1080 [1:50:39<03:23,  4.70it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000341 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058087 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0704 seconds

Running ammonia_LUCJ_L2_cc-pVDZ_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000357 seconds
  Subspace dimension: 56 x 56 = 3_136

 11%|██████████████████████▎                                                                                                                                                                             | 123/1080 [1:50:39<03:19,  4.79it/s]

  Operator projection took: 0.057810 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0069 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0686 seconds

Running ammonia_LUCJ_L2_cc-pVDZ_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057988 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 11%|██████████████████████▌                                                                                                                                                                             | 124/1080 [1:50:40<03:17,  4.85it/s]

  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0696 seconds

Running ammonia_LUCJ_L2_cc-pVDZ_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000355 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057539 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 12%|██████████████████████▊                                                                                                                                                                             | 126/1080 [1:50:40<02:59,  5.33it/s]

  Eigensolving took: 0.0066 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0729 seconds

Running ammonia_LUCJ_L2_cc-pVDZ_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  32
  num selected half strs:  32
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000113 seconds
  Subspace dimension: 32 x 32 = 1_024
  Operator projection took: 0.017394 seconds
  CSR matrix memory: 1.732105 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0028 seconds
  Electronic Energy: [-68.15097561]
  Total Energy: [-56.20629785]
  num carryover full strs: 284
Iter 0 took: 0.0212 seconds

Running ammonia_LUCJ_L3_STO-3G_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 12%|███████████████████████                                                                                                                                                                             | 127/1080 [1:50:40<03:01,  5.24it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000336 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057621 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0701 seconds

Running ammonia_LUCJ_L3_STO-3G_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000343 seconds
  Subspace dimension: 56 x 56 = 3_136

 12%|███████████████████████▏                                                                                                                                                                            | 128/1080 [1:50:40<03:03,  5.20it/s]

  Operator projection took: 0.057559 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0704 seconds

Running ammonia_LUCJ_L3_STO-3G_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000340 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058600 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 12%|███████████████████████▌                                                                                                                                                                            | 130/1080 [1:50:41<03:04,  5.15it/s]

  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0710 seconds

Running ammonia_LUCJ_L3_STO-3G_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058384 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0707 seconds

Running ammonia_LUCJ_L3_STO-3G_random

 12%|███████████████████████▊                                                                                                                                                                            | 131/1080 [1:50:41<03:07,  5.07it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057821 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0070 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0732 seconds

Running ammonia_LUCJ_L3_STO-3G_zeroes

 12%|███████████████████████▉                                                                                                                                                                            | 132/1080 [1:50:41<02:46,  5.70it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  35
  num selected half strs:  35
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000139 seconds
  Subspace dimension: 35 x 35 = 1_225
  Operator projection took: 0.020565 seconds
  CSR matrix memory: 2.391285 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0021 seconds
  Electronic Energy: [-67.46303304]
  Total Energy: [-55.51835528]
  num carryover full strs: 525
Iter 0 took: 0.0238 seconds

Running ammonia_LUCJ_L3_aug-cc-pVDZ_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 12%|████████████████████████▏                                                                                                                                                                           | 133/1080 [1:50:41<03:05,  5.11it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057486 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0660 seconds

Running ammonia_LUCJ_L3_aug-cc-pVDZ_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 12%|████████████████████████▎                                                                                                                                                                           | 134/1080 [1:50:42<03:19,  4.74it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057586 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0664 seconds

Running ammonia_LUCJ_L3_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000344 seconds
  Subspace dimension: 56 x 56 = 3_136

 12%|████████████████████████▌                                                                                                                                                                           | 135/1080 [1:50:42<03:28,  4.53it/s]

  Operator projection took: 0.058035 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0048 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0672 seconds

Running ammonia_LUCJ_L3_aug-cc-pVDZ_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136

 13%|████████████████████████▋                                                                                                                                                                           | 136/1080 [1:50:42<03:36,  4.36it/s]

  Operator projection took: 0.057563 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0045 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0671 seconds

Running ammonia_LUCJ_L3_aug-cc-pVDZ_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000346 seconds
  Subspace dimension: 56 x 56 = 3_136

 13%|█████████████████████████                                                                                                                                                                           | 138/1080 [1:50:42<03:29,  4.50it/s]

  Operator projection took: 0.058136 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0045 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0719 seconds

Running ammonia_LUCJ_L3_aug-cc-pVDZ_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  34
  num selected half strs:  34
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000125 seconds
  Subspace dimension: 34 x 34 = 1_156
  Operator projection took: 0.019437 seconds
  CSR matrix memory: 2.104954 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0020 seconds
  Electronic Energy: [-68.14997915]
  Total Energy: [-56.2053014]
  num carryover full strs: 65
Iter 0 took: 0.0225 seconds

Running ammonia_LUCJ_L3_cc-pVDZ_CCSD

 13%|█████████████████████████▏                                                                                                                                                                          | 139/1080 [1:50:43<03:24,  4.59it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057876 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0700 seconds

Running ammonia_LUCJ_L3_cc-pVDZ_ML

 13%|█████████████████████████▍                                                                                                                                                                          | 140/1080 [1:50:43<03:23,  4.63it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000341 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057573 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0712 seconds

Running ammonia_LUCJ_L3_cc-pVDZ_ML_exact

 13%|█████████████████████████▌                                                                                                                                                                          | 141/1080 [1:50:43<03:19,  4.70it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057482 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0695 seconds

Running ammonia_LUCJ_L3_cc-pVDZ_MP2

 13%|█████████████████████████▊                                                                                                                                                                          | 142/1080 [1:50:43<03:18,  4.74it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000351 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057875 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0070 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0707 seconds

Running ammonia_LUCJ_L3_cc-pVDZ_random

 13%|█████████████████████████▉                                                                                                                                                                          | 143/1080 [1:50:44<03:19,  4.70it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000333 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057269 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0719 seconds

Running ammonia_LUCJ_L3_cc-pVDZ_zeroes

 13%|██████████████████████████▏                                                                                                                                                                         | 144/1080 [1:50:44<02:57,  5.28it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  34
  num selected half strs:  34
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000134 seconds
  Subspace dimension: 34 x 34 = 1_156
  Operator projection took: 0.019084 seconds
  CSR matrix memory: 2.013676 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0030 seconds
  Electronic Energy: [-68.15058128]
  Total Energy: [-56.20590352]
  num carryover full strs: 284
Iter 0 took: 0.0231 seconds

Running ammonia_LUCJ_L4_STO-3G_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 13%|██████████████████████████▎                                                                                                                                                                         | 145/1080 [1:50:44<03:21,  4.63it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000352 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058302 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0718 seconds

Running ammonia_LUCJ_L4_STO-3G_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136

 14%|██████████████████████████▍                                                                                                                                                                         | 146/1080 [1:50:44<03:17,  4.73it/s]

  Operator projection took: 0.057872 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0708 seconds

Running ammonia_LUCJ_L4_STO-3G_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000338 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058530 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 14%|██████████████████████████▊                                                                                                                                                                         | 148/1080 [1:50:45<03:11,  4.87it/s]

  Eigensolving took: 0.0071 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0716 seconds

Running ammonia_LUCJ_L4_STO-3G_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057543 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0704 seconds

Running ammonia_LUCJ_L4_STO-3G_random

 14%|███████████████████████████                                                                                                                                                                         | 149/1080 [1:50:45<03:10,  4.89it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000340 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057205 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0713 seconds

Running ammonia_LUCJ_L4_STO-3G_zeroes

 14%|███████████████████████████▏                                                                                                                                                                        | 150/1080 [1:50:45<02:47,  5.55it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  34
  num selected half strs:  34
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000134 seconds
  Subspace dimension: 34 x 34 = 1_156
  Operator projection took: 0.019470 seconds
  CSR matrix memory: 2.045811 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0020 seconds
  Electronic Energy: [-67.46295835]
  Total Energy: [-55.5182806]
  num carryover full strs: 468
Iter 0 took: 0.0225 seconds

Running ammonia_LUCJ_L4_aug-cc-pVDZ_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 14%|███████████████████████████▍                                                                                                                                                                        | 151/1080 [1:50:45<03:07,  4.95it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057504 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0670 seconds

Running ammonia_LUCJ_L4_aug-cc-pVDZ_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 14%|███████████████████████████▌                                                                                                                                                                        | 152/1080 [1:50:45<03:22,  4.59it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000340 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058072 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0049 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0683 seconds

Running ammonia_LUCJ_L4_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 14%|███████████████████████████▊                                                                                                                                                                        | 153/1080 [1:50:46<03:31,  4.38it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057798 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0044 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0676 seconds

Running ammonia_LUCJ_L4_aug-cc-pVDZ_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136

 14%|███████████████████████████▉                                                                                                                                                                        | 154/1080 [1:50:46<03:38,  4.25it/s]

  Operator projection took: 0.057665 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0044 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0676 seconds

Running ammonia_LUCJ_L4_aug-cc-pVDZ_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000339 seconds
  Subspace dimension: 56 x 56 = 3_136

 14%|████████████████████████████▎                                                                                                                                                                       | 156/1080 [1:50:46<03:28,  4.43it/s]

  Operator projection took: 0.057476 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0044 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0687 seconds

Running ammonia_LUCJ_L4_aug-cc-pVDZ_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  36
  num selected half strs:  36
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000139 seconds
  Subspace dimension: 36 x 36 = 1_296
  Operator projection took: 0.021953 seconds
  CSR matrix memory: 2.580692 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0022 seconds
  Electronic Energy: [-68.1499866]
  Total Energy: [-56.20530885]
  num carryover full strs: 69
Iter 0 took: 0.0252 seconds

Running ammonia_LUCJ_L4_cc-pVDZ_CCSD

 15%|████████████████████████████▍                                                                                                                                                                       | 157/1080 [1:50:47<03:25,  4.50it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000337 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057397 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0069 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0703 seconds

Running ammonia_LUCJ_L4_cc-pVDZ_ML

 15%|████████████████████████████▋                                                                                                                                                                       | 158/1080 [1:50:47<03:22,  4.55it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000331 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058300 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0709 seconds

Running ammonia_LUCJ_L4_cc-pVDZ_ML_exact

 15%|████████████████████████████▊                                                                                                                                                                       | 159/1080 [1:50:47<03:21,  4.57it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000339 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057950 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0068 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0708 seconds

Running ammonia_LUCJ_L4_cc-pVDZ_MP2

 15%|█████████████████████████████                                                                                                                                                                       | 160/1080 [1:50:47<03:19,  4.62it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000328 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058034 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0704 seconds

Running ammonia_LUCJ_L4_cc-pVDZ_random

 15%|█████████████████████████████▏                                                                                                                                                                      | 161/1080 [1:50:47<03:19,  4.62it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000337 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057548 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0712 seconds

Running ammonia_LUCJ_L4_cc-pVDZ_zeroes

 15%|█████████████████████████████▍                                                                                                                                                                      | 162/1080 [1:50:48<02:55,  5.22it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  31
  num selected half strs:  31
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000104 seconds
  Subspace dimension: 31 x 31 = 961
  Operator projection took: 0.016557 seconds
  CSR matrix memory: 1.687748 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0027 seconds
  Electronic Energy: [-68.15057688]
  Total Energy: [-56.20589913]
  num carryover full strs: 269
Iter 0 took: 0.0203 seconds

Running ammonia_LUCJ_L5_STO-3G_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 15%|█████████████████████████████▌                                                                                                                                                                      | 163/1080 [1:50:48<02:58,  5.14it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058265 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0065 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0710 seconds

Running ammonia_LUCJ_L5_STO-3G_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000333 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058201 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 15%|█████████████████████████████▊                                                                                                                                                                      | 164/1080 [1:50:48<03:00,  5.09it/s]

  Eigensolving took: 0.0067 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0707 seconds

Running ammonia_LUCJ_L5_STO-3G_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057822 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0701 seconds

 15%|██████████████████████████████▏                                                                                                                                                                     | 166/1080 [1:50:48<03:02,  5.01it/s]

Running ammonia_LUCJ_L5_STO-3G_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000337 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057799 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0702 seconds

Running ammonia_LUCJ_L5_STO-3G_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057981 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...

 16%|██████████████████████████████▍                                                                                                                                                                     | 168/1080 [1:50:49<02:40,  5.67it/s]

  Eigensolving took: 0.0071 seconds
  Electronic Energy: [-67.46460696]
  Total Energy: [-55.5199292]
  num carryover full strs: 772
Iter 0 took: 0.0722 seconds

Running ammonia_LUCJ_L5_STO-3G_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  31
  num selected half strs:  31
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000108 seconds
  Subspace dimension: 31 x 31 = 961
  Operator projection took: 0.016238 seconds
  CSR matrix memory: 1.524418 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0018 seconds
  Electronic Energy: [-67.46001709]
  Total Energy: [-55.51533933]
  num carryover full strs: 439
Iter 0 took: 0.0190 seconds

Running ammonia_LUCJ_L5_aug-cc-pVDZ_CCSD
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 16%|██████████████████████████████▋                                                                                                                                                                     | 169/1080 [1:50:49<03:01,  5.01it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000336 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.058032 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0678 seconds

Running ammonia_LUCJ_L5_aug-cc-pVDZ_ML
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 16%|██████████████████████████████▊                                                                                                                                                                     | 170/1080 [1:50:49<03:15,  4.65it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000340 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057574 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0047 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0675 seconds

Running ammonia_LUCJ_L5_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]

 16%|███████████████████████████████                                                                                                                                                                     | 171/1080 [1:50:49<03:25,  4.42it/s]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000346 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057840 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0043 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0679 seconds

Running ammonia_LUCJ_L5_aug-cc-pVDZ_MP2
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136

 16%|███████████████████████████████▏                                                                                                                                                                    | 172/1080 [1:50:50<03:32,  4.27it/s]

  Operator projection took: 0.057821 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0050 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0687 seconds

Running ammonia_LUCJ_L5_aug-cc-pVDZ_random
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136

 16%|███████████████████████████████▌                                                                                                                                                                    | 174/1080 [1:50:50<03:22,  4.48it/s]

  Operator projection took: 0.058206 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0044 seconds
  Electronic Energy: [-68.14998663]
  Total Energy: [-56.20530888]
  num carryover full strs: 69
Iter 0 took: 0.0690 seconds

Running ammonia_LUCJ_L5_aug-cc-pVDZ_zeroes
Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  33
  num selected half strs:  33
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000117 seconds
  Subspace dimension: 33 x 33 = 1_089
  Operator projection took: 0.018810 seconds
  CSR matrix memory: 2.006840 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0020 seconds
  Electronic Energy: [-68.14998659]
  Total Energy: [-56.20530884]
  num carryover full strs: 69
Iter 0 took: 0.0218 seconds

Running ammonia_LUCJ_L5_cc-pVDZ_CCSD

 16%|███████████████████████████████▊                                                                                                                                                                    | 175/1080 [1:50:50<03:20,  4.52it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000346 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057272 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0070 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0704 seconds

Running ammonia_LUCJ_L5_cc-pVDZ_ML

 16%|███████████████████████████████▉                                                                                                                                                                    | 176/1080 [1:50:51<03:18,  4.55it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057850 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0070 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0712 seconds

Running ammonia_LUCJ_L5_cc-pVDZ_ML_exact

 16%|████████████████████████████████                                                                                                                                                                    | 177/1080 [1:50:51<03:16,  4.59it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000334 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057657 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0064 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0705 seconds

Running ammonia_LUCJ_L5_cc-pVDZ_MP2

 16%|████████████████████████████████▎                                                                                                                                                                   | 178/1080 [1:50:51<03:15,  4.61it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000332 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057626 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0069 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0704 seconds

Running ammonia_LUCJ_L5_cc-pVDZ_random

 17%|████████████████████████████████▍                                                                                                                                                                   | 179/1080 [1:50:51<03:14,  4.62it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  56
  num selected half strs:  56
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.000335 seconds
  Subspace dimension: 56 x 56 = 3_136
  Operator projection took: 0.057149 seconds
  CSR matrix memory: 11.352787 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0063 seconds
  Electronic Energy: [-68.15140605]
  Total Energy: [-56.20672829]
  num carryover full strs: 403
Iter 0 took: 0.0695 seconds

Running ammonia_LUCJ_L5_cc-pVDZ_zeroes

 17%|████████████████████████████████▋                                                                                                                                                                   | 180/1080 [1:50:51<02:53,  5.19it/s]

Active Space Orbitals: 8, Electrons: 10, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  35
  num selected half strs:  35
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000140 seconds
  Subspace dimension: 35 x 35 = 1_225
  Operator projection took: 0.020693 seconds
  CSR matrix memory: 2.319462 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0030 seconds
  Electronic Energy: [-68.1505174]
  Total Energy: [-56.20583965]
  num carryover full strs: 310
Iter 0 took: 0.0248 seconds

Running but-1-yne_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  243
  num selected half strs:  243
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012163 seconds
  Subspace dimension: 243 x 243 = 59_049

 17%|████████████████████████████████▌                                                                                                                                                                 | 181/1080 [1:51:40<3:38:48, 14.60s/it]

  Operator projection took: 6.162636 seconds
  CSR matrix memory: 1.290394 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0127 seconds
  Electronic Energy: [-256.10329273]
  Total Energy: [-153.02520759]
  num carryover full strs: 4
Iter 0 took: 6.2033 seconds

Running but-1-yne_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  231
  num selected half strs:  231
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010380 seconds
  Subspace dimension: 231 x 231 = 53_361

 17%|████████████████████████████████▋                                                                                                                                                                 | 182/1080 [1:52:27<6:07:44, 24.57s/it]

  Operator projection took: 5.630250 seconds
  CSR matrix memory: 1.194904 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0098 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 5.6639 seconds

Running but-1-yne_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  309
  num selected half strs:  309
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018773 seconds
  Subspace dimension: 309 x 309 = 95_481

 17%|████████████████████████████████▊                                                                                                                                                                 | 183/1080 [1:53:20<8:13:11, 32.99s/it]

  Operator projection took: 10.674421 seconds
  CSR matrix memory: 2.065479 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0177 seconds
  Electronic Energy: [-256.10300439]
  Total Energy: [-153.02491924]
  num carryover full strs: 3
Iter 0 took: 10.7311 seconds

Running but-1-yne_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  249
  num selected half strs:  249
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012567 seconds
  Subspace dimension: 249 x 249 = 62_001

 17%|█████████████████████████████████                                                                                                                                                                 | 184/1080 [1:54:09<9:22:15, 37.65s/it]

  Operator projection took: 6.517244 seconds
  CSR matrix memory: 1.470387 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0120 seconds
  Electronic Energy: [-256.10298014]
  Total Energy: [-153.024895]
  num carryover full strs: 1
Iter 0 took: 6.5574 seconds

Running but-1-yne_LUCJ_L1_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  383
  num selected half strs:  383
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.030448 seconds
  Subspace dimension: 383 x 383 = 146_689

 17%|█████████████████████████████████                                                                                                                                                                | 185/1080 [1:55:11<11:12:47, 45.10s/it]

  Operator projection took: 18.790244 seconds
  CSR matrix memory: 3.360416 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0291 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 18.8793 seconds

Running but-1-yne_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  302
  num selected half strs:  302
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018246 seconds
  Subspace dimension: 302 x 302 = 91_204

 17%|█████████████████████████████████▏                                                                                                                                                               | 186/1080 [1:56:04<11:46:33, 47.42s/it]

  Operator projection took: 8.927675 seconds
  CSR matrix memory: 35.503757 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0248 seconds
  Electronic Energy: [-256.11448646]
  Total Energy: [-153.03640131]
  num carryover full strs: 393
Iter 0 took: 8.9913 seconds

Running but-1-yne_LUCJ_L1_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  273
  num selected half strs:  273
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015145 seconds
  Subspace dimension: 273 x 273 = 74_529

 17%|█████████████████████████████████▍                                                                                                                                                               | 187/1080 [1:56:39<10:51:48, 43.79s/it]

  Operator projection took: 5.992330 seconds
  CSR matrix memory: 1.549625 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0136 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 6.0407 seconds

Running but-1-yne_LUCJ_L1_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  309
  num selected half strs:  309
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019650 seconds
  Subspace dimension: 309 x 309 = 95_481

 17%|█████████████████████████████████▌                                                                                                                                                               | 188/1080 [1:57:16<10:21:19, 41.79s/it]

  Operator projection took: 8.084926 seconds
  CSR matrix memory: 1.796589 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0192 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 8.1462 seconds

Running but-1-yne_LUCJ_L1_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  337
  num selected half strs:  337
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023602 seconds
  Subspace dimension: 337 x 337 = 113_569

 18%|█████████████████████████████████▊                                                                                                                                                               | 189/1080 [1:57:55<10:04:52, 40.73s/it]

  Operator projection took: 9.062678 seconds
  CSR matrix memory: 2.288700 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0252 seconds
  Electronic Energy: [-257.99487044]
  Total Energy: [-154.91678529]
  num carryover full strs: 2
Iter 0 took: 9.1409 seconds

Running but-1-yne_LUCJ_L1_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  319
  num selected half strs:  319
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021126 seconds
  Subspace dimension: 319 x 319 = 101_761

 18%|██████████████████████████████████▏                                                                                                                                                               | 190/1080 [1:58:32<9:50:58, 39.84s/it]

  Operator projection took: 8.547247 seconds
  CSR matrix memory: 1.888706 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0191 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 8.6091 seconds

Running but-1-yne_LUCJ_L1_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  377
  num selected half strs:  377
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028988 seconds
  Subspace dimension: 377 x 377 = 142_129

 18%|██████████████████████████████████▎                                                                                                                                                               | 191/1080 [1:59:13<9:56:04, 40.23s/it]

  Operator projection took: 11.879121 seconds
  CSR matrix memory: 2.738270 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0297 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 11.9659 seconds

Running but-1-yne_LUCJ_L1_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  258
  num selected half strs:  258
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012839 seconds
  Subspace dimension: 258 x 258 = 66_564

 18%|██████████████████████████████████▍                                                                                                                                                               | 192/1080 [1:59:47<9:26:00, 38.24s/it]

  Operator projection took: 4.473853 seconds
  CSR matrix memory: 16.598240 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0161 seconds
  Electronic Energy: [-257.99488728]
  Total Energy: [-154.91680213]
  num carryover full strs: 83
Iter 0 took: 4.5188 seconds

Running but-1-yne_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  317
  num selected half strs:  317
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020799 seconds
  Subspace dimension: 317 x 317 = 100_489
  Operator projection took: 10.221452 seconds
  CSR matrix memory: 2.578190 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 18%|██████████████████████████████████▋                                                                                                                                                               | 193/1080 [2:00:32<9:56:09, 40.33s/it]

  Eigensolving took: 0.0216 seconds
  Electronic Energy: [-257.98948462]
  Total Energy: [-154.91139947]
  num carryover full strs: 3
Iter 0 took: 10.2893 seconds

Running but-1-yne_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  345
  num selected half strs:  345
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023699 seconds
  Subspace dimension: 345 x 345 = 119_025

 18%|██████████████████████████████████▋                                                                                                                                                              | 194/1080 [2:01:20<10:27:59, 42.53s/it]

  Operator projection took: 11.709298 seconds
  CSR matrix memory: 2.718021 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0228 seconds
  Electronic Energy: [-257.98947373]
  Total Energy: [-154.91138859]
  num carryover full strs: 3
Iter 0 took: 11.7818 seconds

Running but-1-yne_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  383
  num selected half strs:  383
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032482 seconds
  Subspace dimension: 383 x 383 = 146_689

 18%|██████████████████████████████████▊                                                                                                                                                              | 195/1080 [2:02:12<11:08:15, 45.31s/it]

  Operator projection took: 15.896507 seconds
  CSR matrix memory: 3.623768 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0278 seconds
  Electronic Energy: [-257.98947903]
  Total Energy: [-154.91139389]
  num carryover full strs: 7
Iter 0 took: 15.9858 seconds

Running but-1-yne_LUCJ_L1_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  289
  num selected half strs:  289
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018781 seconds
  Subspace dimension: 289 x 289 = 83_521

 18%|███████████████████████████████████                                                                                                                                                              | 196/1080 [2:02:54<10:54:06, 44.40s/it]

  Operator projection took: 8.000231 seconds
  CSR matrix memory: 2.041828 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0155 seconds
  Electronic Energy: [-257.98950472]
  Total Energy: [-154.91141958]
  num carryover full strs: 11
Iter 0 took: 8.0543 seconds

Running but-1-yne_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  391
  num selected half strs:  391
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032172 seconds
  Subspace dimension: 391 x 391 = 152_881

 18%|███████████████████████████████████▏                                                                                                                                                             | 197/1080 [2:03:46<11:26:58, 46.68s/it]

  Operator projection took: 15.143704 seconds
  CSR matrix memory: 3.030872 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0294 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 15.2357 seconds

Running but-1-yne_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  331
  num selected half strs:  331
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021081 seconds
  Subspace dimension: 331 x 331 = 109_561

 18%|███████████████████████████████████▍                                                                                                                                                             | 198/1080 [2:04:28<11:03:41, 45.15s/it]

  Operator projection took: 8.480738 seconds
  CSR matrix memory: 37.054935 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0279 seconds
  Electronic Energy: [-257.99199634]
  Total Energy: [-154.91391119]
  num carryover full strs: 237
Iter 0 took: 8.5524 seconds

Running but-1-yne_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  267
  num selected half strs:  267
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.014357 seconds
  Subspace dimension: 267 x 267 = 71_289

 18%|███████████████████████████████████▌                                                                                                                                                             | 199/1080 [2:05:22<11:41:52, 47.80s/it]

  Operator projection took: 9.511483 seconds
  CSR matrix memory: 1.368900 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0148 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 9.5582 seconds

Running but-1-yne_LUCJ_L2_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  297
  num selected half strs:  297
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019256 seconds
  Subspace dimension: 297 x 297 = 88_209

 19%|███████████████████████████████████▋                                                                                                                                                             | 200/1080 [2:06:20<12:27:24, 50.96s/it]

  Operator projection took: 10.624545 seconds
  CSR matrix memory: 1.821857 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0150 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 10.6786 seconds

Running but-1-yne_LUCJ_L2_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  273
  num selected half strs:  273
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015982 seconds
  Subspace dimension: 273 x 273 = 74_529

 19%|███████████████████████████████████▉                                                                                                                                                             | 201/1080 [2:07:16<12:48:21, 52.45s/it]

  Operator projection took: 9.743298 seconds
  CSR matrix memory: 1.374714 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0133 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 9.7927 seconds

Running but-1-yne_LUCJ_L2_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  363
  num selected half strs:  363
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032497 seconds
  Subspace dimension: 363 x 363 = 131_769

 19%|████████████████████████████████████                                                                                                                                                             | 202/1080 [2:08:18<13:28:17, 55.24s/it]

  Operator projection took: 16.985591 seconds
  CSR matrix memory: 2.758808 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0294 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 17.0773 seconds

Running but-1-yne_LUCJ_L2_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  331
  num selected half strs:  331
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022509 seconds
  Subspace dimension: 331 x 331 = 109_561

 19%|████████████████████████████████████▎                                                                                                                                                            | 203/1080 [2:09:16<13:40:15, 56.12s/it]

  Operator projection took: 13.286594 seconds
  CSR matrix memory: 2.308201 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0236 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 13.3573 seconds

Running but-1-yne_LUCJ_L2_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  293
  num selected half strs:  293
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019062 seconds
  Subspace dimension: 293 x 293 = 85_849

 19%|████████████████████████████████████▍                                                                                                                                                            | 204/1080 [2:10:11<13:34:00, 55.75s/it]

  Operator projection took: 8.595040 seconds
  CSR matrix memory: 32.953144 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0226 seconds
  Electronic Energy: [-256.11667261]
  Total Energy: [-153.03858747]
  num carryover full strs: 359
Iter 0 took: 8.6556 seconds

Running but-1-yne_LUCJ_L2_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  319
  num selected half strs:  319
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023484 seconds
  Subspace dimension: 319 x 319 = 101_761

 19%|████████████████████████████████████▋                                                                                                                                                            | 205/1080 [2:10:50<12:22:30, 50.91s/it]

  Operator projection took: 9.977708 seconds
  CSR matrix memory: 2.034687 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0191 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 10.0437 seconds

Running but-1-yne_LUCJ_L2_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  325
  num selected half strs:  325
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021717 seconds
  Subspace dimension: 325 x 325 = 105_625

 19%|████████████████████████████████████▊                                                                                                                                                            | 206/1080 [2:11:31<11:37:32, 47.89s/it]

  Operator projection took: 9.523590 seconds
  CSR matrix memory: 1.968769 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0189 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 9.5870 seconds

Running but-1-yne_LUCJ_L2_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  395
  num selected half strs:  395
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032690 seconds
  Subspace dimension: 395 x 395 = 156_025

 19%|████████████████████████████████████▉                                                                                                                                                            | 207/1080 [2:12:15<11:17:23, 46.56s/it]

  Operator projection took: 13.540580 seconds
  CSR matrix memory: 3.049778 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0354 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 13.6394 seconds

Running but-1-yne_LUCJ_L2_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  369
  num selected half strs:  369
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.034657 seconds
  Subspace dimension: 369 x 369 = 136_161

 19%|█████████████████████████████████████▏                                                                                                                                                           | 208/1080 [2:12:55<10:50:31, 44.76s/it]

  Operator projection took: 11.003589 seconds
  CSR matrix memory: 2.736469 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0259 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 11.0914 seconds

Running but-1-yne_LUCJ_L2_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  337
  num selected half strs:  337
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023166 seconds
  Subspace dimension: 337 x 337 = 113_569

 19%|█████████████████████████████████████▎                                                                                                                                                           | 209/1080 [2:13:32<10:17:05, 42.51s/it]

  Operator projection took: 8.774810 seconds
  CSR matrix memory: 1.979801 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0202 seconds
  Electronic Energy: [-257.99487041]
  Total Energy: [-154.91678527]
  num carryover full strs: 3
Iter 0 took: 8.8421 seconds

Running but-1-yne_LUCJ_L2_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  293
  num selected half strs:  293
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017095 seconds
  Subspace dimension: 293 x 293 = 85_849

 19%|█████████████████████████████████████▋                                                                                                                                                            | 210/1080 [2:14:06<9:40:00, 40.00s/it]

  Operator projection took: 5.559857 seconds
  CSR matrix memory: 29.068699 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0219 seconds
  Electronic Energy: [-257.99495836]
  Total Energy: [-154.91687322]
  num carryover full strs: 72
Iter 0 took: 5.6172 seconds

Running but-1-yne_LUCJ_L2_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  295
  num selected half strs:  295
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017976 seconds
  Subspace dimension: 295 x 295 = 87_025

 20%|█████████████████████████████████████▉                                                                                                                                                            | 211/1080 [2:14:47<9:43:23, 40.28s/it]

  Operator projection took: 8.047422 seconds
  CSR matrix memory: 1.692692 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0160 seconds
  Electronic Energy: [-257.98951998]
  Total Energy: [-154.91143484]
  num carryover full strs: 3
Iter 0 took: 8.1003 seconds

Running but-1-yne_LUCJ_L2_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  277
  num selected half strs:  277
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015592 seconds
  Subspace dimension: 277 x 277 = 76_729

 20%|██████████████████████████████████████                                                                                                                                                            | 212/1080 [2:15:27<9:41:41, 40.21s/it]

  Operator projection took: 7.052491 seconds
  CSR matrix memory: 1.462437 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0133 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 7.0982 seconds

Running but-1-yne_LUCJ_L2_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  289
  num selected half strs:  289
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017204 seconds
  Subspace dimension: 289 x 289 = 83_521

 20%|██████████████████████████████████████▎                                                                                                                                                           | 213/1080 [2:16:08<9:42:04, 40.28s/it]

  Operator projection took: 7.701543 seconds
  CSR matrix memory: 1.499332 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0141 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 7.7514 seconds

Running but-1-yne_LUCJ_L2_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  313
  num selected half strs:  313
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019587 seconds
  Subspace dimension: 313 x 313 = 97_969

 20%|██████████████████████████████████████▍                                                                                                                                                           | 214/1080 [2:16:51<9:51:26, 40.98s/it]

  Operator projection took: 9.300520 seconds
  CSR matrix memory: 2.040226 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0172 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 9.3598 seconds

Running but-1-yne_LUCJ_L2_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  361
  num selected half strs:  361
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027001 seconds
  Subspace dimension: 361 x 361 = 130_321

 20%|██████████████████████████████████████▍                                                                                                                                                          | 215/1080 [2:17:35<10:06:56, 42.10s/it]

  Operator projection took: 11.987144 seconds
  CSR matrix memory: 2.616917 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0236 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 12.0656 seconds

Running but-1-yne_LUCJ_L2_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  294
  num selected half strs:  294
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016537 seconds
  Subspace dimension: 294 x 294 = 86_436

 20%|██████████████████████████████████████▊                                                                                                                                                           | 216/1080 [2:18:15<9:54:33, 41.29s/it]

  Operator projection took: 6.528471 seconds
  CSR matrix memory: 15.794224 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0166 seconds
  Electronic Energy: [-257.9923352]
  Total Energy: [-154.91425006]
  num carryover full strs: 113
Iter 0 took: 6.5802 seconds

Running but-1-yne_LUCJ_L3_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  349
  num selected half strs:  349
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025035 seconds
  Subspace dimension: 349 x 349 = 121_801

 20%|██████████████████████████████████████▊                                                                                                                                                          | 217/1080 [2:19:11<10:59:43, 45.87s/it]

  Operator projection took: 13.929116 seconds
  CSR matrix memory: 2.513737 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0223 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 14.0014 seconds

Running but-1-yne_LUCJ_L3_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  295
  num selected half strs:  295
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017173 seconds
  Subspace dimension: 295 x 295 = 87_025

 20%|██████████████████████████████████████▉                                                                                                                                                          | 218/1080 [2:20:03<11:25:28, 47.71s/it]

  Operator projection took: 9.679024 seconds
  CSR matrix memory: 1.787037 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0150 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 9.7308 seconds

Running but-1-yne_LUCJ_L3_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  301
  num selected half strs:  301
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017985 seconds
  Subspace dimension: 301 x 301 = 90_601

 20%|███████████████████████████████████████▏                                                                                                                                                         | 219/1080 [2:20:56<11:46:35, 49.24s/it]

  Operator projection took: 10.297555 seconds
  CSR matrix memory: 1.823566 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0166 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 10.3527 seconds

Running but-1-yne_LUCJ_L3_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  349
  num selected half strs:  349
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025122 seconds
  Subspace dimension: 349 x 349 = 121_801

 20%|███████████████████████████████████████▎                                                                                                                                                         | 220/1080 [2:21:52<12:14:10, 51.22s/it]

  Operator projection took: 13.594672 seconds
  CSR matrix memory: 2.481602 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0218 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 13.6682 seconds

Running but-1-yne_LUCJ_L3_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  385
  num selected half strs:  385
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029912 seconds
  Subspace dimension: 385 x 385 = 148_225

 20%|███████████████████████████████████████▍                                                                                                                                                         | 221/1080 [2:22:51<12:47:40, 53.62s/it]

  Operator projection took: 16.782933 seconds
  CSR matrix memory: 3.231236 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0279 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 16.8708 seconds

Running but-1-yne_LUCJ_L3_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  285
  num selected half strs:  285
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015772 seconds
  Subspace dimension: 285 x 285 = 81_225

 21%|███████████████████████████████████████▋                                                                                                                                                         | 222/1080 [2:23:41<12:30:59, 52.52s/it]

  Operator projection took: 7.434065 seconds
  CSR matrix memory: 29.534229 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0220 seconds
  Electronic Energy: [-256.11284138]
  Total Energy: [-153.03475624]
  num carryover full strs: 414
Iter 0 took: 7.4894 seconds

Running but-1-yne_LUCJ_L3_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  351
  num selected half strs:  351
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025687 seconds
  Subspace dimension: 351 x 351 = 123_201

 21%|███████████████████████████████████████▊                                                                                                                                                         | 223/1080 [2:24:19<11:28:44, 48.22s/it]

  Operator projection took: 9.576012 seconds
  CSR matrix memory: 2.265568 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0221 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 9.6491 seconds

Running but-1-yne_LUCJ_L3_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  349
  num selected half strs:  349
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025810 seconds
  Subspace dimension: 349 x 349 = 121_801

 21%|████████████████████████████████████████                                                                                                                                                         | 224/1080 [2:24:57<10:43:13, 45.09s/it]

  Operator projection took: 9.353026 seconds
  CSR matrix memory: 2.385792 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0225 seconds
  Electronic Energy: [-257.99487038]
  Total Energy: [-154.91678523]
  num carryover full strs: 1
Iter 0 took: 9.4254 seconds

Running but-1-yne_LUCJ_L3_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  347
  num selected half strs:  347
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024070 seconds
  Subspace dimension: 347 x 347 = 120_409

 21%|████████████████████████████████████████▏                                                                                                                                                        | 225/1080 [2:25:35<10:12:06, 42.96s/it]

  Operator projection took: 9.341198 seconds
  CSR matrix memory: 2.329899 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0217 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 9.4128 seconds

Running but-1-yne_LUCJ_L3_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  339
  num selected half strs:  339
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024037 seconds
  Subspace dimension: 339 x 339 = 114_921

 21%|████████████████████████████████████████▌                                                                                                                                                         | 226/1080 [2:26:12<9:47:59, 41.31s/it]

  Operator projection took: 9.183914 seconds
  CSR matrix memory: 2.079441 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0209 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 9.2543 seconds

Running but-1-yne_LUCJ_L3_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  315
  num selected half strs:  315
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020533 seconds
  Subspace dimension: 315 x 315 = 99_225

 21%|████████████████████████████████████████▊                                                                                                                                                         | 227/1080 [2:26:49<9:27:50, 39.94s/it]

  Operator projection took: 8.451483 seconds
  CSR matrix memory: 1.889194 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0171 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 8.5112 seconds

Running but-1-yne_LUCJ_L3_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  291
  num selected half strs:  291
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015913 seconds
  Subspace dimension: 291 x 291 = 84_681

 21%|████████████████████████████████████████▉                                                                                                                                                         | 228/1080 [2:27:23<9:02:10, 38.18s/it]

  Operator projection took: 5.432457 seconds
  CSR matrix memory: 20.326038 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0189 seconds
  Electronic Energy: [-257.9949076]
  Total Energy: [-154.91682246]
  num carryover full strs: 115
Iter 0 took: 5.4866 seconds

Running but-1-yne_LUCJ_L3_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  319
  num selected half strs:  319
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020958 seconds
  Subspace dimension: 319 x 319 = 101_761

 21%|█████████████████████████████████████████▏                                                                                                                                                        | 229/1080 [2:28:06<9:20:48, 39.54s/it]

  Operator projection took: 9.871506 seconds
  CSR matrix memory: 2.034687 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0177 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 9.9334 seconds

Running but-1-yne_LUCJ_L3_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  357
  num selected half strs:  357
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.026455 seconds
  Subspace dimension: 357 x 357 = 127_449

 21%|█████████████████████████████████████████▎                                                                                                                                                        | 230/1080 [2:28:50<9:41:15, 41.03s/it]

  Operator projection took: 11.647974 seconds
  CSR matrix memory: 2.549427 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0243 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 11.7241 seconds

Running but-1-yne_LUCJ_L3_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  359
  num selected half strs:  359
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.026071 seconds
  Subspace dimension: 359 x 359 = 128_881

 21%|█████████████████████████████████████████▍                                                                                                                                                        | 231/1080 [2:29:35<9:56:10, 42.13s/it]

  Operator projection took: 11.908352 seconds
  CSR matrix memory: 2.492496 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0245 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 11.9857 seconds

Running but-1-yne_LUCJ_L3_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024093 seconds
  Subspace dimension: 343 x 343 = 117_649

 21%|█████████████████████████████████████████▍                                                                                                                                                       | 232/1080 [2:30:19<10:01:55, 42.59s/it]

  Operator projection took: 11.022382 seconds
  CSR matrix memory: 2.454639 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0203 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 11.0921 seconds

Running but-1-yne_LUCJ_L3_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023317 seconds
  Subspace dimension: 343 x 343 = 117_649

 22%|█████████████████████████████████████████▋                                                                                                                                                       | 233/1080 [2:31:02<10:04:48, 42.84s/it]

  Operator projection took: 10.740354 seconds
  CSR matrix memory: 2.344776 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0218 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 10.8126 seconds

Running but-1-yne_LUCJ_L3_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  312
  num selected half strs:  312
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019102 seconds
  Subspace dimension: 312 x 312 = 97_344

 22%|██████████████████████████████████████████                                                                                                                                                        | 234/1080 [2:31:42<9:51:13, 41.93s/it]

  Operator projection took: 7.246947 seconds
  CSR matrix memory: 28.183918 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0185 seconds
  Electronic Energy: [-257.99140977]
  Total Energy: [-154.91332462]
  num carryover full strs: 208
Iter 0 took: 7.3056 seconds

Running but-1-yne_LUCJ_L4_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  351
  num selected half strs:  351
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024996 seconds
  Subspace dimension: 351 x 351 = 123_201

 22%|█████████████████████████████████████████▉                                                                                                                                                       | 235/1080 [2:32:38<10:51:03, 46.23s/it]

  Operator projection took: 13.801793 seconds
  CSR matrix memory: 2.474445 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0221 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 13.8739 seconds

Running but-1-yne_LUCJ_L4_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024556 seconds
  Subspace dimension: 343 x 343 = 117_649

 22%|██████████████████████████████████████████▏                                                                                                                                                      | 236/1080 [2:33:34<11:28:37, 48.95s/it]

  Operator projection took: 12.900706 seconds
  CSR matrix memory: 2.580433 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0216 seconds
  Electronic Energy: [-256.10298011]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 12.9713 seconds

Running but-1-yne_LUCJ_L4_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  367
  num selected half strs:  367
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.035238 seconds
  Subspace dimension: 367 x 367 = 134_689

 22%|██████████████████████████████████████████▎                                                                                                                                                      | 237/1080 [2:34:31<12:02:05, 51.39s/it]

  Operator projection took: 14.939764 seconds
  CSR matrix memory: 2.912037 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0243 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 15.0264 seconds

Running but-1-yne_LUCJ_L4_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  337
  num selected half strs:  337
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023549 seconds
  Subspace dimension: 337 x 337 = 113_569

 22%|██████████████████████████████████████████▌                                                                                                                                                      | 238/1080 [2:35:26<12:15:34, 52.42s/it]

  Operator projection took: 12.679968 seconds
  CSR matrix memory: 2.303944 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0203 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 12.7464 seconds

Running but-1-yne_LUCJ_L4_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  335
  num selected half strs:  335
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023432 seconds
  Subspace dimension: 335 x 335 = 112_225

 22%|██████████████████████████████████████████▋                                                                                                                                                      | 239/1080 [2:36:20<12:23:44, 53.06s/it]

  Operator projection took: 12.243630 seconds
  CSR matrix memory: 2.387165 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0196 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 12.3097 seconds

Running but-1-yne_LUCJ_L4_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  293
  num selected half strs:  293
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016544 seconds
  Subspace dimension: 293 x 293 = 85_849

 22%|██████████████████████████████████████████▉                                                                                                                                                      | 240/1080 [2:37:10<12:10:07, 52.15s/it]

  Operator projection took: 7.692295 seconds
  CSR matrix memory: 42.183857 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0261 seconds
  Electronic Energy: [-256.12445651]
  Total Energy: [-153.04637137]
  num carryover full strs: 527
Iter 0 took: 7.7536 seconds

Running but-1-yne_LUCJ_L4_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  357
  num selected half strs:  357
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.026306 seconds
  Subspace dimension: 357 x 357 = 127_449

 22%|███████████████████████████████████████████                                                                                                                                                      | 241/1080 [2:37:49<11:12:18, 48.08s/it]

  Operator projection took: 10.090066 seconds
  CSR matrix memory: 2.467716 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0247 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 10.1676 seconds

Running but-1-yne_LUCJ_L4_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  383
  num selected half strs:  383
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.031142 seconds
  Subspace dimension: 383 x 383 = 146_689

 22%|███████████████████████████████████████████▏                                                                                                                                                     | 242/1080 [2:38:29<10:38:40, 45.73s/it]

  Operator projection took: 11.696997 seconds
  CSR matrix memory: 2.851933 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0265 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 11.7867 seconds

Running but-1-yne_LUCJ_L4_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  333
  num selected half strs:  333
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022950 seconds
  Subspace dimension: 333 x 333 = 110_889

 22%|███████████████████████████████████████████▍                                                                                                                                                     | 243/1080 [2:39:06<10:01:17, 43.10s/it]

  Operator projection took: 8.610666 seconds
  CSR matrix memory: 2.240849 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0230 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 8.6801 seconds

Running but-1-yne_LUCJ_L4_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  335
  num selected half strs:  335
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022974 seconds
  Subspace dimension: 335 x 335 = 112_225

 23%|███████████████████████████████████████████▊                                                                                                                                                      | 244/1080 [2:39:43<9:35:50, 41.33s/it]

  Operator projection took: 8.664046 seconds
  CSR matrix memory: 2.264713 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0196 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 8.7307 seconds

Running but-1-yne_LUCJ_L4_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  345
  num selected half strs:  345
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024685 seconds
  Subspace dimension: 345 x 345 = 119_025

 23%|████████████████████████████████████████████                                                                                                                                                      | 245/1080 [2:40:21<9:19:35, 40.21s/it]

  Operator projection took: 9.154809 seconds
  CSR matrix memory: 2.369114 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0220 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 9.2254 seconds

Running but-1-yne_LUCJ_L4_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  242
  num selected half strs:  242
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011380 seconds
  Subspace dimension: 242 x 242 = 58_564

 23%|████████████████████████████████████████████▏                                                                                                                                                     | 246/1080 [2:40:53<8:45:12, 37.78s/it]

  Operator projection took: 3.755643 seconds
  CSR matrix memory: 11.770908 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0121 seconds
  Electronic Energy: [-257.99490657]
  Total Energy: [-154.91682143]
  num carryover full strs: 68
Iter 0 took: 3.7938 seconds

Running but-1-yne_LUCJ_L4_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  373
  num selected half strs:  373
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029614 seconds
  Subspace dimension: 373 x 373 = 139_129

 23%|████████████████████████████████████████████▎                                                                                                                                                     | 247/1080 [2:41:39<9:18:09, 40.20s/it]

  Operator projection took: 12.817030 seconds
  CSR matrix memory: 2.788944 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0263 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 12.9030 seconds

Running but-1-yne_LUCJ_L4_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  365
  num selected half strs:  365
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027724 seconds
  Subspace dimension: 365 x 365 = 133_225

 23%|████████████████████████████████████████████▌                                                                                                                                                     | 248/1080 [2:42:24<9:38:43, 41.73s/it]

  Operator projection took: 12.417202 seconds
  CSR matrix memory: 2.784779 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0247 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 12.4976 seconds

Running but-1-yne_LUCJ_L4_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  413
  num selected half strs:  413
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.035579 seconds
  Subspace dimension: 413 x 413 = 170_569

 23%|████████████████████████████████████████████▍                                                                                                                                                    | 249/1080 [2:43:13<10:08:38, 43.94s/it]

  Operator projection took: 16.279655 seconds
  CSR matrix memory: 3.585773 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0349 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 16.3856 seconds

Running but-1-yne_LUCJ_L4_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  309
  num selected half strs:  309
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019942 seconds
  Subspace dimension: 309 x 309 = 95_481

 23%|████████████████████████████████████████████▉                                                                                                                                                     | 250/1080 [2:43:55<9:59:45, 43.36s/it]

  Operator projection took: 9.077885 seconds
  CSR matrix memory: 1.952000 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0182 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 9.1374 seconds

Running but-1-yne_LUCJ_L4_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  375
  num selected half strs:  375
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028550 seconds
  Subspace dimension: 375 x 375 = 140_625

 23%|████████████████████████████████████████████▊                                                                                                                                                    | 251/1080 [2:44:41<10:09:26, 44.11s/it]

  Operator projection took: 12.912579 seconds
  CSR matrix memory: 2.729420 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0249 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 12.9970 seconds

Running but-1-yne_LUCJ_L4_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  340
  num selected half strs:  340
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022352 seconds
  Subspace dimension: 340 x 340 = 115_600

 23%|█████████████████████████████████████████████▎                                                                                                                                                    | 252/1080 [2:45:22<9:57:59, 43.33s/it]

  Operator projection took: 8.638188 seconds
  CSR matrix memory: 25.662296 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0208 seconds
  Electronic Energy: [-257.99178097]
  Total Energy: [-154.91369582]
  num carryover full strs: 160
Iter 0 took: 8.7029 seconds

Running but-1-yne_LUCJ_L5_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  349
  num selected half strs:  349
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025413 seconds
  Subspace dimension: 349 x 349 = 121_801

 23%|█████████████████████████████████████████████▏                                                                                                                                                   | 253/1080 [2:46:18<10:48:27, 47.05s/it]

  Operator projection took: 13.534867 seconds
  CSR matrix memory: 2.593479 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0216 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 13.6078 seconds

Running but-1-yne_LUCJ_L5_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  363
  num selected half strs:  363
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027307 seconds
  Subspace dimension: 363 x 363 = 131_769

 24%|█████████████████████████████████████████████▍                                                                                                                                                   | 254/1080 [2:47:15<11:28:14, 49.99s/it]

  Operator projection took: 14.593890 seconds
  CSR matrix memory: 2.791630 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0249 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 14.6717 seconds

Running but-1-yne_LUCJ_L5_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  371
  num selected half strs:  371
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029133 seconds
  Subspace dimension: 371 x 371 = 137_641

 24%|█████████████████████████████████████████████▌                                                                                                                                                   | 255/1080 [2:48:13<11:58:54, 52.28s/it]

  Operator projection took: 15.346885 seconds
  CSR matrix memory: 3.000523 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0246 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 15.4304 seconds

Running but-1-yne_LUCJ_L5_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  369
  num selected half strs:  369
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028349 seconds
  Subspace dimension: 369 x 369 = 136_161

 24%|█████████████████████████████████████████████▋                                                                                                                                                   | 256/1080 [2:49:10<12:19:44, 53.86s/it]

  Operator projection took: 15.255515 seconds
  CSR matrix memory: 2.973087 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0250 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 15.3372 seconds

Running but-1-yne_LUCJ_L5_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  429
  num selected half strs:  429
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.037516 seconds
  Subspace dimension: 429 x 429 = 184_041

 24%|█████████████████████████████████████████████▉                                                                                                                                                   | 257/1080 [2:50:14<12:57:40, 56.70s/it]

  Operator projection took: 21.188675 seconds
  CSR matrix memory: 3.829426 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0412 seconds
  Electronic Energy: [-256.1029801]
  Total Energy: [-153.02489496]
  num carryover full strs: 1
Iter 0 took: 21.3027 seconds

Running but-1-yne_LUCJ_L5_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  250
  num selected half strs:  250
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011752 seconds
  Subspace dimension: 250 x 250 = 62_500

 24%|██████████████████████████████████████████████                                                                                                                                                   | 258/1080 [2:51:01<12:20:45, 54.07s/it]

  Operator projection took: 5.618558 seconds
  CSR matrix memory: 28.158848 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0153 seconds
  Electronic Energy: [-256.11369132]
  Total Energy: [-153.03560617]
  num carryover full strs: 309
Iter 0 took: 5.6614 seconds

Running but-1-yne_LUCJ_L5_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  359
  num selected half strs:  359
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027033 seconds
  Subspace dimension: 359 x 359 = 128_881

 24%|██████████████████████████████████████████████▎                                                                                                                                                  | 259/1080 [2:51:40<11:15:47, 49.39s/it]

  Operator projection took: 9.971402 seconds
  CSR matrix memory: 2.311680 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0252 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 10.0508 seconds

Running but-1-yne_LUCJ_L5_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  359
  num selected half strs:  359
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.026762 seconds
  Subspace dimension: 359 x 359 = 128_881

 24%|██████████████████████████████████████████████▍                                                                                                                                                  | 260/1080 [2:52:19<10:30:59, 46.17s/it]

  Operator projection took: 10.132558 seconds
  CSR matrix memory: 2.443333 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0234 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 10.2094 seconds

Running but-1-yne_LUCJ_L5_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  373
  num selected half strs:  373
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028569 seconds
  Subspace dimension: 373 x 373 = 139_129

 24%|██████████████████████████████████████████████▋                                                                                                                                                  | 261/1080 [2:52:58<10:01:50, 44.09s/it]

  Operator projection took: 10.757374 seconds
  CSR matrix memory: 2.737675 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0286 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 10.8431 seconds

Running but-1-yne_LUCJ_L5_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  323
  num selected half strs:  323
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022179 seconds
  Subspace dimension: 323 x 323 = 104_329

 24%|███████████████████████████████████████████████                                                                                                                                                   | 262/1080 [2:53:35<9:31:57, 41.95s/it]

  Operator projection took: 8.427092 seconds
  CSR matrix memory: 2.095112 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0181 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 8.4913 seconds

Running but-1-yne_LUCJ_L5_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  401
  num selected half strs:  401
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032771 seconds
  Subspace dimension: 401 x 401 = 160_801

 24%|███████████████████████████████████████████████▏                                                                                                                                                  | 263/1080 [2:54:16<9:29:20, 41.81s/it]

  Operator projection took: 13.015643 seconds
  CSR matrix memory: 3.371540 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0318 seconds
  Electronic Energy: [-257.99487036]
  Total Energy: [-154.91678522]
  num carryover full strs: 1
Iter 0 took: 13.1127 seconds

Running but-1-yne_LUCJ_L5_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  285
  num selected half strs:  285
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015869 seconds
  Subspace dimension: 285 x 285 = 81_225

 24%|███████████████████████████████████████████████▍                                                                                                                                                  | 264/1080 [2:54:50<8:55:41, 39.39s/it]

  Operator projection took: 5.272074 seconds
  CSR matrix memory: 16.874088 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0176 seconds
  Electronic Energy: [-257.99493906]
  Total Energy: [-154.91685392]
  num carryover full strs: 83
Iter 0 took: 5.3229 seconds

Running but-1-yne_LUCJ_L5_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  387
  num selected half strs:  387
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.030335 seconds
  Subspace dimension: 387 x 387 = 149_769

 25%|███████████████████████████████████████████████▌                                                                                                                                                  | 265/1080 [2:55:37<9:25:14, 41.61s/it]

  Operator projection took: 14.021997 seconds
  CSR matrix memory: 3.153400 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0293 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 14.1118 seconds

Running but-1-yne_LUCJ_L5_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  347
  num selected half strs:  347
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025146 seconds
  Subspace dimension: 347 x 347 = 120_409

 25%|███████████████████████████████████████████████▊                                                                                                                                                  | 266/1080 [2:56:21<9:33:46, 42.29s/it]

  Operator projection took: 11.163854 seconds
  CSR matrix memory: 2.504536 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0225 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 11.2381 seconds

Running but-1-yne_LUCJ_L5_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  395
  num selected half strs:  395
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.031648 seconds
  Subspace dimension: 395 x 395 = 156_025

 25%|███████████████████████████████████████████████▉                                                                                                                                                  | 267/1080 [2:57:08<9:53:55, 43.83s/it]

  Operator projection took: 14.668830 seconds
  CSR matrix memory: 3.176579 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0306 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 14.7639 seconds

Running but-1-yne_LUCJ_L5_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  399
  num selected half strs:  399
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032704 seconds
  Subspace dimension: 399 x 399 = 159_201

 25%|███████████████████████████████████████████████▉                                                                                                                                                 | 268/1080 [2:57:56<10:08:43, 44.98s/it]

  Operator projection took: 15.097257 seconds
  CSR matrix memory: 3.178257 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0308 seconds
  Electronic Energy: [-257.98947354]
  Total Energy: [-154.91138839]
  num carryover full strs: 3
Iter 0 took: 15.1920 seconds

Running but-1-yne_LUCJ_L5_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  381
  num selected half strs:  381
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029145 seconds
  Subspace dimension: 381 x 381 = 145_161

 25%|████████████████████████████████████████████████                                                                                                                                                 | 269/1080 [2:58:42<10:14:03, 45.43s/it]

  Operator projection took: 13.681736 seconds
  CSR matrix memory: 2.912617 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0275 seconds
  Electronic Energy: [-257.98947342]
  Total Energy: [-154.91138827]
  num carryover full strs: 1
Iter 0 took: 13.7677 seconds

Running but-1-yne_LUCJ_L5_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  371
  num selected half strs:  371
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.026253 seconds
  Subspace dimension: 371 x 371 = 137_641

 25%|████████████████████████████████████████████████▎                                                                                                                                                | 270/1080 [2:59:25<10:03:39, 44.72s/it]

  Operator projection took: 10.316254 seconds
  CSR matrix memory: 38.967518 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0335 seconds
  Electronic Energy: [-258.00141484]
  Total Energy: [-154.92332969]
  num carryover full strs: 202
Iter 0 took: 10.4040 seconds

Running buta-1,3-diene_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  333
  num selected half strs:  333
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022131 seconds
  Subspace dimension: 333 x 333 = 110_889

 25%|████████████████████████████████████████████████▍                                                                                                                                                | 271/1080 [3:00:12<10:09:56, 45.24s/it]

  Operator projection took: 10.382009 seconds
  CSR matrix memory: 3.125706 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0196 seconds
  Electronic Energy: [-257.16408854]
  Total Energy: [-153.0166648]
  num carryover full strs: 10
Iter 0 took: 10.4466 seconds

Running buta-1,3-diene_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  324
  num selected half strs:  324
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022613 seconds
  Subspace dimension: 324 x 324 = 104_976

 25%|████████████████████████████████████████████████▌                                                                                                                                                | 272/1080 [3:00:58<10:11:56, 45.44s/it]

  Operator projection took: 9.936545 seconds
  CSR matrix memory: 2.298939 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0149 seconds
  Electronic Energy: [-257.16402212]
  Total Energy: [-153.01659837]
  num carryover full strs: 5
Iter 0 took: 9.9968 seconds

Running buta-1,3-diene_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  317
  num selected half strs:  317
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020123 seconds
  Subspace dimension: 317 x 317 = 100_489

 25%|████████████████████████████████████████████████▊                                                                                                                                                | 273/1080 [3:01:44<10:13:53, 45.64s/it]

  Operator projection took: 10.030803 seconds
  CSR matrix memory: 2.447956 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0178 seconds
  Electronic Energy: [-257.1641605]
  Total Energy: [-153.01673676]
  num carryover full strs: 4
Iter 0 took: 10.0905 seconds

Running buta-1,3-diene_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  285
  num selected half strs:  285
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016098 seconds
  Subspace dimension: 285 x 285 = 81_225

 25%|████████████████████████████████████████████████▉                                                                                                                                                | 274/1080 [3:02:28<10:05:42, 45.09s/it]

  Operator projection took: 7.713345 seconds
  CSR matrix memory: 2.152821 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0147 seconds
  Electronic Energy: [-257.16435932]
  Total Energy: [-153.01693557]
  num carryover full strs: 2
Iter 0 took: 7.7634 seconds

Running buta-1,3-diene_LUCJ_L1_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  371
  num selected half strs:  371
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028372 seconds
  Subspace dimension: 371 x 371 = 137_641

 25%|█████████████████████████████████████████████████▏                                                                                                                                               | 275/1080 [3:03:18<10:25:07, 46.59s/it]

  Operator projection took: 14.178346 seconds
  CSR matrix memory: 3.221302 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0271 seconds
  Electronic Energy: [-257.16396554]
  Total Energy: [-153.0165418]
  num carryover full strs: 3
Iter 0 took: 14.2596 seconds

Running buta-1,3-diene_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  212
  num selected half strs:  212
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.008796 seconds
  Subspace dimension: 212 x 212 = 44_944

 26%|█████████████████████████████████████████████████▌                                                                                                                                                | 276/1080 [3:03:58<9:57:49, 44.61s/it]

  Operator projection took: 3.871792 seconds
  CSR matrix memory: 13.092197 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0145 seconds
  Electronic Energy: [-257.18074322]
  Total Energy: [-153.03331947]
  num carryover full strs: 145
Iter 0 took: 3.9064 seconds

Running buta-1,3-diene_LUCJ_L1_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  299
  num selected half strs:  299
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018382 seconds
  Subspace dimension: 299 x 299 = 89_401

 26%|█████████████████████████████████████████████████▊                                                                                                                                                | 277/1080 [3:04:26<8:51:36, 39.72s/it]

  Operator projection took: 5.893615 seconds
  CSR matrix memory: 1.556004 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0164 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 5.9493 seconds

Running buta-1,3-diene_LUCJ_L1_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  369
  num selected half strs:  369
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027964 seconds
  Subspace dimension: 369 x 369 = 136_161

 26%|█████████████████████████████████████████████████▉                                                                                                                                                | 278/1080 [3:04:57<8:16:53, 37.17s/it]

  Operator projection took: 8.611894 seconds
  CSR matrix memory: 3.041752 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0249 seconds
  Electronic Energy: [-259.0873694]
  Total Energy: [-154.93994566]
  num carryover full strs: 8
Iter 0 took: 8.6949 seconds

Running buta-1,3-diene_LUCJ_L1_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  363
  num selected half strs:  363
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027223 seconds
  Subspace dimension: 363 x 363 = 131_769

 26%|██████████████████████████████████████████████████                                                                                                                                                | 279/1080 [3:05:28<7:51:55, 35.35s/it]

  Operator projection took: 8.522736 seconds
  CSR matrix memory: 2.792271 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0249 seconds
  Electronic Energy: [-259.08733679]
  Total Energy: [-154.93991305]
  num carryover full strs: 1
Iter 0 took: 8.6017 seconds

Running buta-1,3-diene_LUCJ_L1_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  347
  num selected half strs:  347
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024600 seconds
  Subspace dimension: 347 x 347 = 120_409

 26%|██████████████████████████████████████████████████▎                                                                                                                                               | 280/1080 [3:05:59<7:30:46, 33.81s/it]

  Operator projection took: 7.593881 seconds
  CSR matrix memory: 2.329762 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0225 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.6684 seconds

Running buta-1,3-diene_LUCJ_L1_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  403
  num selected half strs:  403
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032942 seconds
  Subspace dimension: 403 x 403 = 162_409

 26%|██████████████████████████████████████████████████▍                                                                                                                                               | 281/1080 [3:06:32<7:29:25, 33.75s/it]

  Operator projection took: 11.072936 seconds
  CSR matrix memory: 3.086994 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0328 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 11.1691 seconds

Running buta-1,3-diene_LUCJ_L1_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  273
  num selected half strs:  273
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.013992 seconds
  Subspace dimension: 273 x 273 = 74_529

 26%|██████████████████████████████████████████████████▋                                                                                                                                               | 282/1080 [3:06:59<6:59:34, 31.55s/it]

  Operator projection took: 3.839425 seconds
  CSR matrix memory: 30.138615 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0223 seconds
  Electronic Energy: [-259.09113341]
  Total Energy: [-154.94370967]
  num carryover full strs: 191
Iter 0 took: 3.8924 seconds

Running buta-1,3-diene_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  303
  num selected half strs:  303
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018209 seconds
  Subspace dimension: 303 x 303 = 91_809

 26%|██████████████████████████████████████████████████▊                                                                                                                                               | 283/1080 [3:07:33<7:09:36, 32.34s/it]

  Operator projection took: 7.479342 seconds
  CSR matrix memory: 2.206104 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0172 seconds
  Electronic Energy: [-259.08134437]
  Total Energy: [-154.93392062]
  num carryover full strs: 3
Iter 0 took: 7.5350 seconds

Running buta-1,3-diene_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  293
  num selected half strs:  293
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017314 seconds
  Subspace dimension: 293 x 293 = 85_849

 26%|███████████████████████████████████████████████████                                                                                                                                               | 284/1080 [3:08:06<7:14:10, 32.73s/it]

  Operator projection took: 6.966225 seconds
  CSR matrix memory: 1.994038 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0161 seconds
  Electronic Energy: [-259.08135309]
  Total Energy: [-154.93392935]
  num carryover full strs: 3
Iter 0 took: 7.0182 seconds

Running buta-1,3-diene_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  323
  num selected half strs:  323
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021088 seconds
  Subspace dimension: 323 x 323 = 104_329

 26%|███████████████████████████████████████████████████▏                                                                                                                                              | 285/1080 [3:08:42<7:23:49, 33.50s/it]

  Operator projection took: 8.642927 seconds
  CSR matrix memory: 2.375813 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0187 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 8.7059 seconds

Running buta-1,3-diene_LUCJ_L1_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  288
  num selected half strs:  288
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016682 seconds
  Subspace dimension: 288 x 288 = 82_944

 26%|███████████████████████████████████████████████████▎                                                                                                                                              | 286/1080 [3:09:15<7:22:55, 33.47s/it]

  Operator projection took: 6.569854 seconds
  CSR matrix memory: 2.109791 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0121 seconds
  Electronic Energy: [-259.08156051]
  Total Energy: [-154.93413677]
  num carryover full strs: 10
Iter 0 took: 6.6181 seconds

Running buta-1,3-diene_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  453
  num selected half strs:  453
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.043546 seconds
  Subspace dimension: 453 x 453 = 205_209

 27%|███████████████████████████████████████████████████▌                                                                                                                                              | 287/1080 [3:10:00<8:08:20, 36.95s/it]

  Operator projection took: 18.242829 seconds
  CSR matrix memory: 4.188816 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0477 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 18.3748 seconds

Running buta-1,3-diene_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  212
  num selected half strs:  212
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.008676 seconds
  Subspace dimension: 212 x 212 = 44_944

 27%|███████████████████████████████████████████████████▋                                                                                                                                              | 288/1080 [3:10:30<7:40:51, 34.91s/it]

  Operator projection took: 3.197637 seconds
  CSR matrix memory: 13.375782 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0107 seconds
  Electronic Energy: [-259.0821574]
  Total Energy: [-154.93473366]
  num carryover full strs: 123
Iter 0 took: 3.2287 seconds

Running buta-1,3-diene_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  311
  num selected half strs:  311
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019805 seconds
  Subspace dimension: 311 x 311 = 96_721

 27%|███████████████████████████████████████████████████▉                                                                                                                                              | 289/1080 [3:11:16<8:24:26, 38.26s/it]

  Operator projection took: 10.031124 seconds
  CSR matrix memory: 1.860279 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0171 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 10.0890 seconds

Running buta-1,3-diene_LUCJ_L2_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  299
  num selected half strs:  299
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018545 seconds
  Subspace dimension: 299 x 299 = 89_401

 27%|████████████████████████████████████████████████████                                                                                                                                              | 290/1080 [3:12:02<8:50:59, 40.33s/it]

  Operator projection took: 9.150481 seconds
  CSR matrix memory: 1.706333 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0161 seconds
  Electronic Energy: [-257.16398011]
  Total Energy: [-153.01655637]
  num carryover full strs: 3
Iter 0 took: 9.2053 seconds

Running buta-1,3-diene_LUCJ_L2_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  299
  num selected half strs:  299
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018720 seconds
  Subspace dimension: 299 x 299 = 89_401

 27%|████████████████████████████████████████████████████▎                                                                                                                                             | 291/1080 [3:12:47<9:08:50, 41.74s/it]

  Operator projection took: 9.046882 seconds
  CSR matrix memory: 1.706379 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0153 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 9.1008 seconds

Running buta-1,3-diene_LUCJ_L2_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  335
  num selected half strs:  335
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022463 seconds
  Subspace dimension: 335 x 335 = 112_225

 27%|████████████████████████████████████████████████████▍                                                                                                                                             | 292/1080 [3:13:34<9:29:54, 43.39s/it]

  Operator projection took: 11.209658 seconds
  CSR matrix memory: 2.218479 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0210 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 11.2795 seconds

Running buta-1,3-diene_LUCJ_L2_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  385
  num selected half strs:  385
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.031166 seconds
  Subspace dimension: 385 x 385 = 148_225

 27%|████████████████████████████████████████████████████▎                                                                                                                                            | 293/1080 [3:14:25<10:00:22, 45.77s/it]

  Operator projection took: 15.264680 seconds
  CSR matrix memory: 3.231144 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0297 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 15.3549 seconds

Running buta-1,3-diene_LUCJ_L2_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  212
  num selected half strs:  212
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.008818 seconds
  Subspace dimension: 212 x 212 = 44_944

 27%|████████████████████████████████████████████████████▊                                                                                                                                             | 294/1080 [3:15:05<9:37:13, 44.06s/it]

  Operator projection took: 3.874366 seconds
  CSR matrix memory: 12.588886 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0098 seconds
  Electronic Energy: [-257.1701881]
  Total Energy: [-153.02276436]
  num carryover full strs: 156
Iter 0 took: 3.9043 seconds

Running buta-1,3-diene_LUCJ_L2_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  283
  num selected half strs:  283
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016247 seconds
  Subspace dimension: 283 x 283 = 80_089

 27%|████████████████████████████████████████████████████▉                                                                                                                                             | 295/1080 [3:15:33<8:33:00, 39.21s/it]

  Operator projection took: 5.438489 seconds
  CSR matrix memory: 1.545933 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0147 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 5.4879 seconds

Running buta-1,3-diene_LUCJ_L2_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  309
  num selected half strs:  309
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019250 seconds
  Subspace dimension: 309 x 309 = 95_481

 27%|█████████████████████████████████████████████████████▏                                                                                                                                            | 296/1080 [3:16:03<7:53:55, 36.27s/it]

  Operator projection took: 6.786484 seconds
  CSR matrix memory: 1.669102 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0170 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 6.8441 seconds

Running buta-1,3-diene_LUCJ_L2_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  311
  num selected half strs:  311
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020234 seconds
  Subspace dimension: 311 x 311 = 96_721

 28%|█████████████████████████████████████████████████████▎                                                                                                                                            | 297/1080 [3:16:32<7:26:22, 34.21s/it]

  Operator projection took: 6.696061 seconds
  CSR matrix memory: 1.717869 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0181 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 6.7546 seconds

Running buta-1,3-diene_LUCJ_L2_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  311
  num selected half strs:  311
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020115 seconds
  Subspace dimension: 311 x 311 = 96_721

 28%|█████████████████████████████████████████████████████▌                                                                                                                                            | 298/1080 [3:17:01<7:06:09, 32.70s/it]

  Operator projection took: 6.726611 seconds
  CSR matrix memory: 1.817616 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0176 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 6.7861 seconds

Running buta-1,3-diene_LUCJ_L2_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  329
  num selected half strs:  329
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021826 seconds
  Subspace dimension: 329 x 329 = 108_241

 28%|█████████████████████████████████████████████████████▋                                                                                                                                            | 299/1080 [3:17:31<6:53:17, 31.75s/it]

  Operator projection took: 7.064461 seconds
  CSR matrix memory: 2.088612 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0203 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.1305 seconds

Running buta-1,3-diene_LUCJ_L2_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  251
  num selected half strs:  251
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011872 seconds
  Subspace dimension: 251 x 251 = 63_001

 28%|█████████████████████████████████████████████████████▉                                                                                                                                            | 300/1080 [3:17:57<6:30:50, 30.06s/it]

  Operator projection took: 3.260954 seconds
  CSR matrix memory: 23.852802 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0190 seconds
  Electronic Energy: [-259.09195732]
  Total Energy: [-154.94453358]
  num carryover full strs: 163
Iter 0 took: 3.3068 seconds

Running buta-1,3-diene_LUCJ_L2_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  321
  num selected half strs:  321
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021381 seconds
  Subspace dimension: 321 x 321 = 103_041

 28%|██████████████████████████████████████████████████████                                                                                                                                            | 301/1080 [3:18:33<6:53:00, 31.81s/it]

  Operator projection took: 9.168206 seconds
  CSR matrix memory: 1.969074 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0188 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.2314 seconds

Running buta-1,3-diene_LUCJ_L2_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  311
  num selected half strs:  311
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019857 seconds
  Subspace dimension: 311 x 311 = 96_721

 28%|██████████████████████████████████████████████████████▏                                                                                                                                           | 302/1080 [3:19:08<7:06:58, 32.93s/it]

  Operator projection took: 8.640330 seconds
  CSR matrix memory: 1.831760 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0175 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 8.6999 seconds

Running buta-1,3-diene_LUCJ_L2_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023489 seconds
  Subspace dimension: 343 x 343 = 117_649

 28%|██████████████████████████████████████████████████████▍                                                                                                                                           | 303/1080 [3:19:45<7:20:35, 34.02s/it]

  Operator projection took: 9.751825 seconds
  CSR matrix memory: 2.407764 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0202 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.8201 seconds

Running buta-1,3-diene_LUCJ_L2_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  379
  num selected half strs:  379
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029426 seconds
  Subspace dimension: 379 x 379 = 143_641

 28%|██████████████████████████████████████████████████████▌                                                                                                                                           | 304/1080 [3:20:24<7:40:03, 35.57s/it]

  Operator projection took: 12.295455 seconds
  CSR matrix memory: 2.868412 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0276 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 12.3813 seconds

Running buta-1,3-diene_LUCJ_L2_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  345
  num selected half strs:  345
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024446 seconds
  Subspace dimension: 345 x 345 = 119_025

 28%|██████████████████████████████████████████████████████▊                                                                                                                                           | 305/1080 [3:21:01<7:43:38, 35.90s/it]

  Operator projection took: 9.941971 seconds
  CSR matrix memory: 2.290012 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0219 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 10.0129 seconds

Running buta-1,3-diene_LUCJ_L2_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  238
  num selected half strs:  238
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010915 seconds
  Subspace dimension: 238 x 238 = 56_644

 28%|██████████████████████████████████████████████████████▉                                                                                                                                           | 306/1080 [3:21:31<7:22:51, 34.33s/it]

  Operator projection took: 3.866963 seconds
  CSR matrix memory: 19.183521 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0124 seconds
  Electronic Energy: [-259.0830795]
  Total Energy: [-154.93565576]
  num carryover full strs: 141
Iter 0 took: 3.9038 seconds

Running buta-1,3-diene_LUCJ_L3_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  341
  num selected half strs:  341
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023123 seconds
  Subspace dimension: 341 x 341 = 116_281

 28%|███████████████████████████████████████████████████████▏                                                                                                                                          | 307/1080 [3:22:19<8:15:10, 38.43s/it]

  Operator projection took: 11.978980 seconds
  CSR matrix memory: 2.164646 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0204 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 12.0487 seconds

Running buta-1,3-diene_LUCJ_L3_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  289
  num selected half strs:  289
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017407 seconds
  Subspace dimension: 289 x 289 = 83_521

 29%|███████████████████████████████████████████████████████▎                                                                                                                                          | 308/1080 [3:23:04<8:38:07, 40.27s/it]

  Operator projection took: 8.606262 seconds
  CSR matrix memory: 1.804386 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0152 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 8.6597 seconds

Running buta-1,3-diene_LUCJ_L3_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  335
  num selected half strs:  335
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023225 seconds
  Subspace dimension: 335 x 335 = 112_225

 29%|███████████████████████████████████████████████████████▌                                                                                                                                          | 309/1080 [3:23:51<9:05:37, 42.46s/it]

  Operator projection took: 11.302435 seconds
  CSR matrix memory: 2.187901 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0200 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 11.3698 seconds

Running buta-1,3-diene_LUCJ_L3_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  341
  num selected half strs:  341
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023641 seconds
  Subspace dimension: 341 x 341 = 116_281

 29%|███████████████████████████████████████████████████████▋                                                                                                                                          | 310/1080 [3:24:39<9:26:03, 44.11s/it]

  Operator projection took: 11.693296 seconds
  CSR matrix memory: 2.367664 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0234 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 11.7666 seconds

Running buta-1,3-diene_LUCJ_L3_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  357
  num selected half strs:  357
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025890 seconds
  Subspace dimension: 357 x 357 = 127_449

 29%|███████████████████████████████████████████████████████▊                                                                                                                                          | 311/1080 [3:25:28<9:44:24, 45.60s/it]

  Operator projection took: 12.940711 seconds
  CSR matrix memory: 2.533131 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0248 seconds
  Electronic Energy: [-257.16396633]
  Total Energy: [-153.01654259]
  num carryover full strs: 3
Iter 0 took: 13.0180 seconds

Running buta-1,3-diene_LUCJ_L3_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  203
  num selected half strs:  203
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.008004 seconds
  Subspace dimension: 203 x 203 = 41_209

 29%|████████████████████████████████████████████████████████                                                                                                                                          | 312/1080 [3:26:08<9:20:29, 43.79s/it]

  Operator projection took: 3.597195 seconds
  CSR matrix memory: 10.721668 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0104 seconds
  Electronic Energy: [-257.17200845]
  Total Energy: [-153.0245847]
  num carryover full strs: 168
Iter 0 took: 3.6270 seconds

Running buta-1,3-diene_LUCJ_L3_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  341
  num selected half strs:  341
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023470 seconds
  Subspace dimension: 341 x 341 = 116_281

 29%|████████████████████████████████████████████████████████▏                                                                                                                                         | 313/1080 [3:26:38<8:27:56, 39.73s/it]

  Operator projection took: 7.730532 seconds
  CSR matrix memory: 2.211613 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0204 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.7990 seconds

Running buta-1,3-diene_LUCJ_L3_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  333
  num selected half strs:  333
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022724 seconds
  Subspace dimension: 333 x 333 = 110_889

 29%|████████████████████████████████████████████████████████▍                                                                                                                                         | 314/1080 [3:27:08<7:49:18, 36.76s/it]

  Operator projection took: 7.152952 seconds
  CSR matrix memory: 2.301823 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0202 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.2191 seconds

Running buta-1,3-diene_LUCJ_L3_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  345
  num selected half strs:  345
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023996 seconds
  Subspace dimension: 345 x 345 = 119_025

 29%|████████████████████████████████████████████████████████▌                                                                                                                                         | 315/1080 [3:27:39<7:24:25, 34.86s/it]

  Operator projection took: 7.746863 seconds
  CSR matrix memory: 2.258381 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0206 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.8169 seconds

Running buta-1,3-diene_LUCJ_L3_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  327
  num selected half strs:  327
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021289 seconds
  Subspace dimension: 327 x 327 = 106_929

 29%|████████████████████████████████████████████████████████▊                                                                                                                                         | 316/1080 [3:28:08<7:03:37, 33.27s/it]

  Operator projection took: 6.927156 seconds
  CSR matrix memory: 1.931171 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0191 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 6.9899 seconds

Running buta-1,3-diene_LUCJ_L3_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  327
  num selected half strs:  327
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021888 seconds
  Subspace dimension: 327 x 327 = 106_929

 29%|████████████████████████████████████████████████████████▉                                                                                                                                         | 317/1080 [3:28:38<6:49:12, 32.18s/it]

  Operator projection took: 6.939406 seconds
  CSR matrix memory: 1.945957 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0185 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.0024 seconds

Running buta-1,3-diene_LUCJ_L3_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  263
  num selected half strs:  263
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.013088 seconds
  Subspace dimension: 263 x 263 = 69_169

 29%|█████████████████████████████████████████████████████████                                                                                                                                         | 318/1080 [3:29:04<6:26:04, 30.40s/it]

  Operator projection took: 3.665141 seconds
  CSR matrix memory: 20.844746 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0176 seconds
  Electronic Energy: [-259.08799766]
  Total Energy: [-154.94057392]
  num carryover full strs: 99
Iter 0 took: 3.7121 seconds

Running buta-1,3-diene_LUCJ_L3_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  361
  num selected half strs:  361
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027861 seconds
  Subspace dimension: 361 x 361 = 130_321

 30%|█████████████████████████████████████████████████████████▎                                                                                                                                        | 319/1080 [3:29:42<6:54:17, 32.66s/it]

  Operator projection took: 11.051565 seconds
  CSR matrix memory: 2.649738 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0244 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 11.1310 seconds

Running buta-1,3-diene_LUCJ_L3_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  305
  num selected half strs:  305
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018959 seconds
  Subspace dimension: 305 x 305 = 93_025

 30%|█████████████████████████████████████████████████████████▍                                                                                                                                        | 320/1080 [3:30:17<7:01:25, 33.27s/it]

  Operator projection took: 7.990569 seconds
  CSR matrix memory: 1.698689 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0162 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 8.0454 seconds

Running buta-1,3-diene_LUCJ_L3_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  357
  num selected half strs:  357
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027567 seconds
  Subspace dimension: 357 x 357 = 127_449

 30%|█████████████████████████████████████████████████████████▋                                                                                                                                        | 321/1080 [3:30:54<7:16:33, 34.51s/it]

  Operator projection took: 10.585097 seconds
  CSR matrix memory: 2.582294 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0239 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 10.6622 seconds

Running buta-1,3-diene_LUCJ_L3_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  341
  num selected half strs:  341
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023955 seconds
  Subspace dimension: 341 x 341 = 116_281

 30%|█████████████████████████████████████████████████████████▊                                                                                                                                        | 322/1080 [3:31:31<7:24:06, 35.15s/it]

  Operator projection took: 9.631828 seconds
  CSR matrix memory: 2.133381 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0214 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.7029 seconds

Running buta-1,3-diene_LUCJ_L3_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  307
  num selected half strs:  307
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018881 seconds
  Subspace dimension: 307 x 307 = 94_249

 30%|██████████████████████████████████████████████████████████                                                                                                                                        | 323/1080 [3:32:06<7:23:23, 35.14s/it]

  Operator projection took: 8.182981 seconds
  CSR matrix memory: 1.845722 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0165 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 8.2389 seconds

Running buta-1,3-diene_LUCJ_L3_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  236
  num selected half strs:  236
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010559 seconds
  Subspace dimension: 236 x 236 = 55_696

 30%|██████████████████████████████████████████████████████████▏                                                                                                                                       | 324/1080 [3:32:37<7:06:19, 33.83s/it]

  Operator projection took: 3.877355 seconds
  CSR matrix memory: 21.285938 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0147 seconds
  Electronic Energy: [-259.08293891]
  Total Energy: [-154.93551517]
  num carryover full strs: 179
Iter 0 took: 3.9169 seconds

Running buta-1,3-diene_LUCJ_L4_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  393
  num selected half strs:  393
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.031151 seconds
  Subspace dimension: 393 x 393 = 154_449

 30%|██████████████████████████████████████████████████████████▍                                                                                                                                       | 325/1080 [3:33:29<8:17:05, 39.50s/it]

  Operator projection took: 16.592580 seconds
  CSR matrix memory: 3.328358 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0295 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 16.6834 seconds

Running buta-1,3-diene_LUCJ_L4_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  367
  num selected half strs:  367
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.033633 seconds
  Subspace dimension: 367 x 367 = 134_689

 30%|██████████████████████████████████████████████████████████▌                                                                                                                                       | 326/1080 [3:34:19<8:56:33, 42.70s/it]

  Operator projection took: 13.875731 seconds
  CSR matrix memory: 2.844837 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0242 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 13.9606 seconds

Running buta-1,3-diene_LUCJ_L4_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023536 seconds
  Subspace dimension: 343 x 343 = 117_649

 30%|██████████████████████████████████████████████████████████▋                                                                                                                                       | 327/1080 [3:35:07<9:15:47, 44.29s/it]

  Operator projection took: 11.851703 seconds
  CSR matrix memory: 2.548847 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0211 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 11.9216 seconds

Running buta-1,3-diene_LUCJ_L4_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023453 seconds
  Subspace dimension: 343 x 343 = 117_649

 30%|██████████████████████████████████████████████████████████▉                                                                                                                                       | 328/1080 [3:35:56<9:29:47, 45.46s/it]

  Operator projection took: 11.925921 seconds
  CSR matrix memory: 2.187763 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0223 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 11.9964 seconds

Running buta-1,3-diene_LUCJ_L4_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  313
  num selected half strs:  313
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.020076 seconds
  Subspace dimension: 313 x 313 = 97_969

 30%|███████████████████████████████████████████████████████████                                                                                                                                       | 329/1080 [3:36:42<9:32:17, 45.72s/it]

  Operator projection took: 10.190240 seconds
  CSR matrix memory: 1.910450 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0172 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 10.2486 seconds

Running buta-1,3-diene_LUCJ_L4_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  205
  num selected half strs:  205
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.007958 seconds
  Subspace dimension: 205 x 205 = 42_025

 31%|███████████████████████████████████████████████████████████▎                                                                                                                                      | 330/1080 [3:37:22<9:08:42, 43.90s/it]

  Operator projection took: 3.654301 seconds
  CSR matrix memory: 9.439518 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0100 seconds
  Electronic Energy: [-257.17659397]
  Total Energy: [-153.02917023]
  num carryover full strs: 84
Iter 0 took: 3.6838 seconds

Running buta-1,3-diene_LUCJ_L4_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  321
  num selected half strs:  321
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021323 seconds
  Subspace dimension: 321 x 321 = 103_041

 31%|███████████████████████████████████████████████████████████▍                                                                                                                                      | 331/1080 [3:37:51<8:14:22, 39.60s/it]

  Operator projection took: 7.134587 seconds
  CSR matrix memory: 1.983768 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0183 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.1969 seconds

Running buta-1,3-diene_LUCJ_L4_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  431
  num selected half strs:  431
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.038831 seconds
  Subspace dimension: 431 x 431 = 185_761

 31%|███████████████████████████████████████████████████████████▋                                                                                                                                      | 332/1080 [3:38:27<7:58:48, 38.41s/it]

  Operator projection took: 13.020311 seconds
  CSR matrix memory: 3.505344 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0388 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 13.1370 seconds

Running buta-1,3-diene_LUCJ_L4_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  359
  num selected half strs:  359
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.026528 seconds
  Subspace dimension: 359 x 359 = 128_881

 31%|███████████████████████████████████████████████████████████▊                                                                                                                                      | 333/1080 [3:38:58<7:30:52, 36.21s/it]

  Operator projection took: 8.561403 seconds
  CSR matrix memory: 2.525730 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0263 seconds
  Electronic Energy: [-259.08733741]
  Total Energy: [-154.93991367]
  num carryover full strs: 3
Iter 0 took: 8.6410 seconds

Running buta-1,3-diene_LUCJ_L4_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  385
  num selected half strs:  385
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.031554 seconds
  Subspace dimension: 385 x 385 = 148_225

 31%|███████████████████████████████████████████████████████████▉                                                                                                                                      | 334/1080 [3:39:30<7:16:27, 35.10s/it]

  Operator projection took: 9.956045 seconds
  CSR matrix memory: 2.808308 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0276 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 10.0462 seconds

Running buta-1,3-diene_LUCJ_L4_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  339
  num selected half strs:  339
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023166 seconds
  Subspace dimension: 339 x 339 = 114_921

 31%|████████████████████████████████████████████████████████████▏                                                                                                                                     | 335/1080 [3:40:00<6:57:11, 33.60s/it]

  Operator projection took: 7.614682 seconds
  CSR matrix memory: 2.094959 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0207 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 7.6838 seconds

Running buta-1,3-diene_LUCJ_L4_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  241
  num selected half strs:  241
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010953 seconds
  Subspace dimension: 241 x 241 = 58_081

 31%|████████████████████████████████████████████████████████████▎                                                                                                                                     | 336/1080 [3:40:26<6:26:36, 31.18s/it]

  Operator projection took: 3.037085 seconds
  CSR matrix memory: 21.281269 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0162 seconds
  Electronic Energy: [-259.09061155]
  Total Energy: [-154.94318781]
  num carryover full strs: 131
Iter 0 took: 3.0787 seconds

Running buta-1,3-diene_LUCJ_L4_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  383
  num selected half strs:  383
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.030527 seconds
  Subspace dimension: 383 x 383 = 146_689

 31%|████████████████████████████████████████████████████████████▌                                                                                                                                     | 337/1080 [3:41:05<6:56:07, 33.60s/it]

  Operator projection took: 12.400891 seconds
  CSR matrix memory: 3.132587 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0272 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 12.4891 seconds

Running buta-1,3-diene_LUCJ_L4_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  339
  num selected half strs:  339
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022773 seconds
  Subspace dimension: 339 x 339 = 114_921

 31%|████████████████████████████████████████████████████████████▋                                                                                                                                     | 338/1080 [3:41:42<7:06:48, 34.51s/it]

  Operator projection took: 9.413686 seconds
  CSR matrix memory: 2.110523 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0209 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.4823 seconds

Running buta-1,3-diene_LUCJ_L4_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  309
  num selected half strs:  309
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.019864 seconds
  Subspace dimension: 309 x 309 = 95_481

 31%|████████████████████████████████████████████████████████████▉                                                                                                                                     | 339/1080 [3:42:17<7:07:47, 34.64s/it]

  Operator projection took: 8.230139 seconds
  CSR matrix memory: 1.768162 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0159 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 8.2874 seconds

Running buta-1,3-diene_LUCJ_L4_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  343
  num selected half strs:  343
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024603 seconds
  Subspace dimension: 343 x 343 = 117_649

 31%|█████████████████████████████████████████████████████████████                                                                                                                                     | 340/1080 [3:42:53<7:13:32, 35.15s/it]

  Operator projection took: 9.767320 seconds
  CSR matrix memory: 2.250614 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0209 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.8374 seconds

Running buta-1,3-diene_LUCJ_L4_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  337
  num selected half strs:  337
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.022790 seconds
  Subspace dimension: 337 x 337 = 113_569

 32%|█████████████████████████████████████████████████████████████▎                                                                                                                                    | 341/1080 [3:43:29<7:16:33, 35.44s/it]

  Operator projection took: 9.270838 seconds
  CSR matrix memory: 2.195957 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0209 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.3377 seconds

Running buta-1,3-diene_LUCJ_L4_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  188
  num selected half strs:  188
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.006521 seconds
  Subspace dimension: 188 x 188 = 35_344

 32%|█████████████████████████████████████████████████████████████▍                                                                                                                                    | 342/1080 [3:43:59<6:53:00, 33.58s/it]

  Operator projection took: 2.553987 seconds
  CSR matrix memory: 9.168430 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0071 seconds
  Electronic Energy: [-259.08869596]
  Total Energy: [-154.94127221]
  num carryover full strs: 209
Iter 0 took: 2.5780 seconds

Running buta-1,3-diene_LUCJ_L5_STO-3G_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  379
  num selected half strs:  379
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029191 seconds
  Subspace dimension: 379 x 379 = 143_641

 32%|█████████████████████████████████████████████████████████████▌                                                                                                                                    | 343/1080 [3:44:49<7:55:01, 38.67s/it]

  Operator projection took: 14.568322 seconds
  CSR matrix memory: 3.059299 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0267 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 14.6525 seconds

Running buta-1,3-diene_LUCJ_L5_STO-3G_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  337
  num selected half strs:  337
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.023904 seconds
  Subspace dimension: 337 x 337 = 113_569

 32%|█████████████████████████████████████████████████████████████▊                                                                                                                                    | 344/1080 [3:45:36<8:25:28, 41.21s/it]

  Operator projection took: 11.306685 seconds
  CSR matrix memory: 2.257435 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0201 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 11.3752 seconds

Running buta-1,3-diene_LUCJ_L5_STO-3G_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  371
  num selected half strs:  371
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028429 seconds
  Subspace dimension: 371 x 371 = 137_641

 32%|█████████████████████████████████████████████████████████████▉                                                                                                                                    | 345/1080 [3:46:27<8:58:09, 43.93s/it]

  Operator projection took: 14.158610 seconds
  CSR matrix memory: 2.932590 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0263 seconds
  Electronic Energy: [-257.16396559]
  Total Energy: [-153.01654185]
  num carryover full strs: 1
Iter 0 took: 14.2416 seconds

Running buta-1,3-diene_LUCJ_L5_STO-3G_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  413
  num selected half strs:  413
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.035912 seconds
  Subspace dimension: 413 x 413 = 170_569

 32%|██████████████████████████████████████████████████████████████▏                                                                                                                                   | 346/1080 [3:47:20<9:32:53, 46.83s/it]

  Operator projection took: 17.624730 seconds
  CSR matrix memory: 3.321095 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0395 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 17.7348 seconds

Running buta-1,3-diene_LUCJ_L5_STO-3G_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  363
  num selected half strs:  363
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.027459 seconds
  Subspace dimension: 363 x 363 = 131_769

 32%|██████████████████████████████████████████████████████████████▎                                                                                                                                   | 347/1080 [3:48:10<9:41:56, 47.64s/it]

  Operator projection took: 13.309287 seconds
  CSR matrix memory: 2.675312 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0239 seconds
  Electronic Energy: [-257.16396549]
  Total Energy: [-153.01654175]
  num carryover full strs: 1
Iter 0 took: 13.3876 seconds

Running buta-1,3-diene_LUCJ_L5_STO-3G_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  234
  num selected half strs:  234
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010242 seconds
  Subspace dimension: 234 x 234 = 54_756

 32%|██████████████████████████████████████████████████████████████▌                                                                                                                                   | 348/1080 [3:48:50<9:15:25, 45.53s/it]

  Operator projection took: 4.569423 seconds
  CSR matrix memory: 13.170597 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0106 seconds
  Electronic Energy: [-257.16889861]
  Total Energy: [-153.02147487]
  num carryover full strs: 107
Iter 0 took: 4.6041 seconds

Running buta-1,3-diene_LUCJ_L5_aug-cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  445
  num selected half strs:  445
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.040186 seconds
  Subspace dimension: 445 x 445 = 198_025

 32%|██████████████████████████████████████████████████████████████▋                                                                                                                                   | 349/1080 [3:49:27<8:42:15, 42.87s/it]

  Operator projection took: 14.070501 seconds
  CSR matrix memory: 3.938343 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0445 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 14.1971 seconds

Running buta-1,3-diene_LUCJ_L5_aug-cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  367
  num selected half strs:  367
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028648 seconds
  Subspace dimension: 367 x 367 = 134_689

 32%|██████████████████████████████████████████████████████████████▊                                                                                                                                   | 350/1080 [3:49:58<7:59:32, 39.41s/it]

  Operator projection took: 9.006578 seconds
  CSR matrix memory: 2.710438 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0242 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 9.0862 seconds

Running buta-1,3-diene_LUCJ_L5_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  431
  num selected half strs:  431
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.039123 seconds
  Subspace dimension: 431 x 431 = 185_761

 32%|███████████████████████████████████████████████████████████████                                                                                                                                   | 351/1080 [3:50:34<7:44:19, 38.22s/it]

  Operator projection took: 12.773651 seconds
  CSR matrix memory: 3.860889 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0404 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 12.8895 seconds

Running buta-1,3-diene_LUCJ_L5_aug-cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  377
  num selected half strs:  377
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028683 seconds
  Subspace dimension: 377 x 377 = 142_129

 33%|███████████████████████████████████████████████████████████████▏                                                                                                                                  | 352/1080 [3:51:06<7:21:11, 36.36s/it]

  Operator projection took: 9.390631 seconds
  CSR matrix memory: 2.824558 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0257 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 9.4737 seconds

Running buta-1,3-diene_LUCJ_L5_aug-cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  395
  num selected half strs:  395
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.032546 seconds
  Subspace dimension: 395 x 395 = 156_025

 33%|███████████████████████████████████████████████████████████████▍                                                                                                                                  | 353/1080 [3:51:39<7:08:08, 35.33s/it]

  Operator projection took: 10.480069 seconds
  CSR matrix memory: 2.905170 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0311 seconds
  Electronic Energy: [-259.08733678]
  Total Energy: [-154.93991304]
  num carryover full strs: 1
Iter 0 took: 10.5742 seconds

Running buta-1,3-diene_LUCJ_L5_aug-cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  233
  num selected half strs:  233
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010302 seconds
  Subspace dimension: 233 x 233 = 54_289

 33%|███████████████████████████████████████████████████████████████▌                                                                                                                                  | 354/1080 [3:52:04<6:31:28, 32.35s/it]

  Operator projection took: 2.943128 seconds
  CSR matrix memory: 14.982761 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0135 seconds
  Electronic Energy: [-259.09071125]
  Total Energy: [-154.94328751]
  num carryover full strs: 121
Iter 0 took: 2.9803 seconds

Running buta-1,3-diene_LUCJ_L5_cc-pVDZ_CCSD
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  377
  num selected half strs:  377
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.028841 seconds
  Subspace dimension: 377 x 377 = 142_129

 33%|███████████████████████████████████████████████████████████████▊                                                                                                                                  | 355/1080 [3:52:43<6:53:57, 34.26s/it]

  Operator projection took: 11.879220 seconds
  CSR matrix memory: 2.738270 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0249 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 11.9631 seconds

Running buta-1,3-diene_LUCJ_L5_cc-pVDZ_ML
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  327
  num selected half strs:  327
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.021344 seconds
  Subspace dimension: 327 x 327 = 106_929

 33%|███████████████████████████████████████████████████████████████▉                                                                                                                                  | 356/1080 [3:53:18<6:58:36, 34.69s/it]

  Operator projection took: 8.938072 seconds
  CSR matrix memory: 2.111027 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0189 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.0001 seconds

Running buta-1,3-diene_LUCJ_L5_cc-pVDZ_ML_exact
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  357
  num selected half strs:  357
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.025618 seconds
  Subspace dimension: 357 x 357 = 127_449

 33%|████████████████████████████████████████████████████████████████▏                                                                                                                                 | 357/1080 [3:53:56<7:07:23, 35.47s/it]

  Operator projection took: 10.544501 seconds
  CSR matrix memory: 2.778355 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0236 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 10.6208 seconds

Running buta-1,3-diene_LUCJ_L5_cc-pVDZ_MP2
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  345
  num selected half strs:  345
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.024092 seconds
  Subspace dimension: 345 x 345 = 119_025

 33%|████████████████████████████████████████████████████████████████▎                                                                                                                                 | 358/1080 [3:54:32<7:10:51, 35.81s/it]

  Operator projection took: 9.890258 seconds
  CSR matrix memory: 2.353184 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0215 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 9.9627 seconds

Running buta-1,3-diene_LUCJ_L5_cc-pVDZ_random
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  373
  num selected half strs:  373
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.029245 seconds
  Subspace dimension: 373 x 373 = 139_129

 33%|████████████████████████████████████████████████████████████████▍                                                                                                                                 | 359/1080 [3:55:11<7:20:08, 36.63s/it]

  Operator projection took: 11.657768 seconds
  CSR matrix memory: 2.943165 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0273 seconds
  Electronic Energy: [-259.08134415]
  Total Energy: [-154.9339204]
  num carryover full strs: 1
Iter 0 took: 11.7411 seconds

Running buta-1,3-diene_LUCJ_L5_cc-pVDZ_zeroes
Active Space Orbitals: 26, Electrons: 30, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  244
  num selected half strs:  244
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011316 seconds
  Subspace dimension: 244 x 244 = 59_536

 33%|████████████████████████████████████████████████████████████████▋                                                                                                                                 | 360/1080 [3:55:42<6:58:24, 34.87s/it]

  Operator projection took: 4.051272 seconds
  CSR matrix memory: 23.635777 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0131 seconds
  Electronic Energy: [-259.08460853]
  Total Energy: [-154.93718478]
  num carryover full strs: 268
Iter 0 took: 4.0894 seconds

Running ethane_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  712
  num selected half strs:  712
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.106969 seconds
  Subspace dimension: 712 x 712 = 506_944
  Operator projection took: 10.119392 seconds
  CSR matrix memory: 1349.523121 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 33%|████████████████████████████████████████████████████████████████▊                                                                                                                                 | 361/1080 [3:55:54<5:38:31, 28.25s/it]

  Eigensolving took: 0.4887 seconds
  Electronic Energy: [-120.43024976]
  Total Energy: [-78.4320434]
  num carryover full strs: 5180
Iter 0 took: 10.7986 seconds

Running ethane_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  627
  num selected half strs:  627
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.075370 seconds
  Subspace dimension: 627 x 627 = 393_129
  Operator projection took: 7.837371 seconds
  CSR matrix memory: 1156.426945 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 34%|█████████████████████████████████████████████████████████████████                                                                                                                                 | 362/1080 [3:56:05<4:34:11, 22.91s/it]

  Eigensolving took: 0.4877 seconds
  Electronic Energy: [-120.43279105]
  Total Energy: [-78.4345847]
  num carryover full strs: 5641
Iter 0 took: 8.4677 seconds

Running ethane_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  705
  num selected half strs:  705
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.136065 seconds
  Subspace dimension: 705 x 705 = 497_025
  Operator projection took: 11.828601 seconds
  CSR matrix memory: 1513.647953 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 34%|█████████████████████████████████████████████████████████████████▏                                                                                                                                | 363/1080 [3:56:20<4:05:33, 20.55s/it]

  Eigensolving took: 0.5496 seconds
  Electronic Energy: [-120.42735702]
  Total Energy: [-78.42915067]
  num carryover full strs: 6051
Iter 0 took: 12.5922 seconds

Running ethane_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  652
  num selected half strs:  652
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.090462 seconds
  Subspace dimension: 652 x 652 = 425_104
  Operator projection took: 8.855589 seconds
  CSR matrix memory: 1010.392979 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 34%|█████████████████████████████████████████████████████████████████▍                                                                                                                                | 364/1080 [3:56:31<3:32:28, 17.81s/it]

  Eigensolving took: 0.3631 seconds
  Electronic Energy: [-120.42821615]
  Total Energy: [-78.4300098]
  num carryover full strs: 4766
Iter 0 took: 9.3841 seconds

Running ethane_LUCJ_L1_STO-3G_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  898
  num selected half strs:  898
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.189747 seconds
  Subspace dimension: 898 x 898 = 806_404
  Operator projection took: 20.510610 seconds
  CSR matrix memory: 1452.606968 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 34%|█████████████████████████████████████████████████████████████████▌                                                                                                                                | 365/1080 [3:56:55<3:52:18, 19.49s/it]

  Eigensolving took: 0.5357 seconds
  Electronic Energy: [-120.31296112]
  Total Energy: [-78.31475476]
  num carryover full strs: 169
Iter 0 took: 21.3712 seconds

Running ethane_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  516
  num selected half strs:  516
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.067212 seconds
  Subspace dimension: 516 x 516 = 266_256
  Operator projection took: 5.899785 seconds
  CSR matrix memory: 1090.979420 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 34%|█████████████████████████████████████████████████████████████████▋                                                                                                                                | 366/1080 [3:57:03<3:12:42, 16.19s/it]

  Eigensolving took: 0.3243 seconds
  Electronic Energy: [-120.42941585]
  Total Energy: [-78.43120949]
  num carryover full strs: 5739
Iter 0 took: 6.3400 seconds

Running ethane_LUCJ_L1_aug-cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  730
  num selected half strs:  730
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.145054 seconds
  Subspace dimension: 730 x 730 = 532_900
  Operator projection took: 11.071792 seconds
  CSR matrix memory: 1003.152943 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 34%|█████████████████████████████████████████████████████████████████▉                                                                                                                                | 367/1080 [3:57:18<3:06:22, 15.68s/it]

  Eigensolving took: 0.3525 seconds
  Electronic Energy: [-121.23526196]
  Total Energy: [-79.23705561]
  num carryover full strs: 195
Iter 0 took: 11.6551 seconds

Running ethane_LUCJ_L1_aug-cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  687
  num selected half strs:  687
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.107343 seconds
  Subspace dimension: 687 x 687 = 471_969
  Operator projection took: 8.958010 seconds
  CSR matrix memory: 836.006290 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 34%|██████████████████████████████████████████████████████████████████                                                                                                                                | 368/1080 [3:57:30<2:54:22, 14.69s/it]

  Eigensolving took: 0.3052 seconds
  Electronic Energy: [-121.23528657]
  Total Energy: [-79.23708022]
  num carryover full strs: 220
Iter 0 took: 9.4444 seconds

Running ethane_LUCJ_L1_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  728
  num selected half strs:  728
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.113697 seconds
  Subspace dimension: 728 x 728 = 529_984
  Operator projection took: 10.391605 seconds
  CSR matrix memory: 940.796192 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 34%|██████████████████████████████████████████████████████████████████▎                                                                                                                               | 369/1080 [3:57:44<2:50:43, 14.41s/it]

  Eigensolving took: 0.3263 seconds
  Electronic Energy: [-121.23528085]
  Total Energy: [-79.2370745]
  num carryover full strs: 229
Iter 0 took: 10.9212 seconds

Running ethane_LUCJ_L1_aug-cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  842
  num selected half strs:  842
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.165282 seconds
  Subspace dimension: 842 x 842 = 708_964
  Operator projection took: 15.295681 seconds
  CSR matrix memory: 1716.046757 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 34%|██████████████████████████████████████████████████████████████████▍                                                                                                                               | 370/1080 [3:58:03<3:06:44, 15.78s/it]

  Eigensolving took: 0.5673 seconds
  Electronic Energy: [-121.23526606]
  Total Energy: [-79.2370597]
  num carryover full strs: 203
Iter 0 took: 16.1402 seconds

Running ethane_LUCJ_L1_aug-cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  872
  num selected half strs:  872
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.175994 seconds
  Subspace dimension: 872 x 872 = 760_384
  Operator projection took: 17.001412 seconds
  CSR matrix memory: 1342.091190 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 34%|██████████████████████████████████████████████████████████████████▋                                                                                                                               | 371/1080 [3:58:23<3:23:31, 17.22s/it]

  Eigensolving took: 0.4727 seconds
  Electronic Energy: [-121.23518864]
  Total Energy: [-79.23698228]
  num carryover full strs: 13
Iter 0 took: 17.7642 seconds

Running ethane_LUCJ_L1_aug-cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  465
  num selected half strs:  465
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.041390 seconds
  Subspace dimension: 465 x 465 = 216_225
  Operator projection took: 4.521494 seconds
  CSR matrix memory: 997.863010 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 34%|██████████████████████████████████████████████████████████████████▊                                                                                                                               | 372/1080 [3:58:31<2:49:28, 14.36s/it]

  Eigensolving took: 0.2830 seconds
  Electronic Energy: [-121.23532221]
  Total Energy: [-79.23711585]
  num carryover full strs: 491
Iter 0 took: 4.8836 seconds

Running ethane_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  694
  num selected half strs:  694
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.100762 seconds
  Subspace dimension: 694 x 694 = 481_636
  Operator projection took: 9.688940 seconds
  CSR matrix memory: 1345.803562 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 35%|███████████████████████████████████████████████████████████████████                                                                                                                               | 373/1080 [3:58:44<2:43:55, 13.91s/it]

  Eigensolving took: 0.7631 seconds
  Electronic Energy: [-121.25582403]
  Total Energy: [-79.25761767]
  num carryover full strs: 2252
Iter 0 took: 10.6331 seconds

Running ethane_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  795
  num selected half strs:  795
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.137118 seconds
  Subspace dimension: 795 x 795 = 632_025
  Operator projection took: 13.428237 seconds
  CSR matrix memory: 1875.618580 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...

 35%|███████████████████████████████████████████████████████████████████▏                                                                                                                              | 374/1080 [3:59:01<2:54:00, 14.79s/it]

  Eigensolving took: 1.0163 seconds
  Electronic Energy: [-121.2541357]
  Total Energy: [-79.25592935]
  num carryover full strs: 2132
Iter 0 took: 14.6839 seconds

Running ethane_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  692
  num selected half strs:  692
  Half strs construction took: 0.0004 seconds
  Subspace construction took: 0.103856 seconds
  Subspace dimension: 692 x 692 = 478_864
  Operator projection took: 9.898249 seconds
  CSR matrix memory: 1491.521000 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 35%|███████████████████████████████████████████████████████████████████▎                                                                                                                              | 375/1080 [3:59:14<2:47:14, 14.23s/it]

  Eigensolving took: 0.7489 seconds
  Electronic Energy: [-121.25588535]
  Total Energy: [-79.25767899]
  num carryover full strs: 1973
Iter 0 took: 10.8302 seconds

Running ethane_LUCJ_L1_cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  637
  num selected half strs:  637
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.080516 seconds
  Subspace dimension: 637 x 637 = 405_769
  Operator projection took: 7.995654 seconds
  CSR matrix memory: 997.118702 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 35%|███████████████████████████████████████████████████████████████████▌                                                                                                                              | 376/1080 [3:59:24<2:34:27, 13.16s/it]

  Eigensolving took: 0.3784 seconds
  Electronic Energy: [-121.25618898]
  Total Energy: [-79.25798263]
  num carryover full strs: 2159
Iter 0 took: 8.5188 seconds

Running ethane_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  1009
  num selected half strs:  1000
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.253287 seconds
  Subspace dimension: 1000 x 1000 = 1_000_000
  Operator projection took: 22.022556 seconds
  CSR matrix memory: 2058.561283 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 35%|███████████████████████████████████████████████████████████████████▋                                                                                                                              | 377/1080 [3:59:50<3:16:48, 16.80s/it]

  Eigensolving took: 0.7069 seconds
  Electronic Energy: [-121.23387454]
  Total Energy: [-79.23566818]
  num carryover full strs: 63
Iter 0 took: 23.1421 seconds

Running ethane_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  481
  num selected half strs:  481
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.046950 seconds
  Subspace dimension: 481 x 481 = 231_361
  Operator projection took: 4.684527 seconds
  CSR matrix memory: 902.619068 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 35%|███████████████████████████████████████████████████████████████████▉                                                                                                                              | 378/1080 [3:59:57<2:43:07, 13.94s/it]

  Eigensolving took: 0.4008 seconds
  Electronic Energy: [-121.25520993]
  Total Energy: [-79.25700357]
  num carryover full strs: 2426
Iter 0 took: 5.1755 seconds

Running ethane_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  850
  num selected half strs:  850
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.170352 seconds
  Subspace dimension: 850 x 850 = 722_500
  Operator projection took: 15.665581 seconds
  CSR matrix memory: 1259.395405 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 35%|████████████████████████████████████████████████████████████████████                                                                                                                              | 379/1080 [4:00:15<2:58:43, 15.30s/it]

  Eigensolving took: 0.4603 seconds
  Electronic Energy: [-120.34230393]
  Total Energy: [-78.34409757]
  num carryover full strs: 426
Iter 0 took: 16.4028 seconds

Running ethane_LUCJ_L2_STO-3G_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  827
  num selected half strs:  827
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.154150 seconds
  Subspace dimension: 827 x 827 = 683_929
  Operator projection took: 14.481842 seconds
  CSR matrix memory: 1202.045582 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 35%|████████████████████████████████████████████████████████████████████▎                                                                                                                             | 380/1080 [4:00:33<3:05:10, 15.87s/it]

  Eigensolving took: 0.4464 seconds
  Electronic Energy: [-120.32460482]
  Total Energy: [-78.32639846]
  num carryover full strs: 616
Iter 0 took: 15.1895 seconds

Running ethane_LUCJ_L2_STO-3G_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  755
  num selected half strs:  755
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.127206 seconds
  Subspace dimension: 755 x 755 = 570_025
  Operator projection took: 11.323435 seconds
  CSR matrix memory: 895.371479 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 35%|████████████████████████████████████████████████████████████████████▍                                                                                                                             | 381/1080 [4:00:47<2:57:58, 15.28s/it]

  Eigensolving took: 0.3484 seconds
  Electronic Energy: [-120.3156396]
  Total Energy: [-78.31743325]
  num carryover full strs: 391
Iter 0 took: 11.8887 seconds

Running ethane_LUCJ_L2_STO-3G_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  743
  num selected half strs:  743
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.121655 seconds
  Subspace dimension: 743 x 743 = 552_049
  Operator projection took: 11.104968 seconds
  CSR matrix memory: 853.325199 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 35%|████████████████████████████████████████████████████████████████████▌                                                                                                                             | 382/1080 [4:01:00<2:52:02, 14.79s/it]

  Eigensolving took: 0.3355 seconds
  Electronic Energy: [-120.31322475]
  Total Energy: [-78.31501839]
  num carryover full strs: 224
Iter 0 took: 11.6464 seconds

Running ethane_LUCJ_L2_STO-3G_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  826
  num selected half strs:  826
  Half strs construction took: 0.0004 seconds
  Subspace construction took: 0.158421 seconds
  Subspace dimension: 826 x 826 = 682_276
  Operator projection took: 14.704524 seconds
  CSR matrix memory: 1106.523304 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 35%|████████████████████████████████████████████████████████████████████▊                                                                                                                             | 383/1080 [4:01:18<3:00:51, 15.57s/it]

  Eigensolving took: 0.4082 seconds
  Electronic Energy: [-120.30484357]
  Total Energy: [-78.30663722]
  num carryover full strs: 74
Iter 0 took: 15.3774 seconds

Running ethane_LUCJ_L2_STO-3G_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  485
  num selected half strs:  485
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.042229 seconds
  Subspace dimension: 485 x 485 = 235_225
  Operator projection took: 4.909861 seconds
  CSR matrix memory: 1004.938541 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 36%|████████████████████████████████████████████████████████████████████▉                                                                                                                             | 384/1080 [4:01:25<2:32:13, 13.12s/it]

  Eigensolving took: 0.2976 seconds
  Electronic Energy: [-120.43835754]
  Total Energy: [-78.44015118]
  num carryover full strs: 6370
Iter 0 took: 5.2892 seconds

Running ethane_LUCJ_L2_aug-cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  712
  num selected half strs:  712
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.111702 seconds
  Subspace dimension: 712 x 712 = 506_944
  Operator projection took: 9.811864 seconds
  CSR matrix memory: 706.721027 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 36%|█████████████████████████████████████████████████████████████████████▏                                                                                                                            | 385/1080 [4:01:38<2:31:47, 13.10s/it]

  Eigensolving took: 0.2660 seconds
  Electronic Energy: [-121.23519407]
  Total Energy: [-79.23698771]
  num carryover full strs: 26
Iter 0 took: 10.2725 seconds

Running ethane_LUCJ_L2_aug-cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  636
  num selected half strs:  636
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.083584 seconds
  Subspace dimension: 636 x 636 = 404_496
  Operator projection took: 8.024961 seconds
  CSR matrix memory: 491.689869 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1994 seconds
  Electronic Energy: [-121.23518808]
  Total Energy: [-79.23698172]

 36%|█████████████████████████████████████████████████████████████████████▎                                                                                                                            | 386/1080 [4:01:49<2:24:47, 12.52s/it]

  num carryover full strs: 17
Iter 0 took: 8.3734 seconds

Running ethane_LUCJ_L2_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  661
  num selected half strs:  661
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.092364 seconds
  Subspace dimension: 661 x 661 = 436_921
  Operator projection took: 8.210816 seconds
  CSR matrix memory: 576.161747 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 36%|█████████████████████████████████████████████████████████████████████▌                                                                                                                            | 387/1080 [4:02:01<2:20:44, 12.19s/it]

  Eigensolving took: 0.2383 seconds
  Electronic Energy: [-121.23518771]
  Total Energy: [-79.23698135]
  num carryover full strs: 12
Iter 0 took: 8.6153 seconds

Running ethane_LUCJ_L2_aug-cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  782
  num selected half strs:  782
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.139707 seconds
  Subspace dimension: 782 x 782 = 611_524
  Operator projection took: 12.447243 seconds
  CSR matrix memory: 1022.372929 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 36%|█████████████████████████████████████████████████████████████████████▋                                                                                                                            | 388/1080 [4:02:16<2:33:12, 13.28s/it]

  Eigensolving took: 0.3780 seconds
  Electronic Energy: [-121.23521442]
  Total Energy: [-79.23700806]
  num carryover full strs: 82
Iter 0 took: 13.0603 seconds

Running ethane_LUCJ_L2_aug-cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  716
  num selected half strs:  716
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.112823 seconds
  Subspace dimension: 716 x 716 = 512_656
  Operator projection took: 10.196988 seconds
  CSR matrix memory: 711.772083 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 36%|█████████████████████████████████████████████████████████████████████▉                                                                                                                            | 389/1080 [4:02:30<2:33:53, 13.36s/it]

  Eigensolving took: 0.2713 seconds
  Electronic Energy: [-121.23518654]
  Total Energy: [-79.23698019]
  num carryover full strs: 15
Iter 0 took: 10.6624 seconds

Running ethane_LUCJ_L2_aug-cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  418
  num selected half strs:  418
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.032678 seconds
  Subspace dimension: 418 x 418 = 174_724
  Operator projection took: 3.569618 seconds
  CSR matrix memory: 729.292484 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1997 seconds
  Electronic Energy: [-121.23531092]
  Total Energy: [-79.23710457]

 36%|██████████████████████████████████████████████████████████████████████                                                                                                                            | 390/1080 [4:02:37<2:10:21, 11.34s/it]

  num carryover full strs: 462
Iter 0 took: 3.8350 seconds

Running ethane_LUCJ_L2_cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  678
  num selected half strs:  678
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.102464 seconds
  Subspace dimension: 678 x 678 = 459_684
  Operator projection took: 8.685168 seconds
  CSR matrix memory: 676.042377 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 36%|██████████████████████████████████████████████████████████████████████▏                                                                                                                           | 391/1080 [4:02:48<2:10:08, 11.33s/it]

  Eigensolving took: 0.2979 seconds
  Electronic Energy: [-121.23911684]
  Total Energy: [-79.24091049]
  num carryover full strs: 279
Iter 0 took: 9.1588 seconds

Running ethane_LUCJ_L2_cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  746
  num selected half strs:  746
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.120372 seconds
  Subspace dimension: 746 x 746 = 556_516
  Operator projection took: 11.048840 seconds
  CSR matrix memory: 854.209003 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 36%|██████████████████████████████████████████████████████████████████████▍                                                                                                                           | 392/1080 [4:03:02<2:18:02, 12.04s/it]

  Eigensolving took: 0.3261 seconds
  Electronic Energy: [-121.23861168]
  Total Energy: [-79.24040533]
  num carryover full strs: 273
Iter 0 took: 11.5803 seconds

Running ethane_LUCJ_L2_cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  737
  num selected half strs:  737
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117947 seconds
  Subspace dimension: 737 x 737 = 543_169
  Operator projection took: 10.574664 seconds
  CSR matrix memory: 936.039845 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 36%|██████████████████████████████████████████████████████████████████████▌                                                                                                                           | 393/1080 [4:03:15<2:22:09, 12.42s/it]

  Eigensolving took: 0.3683 seconds
  Electronic Energy: [-121.24096358]
  Total Energy: [-79.24275723]
  num carryover full strs: 487
Iter 0 took: 11.1474 seconds

Running ethane_LUCJ_L2_cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  777
  num selected half strs:  777
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.131913 seconds
  Subspace dimension: 777 x 777 = 603_729
  Operator projection took: 12.299919 seconds
  CSR matrix memory: 1009.882282 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 36%|██████████████████████████████████████████████████████████████████████▊                                                                                                                           | 394/1080 [4:03:30<2:31:22, 13.24s/it]

  Eigensolving took: 0.3863 seconds
  Electronic Energy: [-121.24387917]
  Total Energy: [-79.24567282]
  num carryover full strs: 542
Iter 0 took: 12.9157 seconds

Running ethane_LUCJ_L2_cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  821
  num selected half strs:  821
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.151139 seconds
  Subspace dimension: 821 x 821 = 674_041
  Operator projection took: 14.556755 seconds
  CSR matrix memory: 1079.483158 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 37%|██████████████████████████████████████████████████████████████████████▉                                                                                                                           | 395/1080 [4:03:47<2:45:24, 14.49s/it]

  Eigensolving took: 0.4150 seconds
  Electronic Energy: [-121.23337276]
  Total Energy: [-79.2351664]
  num carryover full strs: 29
Iter 0 took: 15.2207 seconds

Running ethane_LUCJ_L2_cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  452
  num selected half strs:  452
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.036091 seconds
  Subspace dimension: 452 x 452 = 204_304
  Operator projection took: 4.247833 seconds
  CSR matrix memory: 883.329777 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 37%|███████████████████████████████████████████████████████████████████████▏                                                                                                                          | 396/1080 [4:03:54<2:18:18, 12.13s/it]

  Eigensolving took: 0.2696 seconds
  Electronic Energy: [-121.25434144]
  Total Energy: [-79.25613509]
  num carryover full strs: 2239
Iter 0 took: 4.5903 seconds

Running ethane_LUCJ_L3_STO-3G_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  626
  num selected half strs:  626
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.078608 seconds
  Subspace dimension: 626 x 626 = 391_876
  Operator projection took: 7.765072 seconds
  CSR matrix memory: 479.779240 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1973 seconds
  Electronic Energy: [-120.30748186]
  Total Energy: [-78.30927551]

 37%|███████████████████████████████████████████████████████████████████████▎                                                                                                                          | 397/1080 [4:04:04<2:11:05, 11.52s/it]

  num carryover full strs: 83
Iter 0 took: 8.1018 seconds

Running ethane_LUCJ_L3_STO-3G_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  761
  num selected half strs:  761
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.127429 seconds
  Subspace dimension: 761 x 761 = 579_121
  Operator projection took: 11.827393 seconds
  CSR matrix memory: 891.093540 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 37%|███████████████████████████████████████████████████████████████████████▍                                                                                                                          | 398/1080 [4:04:19<2:20:43, 12.38s/it]

  Eigensolving took: 0.3473 seconds
  Electronic Energy: [-120.31311238]
  Total Energy: [-78.31490602]
  num carryover full strs: 293
Iter 0 took: 12.3924 seconds

Running ethane_LUCJ_L3_STO-3G_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  645
  num selected half strs:  645
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.084854 seconds
  Subspace dimension: 645 x 645 = 416_025
  Operator projection took: 8.463057 seconds
  CSR matrix memory: 514.693089 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 37%|███████████████████████████████████████████████████████████████████████▋                                                                                                                          | 399/1080 [4:04:30<2:15:35, 11.95s/it]

  Eigensolving took: 0.2138 seconds
  Electronic Energy: [-120.30908503]
  Total Energy: [-78.31087868]
  num carryover full strs: 131
Iter 0 took: 8.8317 seconds

Running ethane_LUCJ_L3_STO-3G_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  663
  num selected half strs:  663
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.093065 seconds
  Subspace dimension: 663 x 663 = 439_569
  Operator projection took: 8.336416 seconds
  CSR matrix memory: 579.655979 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 37%|███████████████████████████████████████████████████████████████████████▊                                                                                                                          | 400/1080 [4:04:40<2:11:16, 11.58s/it]

  Eigensolving took: 0.2382 seconds
  Electronic Energy: [-120.31246842]
  Total Energy: [-78.31426207]
  num carryover full strs: 233
Iter 0 took: 8.7377 seconds

Running ethane_LUCJ_L3_STO-3G_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  741
  num selected half strs:  741
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.125012 seconds
  Subspace dimension: 741 x 741 = 549_081
  Operator projection took: 11.195960 seconds
  CSR matrix memory: 788.670368 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 37%|████████████████████████████████████████████████████████████████████████                                                                                                                          | 401/1080 [4:04:54<2:18:19, 12.22s/it]

  Eigensolving took: 0.3250 seconds
  Electronic Energy: [-120.30945609]
  Total Energy: [-78.31124974]
  num carryover full strs: 131
Iter 0 took: 11.7289 seconds

Running ethane_LUCJ_L3_STO-3G_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  483
  num selected half strs:  483
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.042398 seconds
  Subspace dimension: 483 x 483 = 233_289
  Operator projection took: 4.710277 seconds
  CSR matrix memory: 892.375629 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...

 37%|████████████████████████████████████████████████████████████████████████▏                                                                                                                         | 402/1080 [4:05:01<2:00:36, 10.67s/it]

  Eigensolving took: 0.2699 seconds
  Electronic Energy: [-120.43535092]
  Total Energy: [-78.43714457]
  num carryover full strs: 5391
Iter 0 took: 5.0633 seconds

Running ethane_LUCJ_L3_aug-cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  658
  num selected half strs:  658
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.092588 seconds
  Subspace dimension: 658 x 658 = 432_964
  Operator projection took: 8.091698 seconds
  CSR matrix memory: 550.445179 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 37%|████████████████████████████████████████████████████████████████████████▍                                                                                                                         | 403/1080 [4:05:12<2:02:25, 10.85s/it]

  Eigensolving took: 0.2212 seconds
  Electronic Energy: [-121.23519016]
  Total Energy: [-79.2369838]
  num carryover full strs: 15
Iter 0 took: 8.4725 seconds

Running ethane_LUCJ_L3_aug-cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  646
  num selected half strs:  646
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.084497 seconds
  Subspace dimension: 646 x 646 = 417_316
  Operator projection took: 8.382727 seconds
  CSR matrix memory: 517.014927 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 37%|████████████████████████████████████████████████████████████████████████▌                                                                                                                         | 404/1080 [4:05:24<2:05:06, 11.10s/it]

  Eigensolving took: 0.2145 seconds
  Electronic Energy: [-121.23518638]
  Total Energy: [-79.23698002]
  num carryover full strs: 12
Iter 0 took: 8.7493 seconds

Running ethane_LUCJ_L3_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  667
  num selected half strs:  667
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.096343 seconds
  Subspace dimension: 667 x 667 = 444_889
  Operator projection took: 8.338257 seconds
  CSR matrix memory: 556.114948 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...

 38%|████████████████████████████████████████████████████████████████████████▊                                                                                                                         | 405/1080 [4:05:36<2:06:17, 11.23s/it]

  Eigensolving took: 0.2333 seconds
  Electronic Energy: [-121.23518799]
  Total Energy: [-79.23698163]
  num carryover full strs: 11
Iter 0 took: 8.7370 seconds

Running ethane_LUCJ_L3_aug-cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  659
  num selected half strs:  659
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.096432 seconds
  Subspace dimension: 659 x 659 = 434_281
  Operator projection took: 8.212424 seconds
  CSR matrix memory: 539.191792 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 38%|████████████████████████████████████████████████████████████████████████▉                                                                                                                         | 406/1080 [4:05:47<2:06:40, 11.28s/it]

  Eigensolving took: 0.2272 seconds
  Electronic Energy: [-121.23518991]
  Total Energy: [-79.23698355]
  num carryover full strs: 9
Iter 0 took: 8.6056 seconds

Running ethane_LUCJ_L3_aug-cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  699
  num selected half strs:  699
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.108784 seconds
  Subspace dimension: 699 x 699 = 488_601
  Operator projection took: 9.409208 seconds
  CSR matrix memory: 654.272877 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 38%|█████████████████████████████████████████████████████████████████████████                                                                                                                         | 407/1080 [4:06:00<2:11:06, 11.69s/it]

  Eigensolving took: 0.2643 seconds
  Electronic Energy: [-121.23518705]
  Total Energy: [-79.2369807]
  num carryover full strs: 9
Iter 0 took: 9.8603 seconds

Running ethane_LUCJ_L3_aug-cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  465
  num selected half strs:  465
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.039059 seconds
  Subspace dimension: 465 x 465 = 216_225
  Operator projection took: 4.610491 seconds
  CSR matrix memory: 1014.612354 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 38%|█████████████████████████████████████████████████████████████████████████▎                                                                                                                        | 408/1080 [4:06:07<1:57:40, 10.51s/it]

  Eigensolving took: 0.2731 seconds
  Electronic Energy: [-121.23530467]
  Total Energy: [-79.23709831]
  num carryover full strs: 439
Iter 0 took: 4.9613 seconds

Running ethane_LUCJ_L3_cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  743
  num selected half strs:  743
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.118721 seconds
  Subspace dimension: 743 x 743 = 552_049
  Operator projection took: 11.397402 seconds
  CSR matrix memory: 808.653004 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 38%|█████████████████████████████████████████████████████████████████████████▍                                                                                                                        | 409/1080 [4:06:21<2:09:41, 11.60s/it]

  Eigensolving took: 0.3230 seconds
  Electronic Energy: [-121.23452338]
  Total Energy: [-79.23631703]
  num carryover full strs: 95
Iter 0 took: 11.9252 seconds

Running ethane_LUCJ_L3_cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  655
  num selected half strs:  655
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.096257 seconds
  Subspace dimension: 655 x 655 = 429_025
  Operator projection took: 8.086153 seconds
  CSR matrix memory: 540.007572 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 38%|█████████████████████████████████████████████████████████████████████████▋                                                                                                                        | 410/1080 [4:06:32<2:06:11, 11.30s/it]

  Eigensolving took: 0.2260 seconds
  Electronic Energy: [-121.23591096]
  Total Energy: [-79.2377046]
  num carryover full strs: 50
Iter 0 took: 8.4776 seconds

Running ethane_LUCJ_L3_cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  738
  num selected half strs:  738
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.121498 seconds
  Subspace dimension: 738 x 738 = 544_644
  Operator projection took: 10.904195 seconds
  CSR matrix memory: 797.587879 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 38%|█████████████████████████████████████████████████████████████████████████▊                                                                                                                        | 411/1080 [4:06:46<2:13:36, 11.98s/it]

  Eigensolving took: 0.3100 seconds
  Electronic Energy: [-121.23343913]
  Total Energy: [-79.23523278]
  num carryover full strs: 50
Iter 0 took: 11.4501 seconds

Running ethane_LUCJ_L3_cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  741
  num selected half strs:  741
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.119786 seconds
  Subspace dimension: 741 x 741 = 549_081
  Operator projection took: 11.056006 seconds
  CSR matrix memory: 820.619801 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 38%|██████████████████████████████████████████████████████████████████████████                                                                                                                        | 412/1080 [4:06:59<2:19:17, 12.51s/it]

  Eigensolving took: 0.3283 seconds
  Electronic Energy: [-121.2344749]
  Total Energy: [-79.23626854]
  num carryover full strs: 85
Iter 0 took: 11.5915 seconds

Running ethane_LUCJ_L3_cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  742
  num selected half strs:  742
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.125242 seconds
  Subspace dimension: 742 x 742 = 550_564
  Operator projection took: 11.172461 seconds
  CSR matrix memory: 786.084888 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 38%|██████████████████████████████████████████████████████████████████████████▏                                                                                                                       | 413/1080 [4:07:13<2:23:24, 12.90s/it]

  Eigensolving took: 0.3153 seconds
  Electronic Energy: [-121.23308367]
  Total Energy: [-79.23487731]
  num carryover full strs: 14
Iter 0 took: 11.7027 seconds

Running ethane_LUCJ_L3_cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  469
  num selected half strs:  469
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.040981 seconds
  Subspace dimension: 469 x 469 = 219_961
  Operator projection took: 4.535957 seconds
  CSR matrix memory: 880.760624 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 38%|██████████████████████████████████████████████████████████████████████████▎                                                                                                                       | 414/1080 [4:07:20<2:04:18, 11.20s/it]

  Eigensolving took: 0.3894 seconds
  Electronic Energy: [-121.25630884]
  Total Energy: [-79.25810249]
  num carryover full strs: 2465
Iter 0 took: 5.0086 seconds

Running ethane_LUCJ_L4_STO-3G_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  710
  num selected half strs:  710
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.109987 seconds
  Subspace dimension: 710 x 710 = 504_100
  Operator projection took: 9.885424 seconds
  CSR matrix memory: 678.727726 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 38%|██████████████████████████████████████████████████████████████████████████▌                                                                                                                       | 415/1080 [4:07:33<2:07:56, 11.54s/it]

  Eigensolving took: 0.2725 seconds
  Electronic Energy: [-120.3055254]
  Total Energy: [-78.30731905]
  num carryover full strs: 64
Iter 0 took: 10.3492 seconds

Running ethane_LUCJ_L4_STO-3G_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  693
  num selected half strs:  693
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.108835 seconds
  Subspace dimension: 693 x 693 = 480_249
  Operator projection took: 9.368147 seconds
  CSR matrix memory: 632.208347 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 39%|██████████████████████████████████████████████████████████████████████████▋                                                                                                                       | 416/1080 [4:07:45<2:08:50, 11.64s/it]

  Eigensolving took: 0.2645 seconds
  Electronic Energy: [-120.30687246]
  Total Energy: [-78.30866611]
  num carryover full strs: 73
Iter 0 took: 9.8199 seconds

Running ethane_LUCJ_L4_STO-3G_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  656
  num selected half strs:  656
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.094737 seconds
  Subspace dimension: 656 x 656 = 430_336
  Operator projection took: 8.393403 seconds
  CSR matrix memory: 542.885395 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 39%|██████████████████████████████████████████████████████████████████████████▉                                                                                                                       | 417/1080 [4:07:55<2:05:44, 11.38s/it]

  Eigensolving took: 0.2180 seconds
  Electronic Energy: [-120.30518933]
  Total Energy: [-78.30698298]
  num carryover full strs: 46
Iter 0 took: 8.7747 seconds

Running ethane_LUCJ_L4_STO-3G_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  746
  num selected half strs:  746
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.121496 seconds
  Subspace dimension: 746 x 746 = 556_516
  Operator projection took: 11.437039 seconds
  CSR matrix memory: 804.811588 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...

 39%|███████████████████████████████████████████████████████████████████████████                                                                                                                       | 418/1080 [4:08:09<2:14:12, 12.16s/it]

  Eigensolving took: 0.3249 seconds
  Electronic Energy: [-120.30710955]
  Total Energy: [-78.3089032]
  num carryover full strs: 81
Iter 0 took: 11.9729 seconds

Running ethane_LUCJ_L4_STO-3G_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  670
  num selected half strs:  670
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.106649 seconds
  Subspace dimension: 670 x 670 = 448_900
  Operator projection took: 8.599825 seconds
  CSR matrix memory: 583.654011 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 39%|███████████████████████████████████████████████████████████████████████████▎                                                                                                                      | 419/1080 [4:08:20<2:10:28, 11.84s/it]

  Eigensolving took: 0.2354 seconds
  Electronic Energy: [-120.30593612]
  Total Energy: [-78.30772976]
  num carryover full strs: 54
Iter 0 took: 9.0106 seconds

Running ethane_LUCJ_L4_STO-3G_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  478
  num selected half strs:  478
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.042256 seconds
  Subspace dimension: 478 x 478 = 228_484
  Operator projection took: 4.831498 seconds
  CSR matrix memory: 1001.801716 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 39%|███████████████████████████████████████████████████████████████████████████▍                                                                                                                      | 420/1080 [4:08:28<1:54:54, 10.45s/it]

  Eigensolving took: 0.2878 seconds
  Electronic Energy: [-120.43291337]
  Total Energy: [-78.43470701]
  num carryover full strs: 6104
Iter 0 took: 5.2050 seconds

Running ethane_LUCJ_L4_aug-cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  675
  num selected half strs:  675
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.096956 seconds
  Subspace dimension: 675 x 675 = 455_625
  Operator projection took: 8.548408 seconds
  CSR matrix memory: 579.280430 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 39%|███████████████████████████████████████████████████████████████████████████▌                                                                                                                      | 421/1080 [4:08:39<1:59:01, 10.84s/it]

  Eigensolving took: 0.2492 seconds
  Electronic Energy: [-121.23518861]
  Total Energy: [-79.23698226]
  num carryover full strs: 12
Iter 0 took: 8.9642 seconds

Running ethane_LUCJ_L4_aug-cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  648
  num selected half strs:  648
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.089093 seconds
  Subspace dimension: 648 x 648 = 419_904
  Operator projection took: 8.009212 seconds
  CSR matrix memory: 523.547840 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1975 seconds
  Electronic Energy: [-121.23518657]
  Total Energy: [-79.23698022]

 39%|███████████████████████████████████████████████████████████████████████████▊                                                                                                                      | 422/1080 [4:08:51<1:59:52, 10.93s/it]

  num carryover full strs: 11
Iter 0 took: 8.3658 seconds

Running ethane_LUCJ_L4_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  743
  num selected half strs:  743
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.125706 seconds
  Subspace dimension: 743 x 743 = 552_049
  Operator projection took: 11.009260 seconds
  CSR matrix memory: 791.557911 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 39%|███████████████████████████████████████████████████████████████████████████▉                                                                                                                      | 423/1080 [4:09:05<2:10:54, 11.96s/it]

  Eigensolving took: 0.3200 seconds
  Electronic Energy: [-121.23519185]
  Total Energy: [-79.23698549]
  num carryover full strs: 17
Iter 0 took: 11.5453 seconds

Running ethane_LUCJ_L4_aug-cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  645
  num selected half strs:  645
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.083501 seconds
  Subspace dimension: 645 x 645 = 416_025
  Operator projection took: 8.393993 seconds
  CSR matrix memory: 512.165592 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 39%|████████████████████████████████████████████████████████████████████████████▏                                                                                                                     | 424/1080 [4:09:17<2:09:38, 11.86s/it]

  Eigensolving took: 0.2154 seconds
  Electronic Energy: [-121.23518856]
  Total Energy: [-79.23698221]
  num carryover full strs: 9
Iter 0 took: 8.7634 seconds

Running ethane_LUCJ_L4_aug-cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  670
  num selected half strs:  670
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.095270 seconds
  Subspace dimension: 670 x 670 = 448_900
  Operator projection took: 8.551577 seconds
  CSR matrix memory: 574.780994 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 39%|████████████████████████████████████████████████████████████████████████████▎                                                                                                                     | 425/1080 [4:09:28<2:09:13, 11.84s/it]

  Eigensolving took: 0.2295 seconds
  Electronic Energy: [-121.23518808]
  Total Energy: [-79.23698172]
  num carryover full strs: 12
Iter 0 took: 8.9533 seconds

Running ethane_LUCJ_L4_aug-cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  482
  num selected half strs:  482
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.041657 seconds
  Subspace dimension: 482 x 482 = 232_324
  Operator projection took: 5.005341 seconds
  CSR matrix memory: 1137.531757 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 39%|████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 426/1080 [4:09:37<1:57:05, 10.74s/it]

  Eigensolving took: 0.3308 seconds
  Electronic Energy: [-121.23531389]
  Total Energy: [-79.23710754]
  num carryover full strs: 497
Iter 0 took: 5.4174 seconds

Running ethane_LUCJ_L4_cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  635
  num selected half strs:  635
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.082480 seconds
  Subspace dimension: 635 x 635 = 403_225
  Operator projection took: 8.155038 seconds
  CSR matrix memory: 497.564365 MBs
  Initial guess vector v0 construction took: 0.0011 seconds
  Starting eigensolving ...

 40%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                     | 427/1080 [4:09:47<1:56:32, 10.71s/it]

  Eigensolving took: 0.2060 seconds
  Electronic Energy: [-121.23347443]
  Total Energy: [-79.23526808]
  num carryover full strs: 26
Iter 0 took: 8.5104 seconds

Running ethane_LUCJ_L4_cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  655
  num selected half strs:  655
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.093207 seconds
  Subspace dimension: 655 x 655 = 429_025
  Operator projection took: 8.321971 seconds
  CSR matrix memory: 541.840229 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 40%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                     | 428/1080 [4:09:58<1:56:43, 10.74s/it]

  Eigensolving took: 0.2277 seconds
  Electronic Energy: [-121.23291732]
  Total Energy: [-79.23471096]
  num carryover full strs: 22
Iter 0 took: 8.7110 seconds

Running ethane_LUCJ_L4_cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  690
  num selected half strs:  690
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.107129 seconds
  Subspace dimension: 690 x 690 = 476_100
  Operator projection took: 9.328499 seconds
  CSR matrix memory: 630.173908 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 40%|█████████████████████████████████████████████████████████████████████████████                                                                                                                     | 429/1080 [4:10:10<2:00:21, 11.09s/it]

  Eigensolving took: 0.2553 seconds
  Electronic Energy: [-121.23589615]
  Total Energy: [-79.23768979]
  num carryover full strs: 46
Iter 0 took: 9.7661 seconds

Running ethane_LUCJ_L4_cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  676
  num selected half strs:  676
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.102126 seconds
  Subspace dimension: 676 x 676 = 456_976
  Operator projection took: 8.882605 seconds
  CSR matrix memory: 599.639622 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 40%|█████████████████████████████████████████████████████████████████████████████▏                                                                                                                    | 430/1080 [4:10:21<2:01:25, 11.21s/it]

  Eigensolving took: 0.2327 seconds
  Electronic Energy: [-121.23317748]
  Total Energy: [-79.23497112]
  num carryover full strs: 31
Iter 0 took: 9.2907 seconds

Running ethane_LUCJ_L4_cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  684
  num selected half strs:  684
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.101038 seconds
  Subspace dimension: 684 x 684 = 467_856
  Operator projection took: 9.164386 seconds
  CSR matrix memory: 611.027393 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...

 40%|█████████████████████████████████████████████████████████████████████████████▍                                                                                                                    | 431/1080 [4:10:33<2:02:55, 11.36s/it]

  Eigensolving took: 0.2335 seconds
  Electronic Energy: [-121.23327436]
  Total Energy: [-79.235068]
  num carryover full strs: 23
Iter 0 took: 9.5724 seconds

Running ethane_LUCJ_L4_cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  462
  num selected half strs:  462
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.039513 seconds
  Subspace dimension: 462 x 462 = 213_444
  Operator projection took: 4.314642 seconds
  CSR matrix memory: 847.802540 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...

 40%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                                    | 432/1080 [4:10:40<1:47:50,  9.98s/it]

  Eigensolving took: 0.2626 seconds
  Electronic Energy: [-121.25317455]
  Total Energy: [-79.2549682]
  num carryover full strs: 2157
Iter 0 took: 4.6524 seconds

Running ethane_LUCJ_L5_STO-3G_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  684
  num selected half strs:  684
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.102668 seconds
  Subspace dimension: 684 x 684 = 467_856
  Operator projection took: 9.151787 seconds
  CSR matrix memory: 621.799122 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 40%|█████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 433/1080 [4:10:51<1:52:46, 10.46s/it]

  Eigensolving took: 0.2389 seconds
  Electronic Energy: [-120.30565966]
  Total Energy: [-78.30745331]
  num carryover full strs: 76
Iter 0 took: 9.5671 seconds

Running ethane_LUCJ_L5_STO-3G_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  707
  num selected half strs:  707
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.109530 seconds
  Subspace dimension: 707 x 707 = 499_849
  Operator projection took: 9.822486 seconds
  CSR matrix memory: 674.829044 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...

 40%|█████████████████████████████████████████████████████████████████████████████▉                                                                                                                    | 434/1080 [4:11:04<1:58:25, 11.00s/it]

  Eigensolving took: 0.2713 seconds
  Electronic Energy: [-120.31484132]
  Total Energy: [-78.31663497]
  num carryover full strs: 89
Iter 0 took: 10.2798 seconds

Running ethane_LUCJ_L5_STO-3G_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  721
  num selected half strs:  721
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.112420 seconds
  Subspace dimension: 721 x 721 = 519_841
  Operator projection took: 10.373569 seconds
  CSR matrix memory: 731.597416 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 40%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                                   | 435/1080 [4:11:17<2:04:29, 11.58s/it]

  Eigensolving took: 0.2984 seconds
  Electronic Energy: [-120.31045368]
  Total Energy: [-78.31224732]
  num carryover full strs: 103
Iter 0 took: 10.8716 seconds

Running ethane_LUCJ_L5_STO-3G_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  689
  num selected half strs:  689
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.107107 seconds
  Subspace dimension: 689 x 689 = 474_721
  Operator projection took: 9.329772 seconds
  CSR matrix memory: 624.715504 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 40%|██████████████████████████████████████████████████████████████████████████████▎                                                                                                                   | 436/1080 [4:11:28<2:04:56, 11.64s/it]

  Eigensolving took: 0.2579 seconds
  Electronic Energy: [-120.30445853]
  Total Energy: [-78.30625218]
  num carryover full strs: 44
Iter 0 took: 9.7750 seconds

Running ethane_LUCJ_L5_STO-3G_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  696
  num selected half strs:  696
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.103900 seconds
  Subspace dimension: 696 x 696 = 484_416
  Operator projection took: 9.530868 seconds
  CSR matrix memory: 665.990620 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 40%|██████████████████████████████████████████████████████████████████████████████▍                                                                                                                   | 437/1080 [4:11:40<2:05:44, 11.73s/it]

  Eigensolving took: 0.2463 seconds
  Electronic Energy: [-120.30572384]
  Total Energy: [-78.30751748]
  num carryover full strs: 51
Iter 0 took: 9.9558 seconds

Running ethane_LUCJ_L5_STO-3G_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  502
  num selected half strs:  502
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.051810 seconds
  Subspace dimension: 502 x 502 = 252_004
  Operator projection took: 5.242974 seconds
  CSR matrix memory: 1020.940311 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 41%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                                   | 438/1080 [4:11:48<1:52:15, 10.49s/it]

  Eigensolving took: 0.2931 seconds
  Electronic Energy: [-120.43314068]
  Total Energy: [-78.43493433]
  num carryover full strs: 5228
Iter 0 took: 5.6310 seconds

Running ethane_LUCJ_L5_aug-cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  680
  num selected half strs:  680
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.104008 seconds
  Subspace dimension: 680 x 680 = 462_400
  Operator projection took: 8.722706 seconds
  CSR matrix memory: 593.215092 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 41%|██████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 439/1080 [4:12:00<1:56:47, 10.93s/it]

  Eigensolving took: 0.2287 seconds
  Electronic Energy: [-121.23520021]
  Total Energy: [-79.23699386]
  num carryover full strs: 32
Iter 0 took: 9.1322 seconds

Running ethane_LUCJ_L5_aug-cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  702
  num selected half strs:  702
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.106715 seconds
  Subspace dimension: 702 x 702 = 492_804
  Operator projection took: 9.593020 seconds
  CSR matrix memory: 668.151127 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 41%|███████████████████████████████████████████████████████████████████████████████                                                                                                                   | 440/1080 [4:12:13<2:02:58, 11.53s/it]

  Eigensolving took: 0.2641 seconds
  Electronic Energy: [-121.2351862]
  Total Energy: [-79.23697985]
  num carryover full strs: 11
Iter 0 took: 10.0429 seconds

Running ethane_LUCJ_L5_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  674
  num selected half strs:  674
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117949 seconds
  Subspace dimension: 674 x 674 = 454_276
  Operator projection took: 8.752774 seconds
  CSR matrix memory: 585.127735 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 41%|███████████████████████████████████████████████████████████████████████████████▏                                                                                                                  | 441/1080 [4:12:25<2:04:17, 11.67s/it]

  Eigensolving took: 0.2452 seconds
  Electronic Energy: [-121.23518674]
  Total Energy: [-79.23698039]
  num carryover full strs: 14
Iter 0 took: 9.1891 seconds

Running ethane_LUCJ_L5_aug-cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  719
  num selected half strs:  719
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.115143 seconds
  Subspace dimension: 719 x 719 = 516_961
  Operator projection took: 10.184386 seconds
  CSR matrix memory: 721.313023 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 41%|███████████████████████████████████████████████████████████████████████████████▍                                                                                                                  | 442/1080 [4:12:38<2:09:49, 12.21s/it]

  Eigensolving took: 0.2898 seconds
  Electronic Energy: [-121.23518831]
  Total Energy: [-79.23698196]
  num carryover full strs: 8
Iter 0 took: 10.6666 seconds

Running ethane_LUCJ_L5_aug-cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  749
  num selected half strs:  749
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.122165 seconds
  Subspace dimension: 749 x 749 = 561_001
  Operator projection took: 11.290420 seconds
  CSR matrix memory: 805.721165 MBs
  Initial guess vector v0 construction took: 0.0011 seconds
  Starting eigensolving ...

 41%|███████████████████████████████████████████████████████████████████████████████▌                                                                                                                  | 443/1080 [4:12:53<2:17:19, 12.93s/it]

  Eigensolving took: 0.3208 seconds
  Electronic Energy: [-121.23518772]
  Total Energy: [-79.23698137]
  num carryover full strs: 17
Iter 0 took: 11.8252 seconds

Running ethane_LUCJ_L5_aug-cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  437
  num selected half strs:  437
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.033027 seconds
  Subspace dimension: 437 x 437 = 190_969
  Operator projection took: 4.037104 seconds
  CSR matrix memory: 883.304691 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 41%|███████████████████████████████████████████████████████████████████████████████▊                                                                                                                  | 444/1080 [4:13:00<1:58:52, 11.21s/it]

  Eigensolving took: 0.2474 seconds
  Electronic Energy: [-121.23532434]
  Total Energy: [-79.23711798]
  num carryover full strs: 507
Iter 0 took: 4.3488 seconds

Running ethane_LUCJ_L5_cc-pVDZ_CCSD
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  720
  num selected half strs:  720
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.113847 seconds
  Subspace dimension: 720 x 720 = 518_400
  Operator projection took: 10.431952 seconds
  CSR matrix memory: 721.031940 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 41%|███████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 445/1080 [4:13:13<2:04:37, 11.78s/it]

  Eigensolving took: 0.2655 seconds
  Electronic Energy: [-121.23357749]
  Total Energy: [-79.23537114]
  num carryover full strs: 32
Iter 0 took: 10.8885 seconds

Running ethane_LUCJ_L5_cc-pVDZ_ML
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  693
  num selected half strs:  693
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.104454 seconds
  Subspace dimension: 693 x 693 = 480_249
  Operator projection took: 9.563900 seconds
  CSR matrix memory: 637.018024 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 41%|████████████████████████████████████████████████████████████████████████████████                                                                                                                  | 446/1080 [4:13:25<2:05:29, 11.88s/it]

  Eigensolving took: 0.2627 seconds
  Electronic Energy: [-121.23347379]
  Total Energy: [-79.23526743]
  num carryover full strs: 41
Iter 0 took: 10.0082 seconds

Running ethane_LUCJ_L5_cc-pVDZ_ML_exact
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  630
  num selected half strs:  630
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.081350 seconds
  Subspace dimension: 630 x 630 = 396_900
  Operator projection took: 8.012756 seconds
  CSR matrix memory: 476.482777 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1989 seconds
  Electronic Energy: [-121.23319814]
  Total Energy: [-79.23499178]

 41%|████████████████████████████████████████████████████████████████████████████████▎                                                                                                                 | 447/1080 [4:13:36<2:00:51, 11.46s/it]

  num carryover full strs: 28
Iter 0 took: 8.3598 seconds

Running ethane_LUCJ_L5_cc-pVDZ_MP2
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  664
  num selected half strs:  664
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.100018 seconds
  Subspace dimension: 664 x 664 = 440_896
  Operator projection took: 8.574498 seconds
  CSR matrix memory: 565.248020 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 41%|████████████████████████████████████████████████████████████████████████████████▍                                                                                                                 | 448/1080 [4:13:47<1:59:34, 11.35s/it]

  Eigensolving took: 0.2154 seconds
  Electronic Energy: [-121.23298953]
  Total Energy: [-79.23478317]
  num carryover full strs: 26
Iter 0 took: 8.9609 seconds

Running ethane_LUCJ_L5_cc-pVDZ_random
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  602
  num selected half strs:  602
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.072347 seconds
  Subspace dimension: 602 x 602 = 362_404
  Operator projection took: 7.132679 seconds
  CSR matrix memory: 423.663410 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1784 seconds
  Electronic Energy: [-121.23303727]
  Total Energy: [-79.23483091]

 42%|████████████████████████████████████████████████████████████████████████████████▋                                                                                                                 | 449/1080 [4:13:56<1:53:37, 10.80s/it]

  num carryover full strs: 14
Iter 0 took: 7.4423 seconds

Running ethane_LUCJ_L5_cc-pVDZ_zeroes
Active Space Orbitals: 16, Electrons: 18, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  493
  num selected half strs:  493
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.043046 seconds
  Subspace dimension: 493 x 493 = 243_049
  Operator projection took: 5.059737 seconds
  CSR matrix memory: 1024.798893 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 42%|████████████████████████████████████████████████████████████████████████████████▊                                                                                                                 | 450/1080 [4:14:04<1:43:31,  9.86s/it]

  Eigensolving took: 0.2994 seconds
  Electronic Energy: [-121.25629871]
  Total Energy: [-79.25809236]
  num carryover full strs: 2369
Iter 0 took: 5.4463 seconds

Running ethylene_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  656
  num selected half strs:  656
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.092681 seconds
  Subspace dimension: 656 x 656 = 430_336
  Operator projection took: 8.357167 seconds
  CSR matrix memory: 2860.119755 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 42%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                 | 451/1080 [4:14:15<1:46:18, 10.14s/it]

  Eigensolving took: 1.2865 seconds
  Electronic Energy: [-110.44729673]
  Total Energy: [-77.22947733]
  num carryover full strs: 5542
Iter 0 took: 9.8003 seconds

Running ethylene_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  679
  num selected half strs:  679
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.103376 seconds
  Subspace dimension: 679 x 679 = 461_041
  Operator projection took: 8.908591 seconds
  CSR matrix memory: 3034.750278 MBs
  Initial guess vector v0 construction took: 0.0010 seconds
  Starting eigensolving ...

 42%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                                                | 452/1080 [4:14:26<1:50:09, 10.53s/it]

  Eigensolving took: 1.3884 seconds
  Electronic Energy: [-110.44331268]
  Total Energy: [-77.22549327]
  num carryover full strs: 5619
Iter 0 took: 10.4668 seconds

Running ethylene_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  734
  num selected half strs:  734
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.120666 seconds
  Subspace dimension: 734 x 734 = 538_756
  Operator projection took: 10.479759 seconds
  CSR matrix memory: 3324.760731 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 42%|█████████████████████████████████████████████████████████████████████████████████▎                                                                                                                | 453/1080 [4:14:39<1:58:10, 11.31s/it]

  Eigensolving took: 1.5164 seconds
  Electronic Energy: [-110.43356424]
  Total Energy: [-77.21574484]
  num carryover full strs: 3887
Iter 0 took: 12.1899 seconds

Running ethylene_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  723
  num selected half strs:  723
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.111508 seconds
  Subspace dimension: 723 x 723 = 522_729
  Operator projection took: 11.269736 seconds
  CSR matrix memory: 3729.594868 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 42%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                                | 454/1080 [4:14:53<2:06:19, 12.11s/it]

  Eigensolving took: 1.5541 seconds
  Electronic Energy: [-110.43777916]
  Total Energy: [-77.21995975]
  num carryover full strs: 4581
Iter 0 took: 13.0086 seconds

Running ethylene_LUCJ_L1_STO-3G_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  983
  num selected half strs:  983
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.255160 seconds
  Subspace dimension: 983 x 983 = 966_289
  Operator projection took: 24.784010 seconds
  CSR matrix memory: 6306.124256 MBs
  Initial guess vector v0 construction took: 0.0013 seconds
  Starting eigensolving ...

 42%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                | 455/1080 [4:15:21<2:55:58, 16.89s/it]

  Eigensolving took: 1.9071 seconds
  Electronic Energy: [-110.34045421]
  Total Energy: [-77.12263481]
  num carryover full strs: 1398
Iter 0 took: 27.0888 seconds

Running ethylene_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  273
  num selected half strs:  273
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.013151 seconds
  Subspace dimension: 273 x 273 = 74_529

 42%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                                                | 456/1080 [4:15:24<2:09:38, 12.47s/it]

  Operator projection took: 1.036634 seconds
  CSR matrix memory: 388.639256 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1597 seconds
  Electronic Energy: [-110.43021779]
  Total Energy: [-77.21239839]
  num carryover full strs: 3177
Iter 0 took: 1.2237 seconds

Running ethylene_LUCJ_L1_aug-cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  689
  num selected half strs:  689
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.104647 seconds
  Subspace dimension: 689 x 689 = 474_721
  Operator projection took: 8.304469 seconds
  CSR matrix memory: 2686.754032 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 42%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                | 457/1080 [4:15:34<2:03:44, 11.92s/it]

  Eigensolving took: 0.8025 seconds
  Electronic Energy: [-111.26319209]
  Total Energy: [-78.04537268]
  num carryover full strs: 261
Iter 0 took: 9.2778 seconds

Running ethylene_LUCJ_L1_aug-cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  723
  num selected half strs:  723
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.116478 seconds
  Subspace dimension: 723 x 723 = 522_729
  Operator projection took: 9.974311 seconds
  CSR matrix memory: 3395.855076 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 42%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                                               | 458/1080 [4:15:47<2:05:24, 12.10s/it]

  Eigensolving took: 0.9370 seconds
  Electronic Energy: [-111.2632093]
  Total Energy: [-78.04538989]
  num carryover full strs: 250
Iter 0 took: 11.0974 seconds

Running ethylene_LUCJ_L1_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  687
  num selected half strs:  687
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.102602 seconds
  Subspace dimension: 687 x 687 = 471_969
  Operator projection took: 8.338196 seconds
  CSR matrix memory: 2657.576160 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 42%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                                               | 459/1080 [4:15:57<2:00:29, 11.64s/it]

  Eigensolving took: 0.7582 seconds
  Electronic Energy: [-111.26313118]
  Total Energy: [-78.04531177]
  num carryover full strs: 209
Iter 0 took: 9.2706 seconds

Running ethylene_LUCJ_L1_aug-cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  733
  num selected half strs:  733
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117333 seconds
  Subspace dimension: 733 x 733 = 537_289
  Operator projection took: 9.984221 seconds
  CSR matrix memory: 3252.325397 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 43%|██████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 460/1080 [4:16:10<2:02:37, 11.87s/it]

  Eigensolving took: 0.9131 seconds
  Electronic Energy: [-111.26320709]
  Total Energy: [-78.04538769]
  num carryover full strs: 274
Iter 0 took: 11.0830 seconds

Running ethylene_LUCJ_L1_aug-cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  984
  num selected half strs:  984
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.242610 seconds
  Subspace dimension: 984 x 984 = 968_256
  Operator projection took: 20.246271 seconds
  CSR matrix memory: 5931.499607 MBs
  Initial guess vector v0 construction took: 0.0012 seconds
  Starting eigensolving ...

 43%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                                               | 461/1080 [4:16:33<2:38:42, 15.38s/it]

  Eigensolving took: 1.6419 seconds
  Electronic Energy: [-111.26090172]
  Total Energy: [-78.04308232]
  num carryover full strs: 53
Iter 0 took: 22.2491 seconds

Running ethylene_LUCJ_L1_aug-cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  265
  num selected half strs:  265
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012544 seconds
  Subspace dimension: 265 x 265 = 70_225

 43%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 462/1080 [4:16:36<1:57:58, 11.45s/it]

  Operator projection took: 0.884536 seconds
  CSR matrix memory: 329.771503 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0981 seconds
  Electronic Energy: [-111.26318928]
  Total Energy: [-78.04536988]
  num carryover full strs: 243
Iter 0 took: 1.0100 seconds

Running ethylene_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  744
  num selected half strs:  744
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.122210 seconds
  Subspace dimension: 744 x 744 = 553_536
  Operator projection took: 11.197838 seconds
  CSR matrix memory: 3675.940571 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 43%|███████████████████████████████████████████████████████████████████████████████████▏                                                                                                              | 463/1080 [4:16:50<2:05:25, 12.20s/it]

  Eigensolving took: 1.5261 seconds
  Electronic Energy: [-111.29572564]
  Total Energy: [-78.07790623]
  num carryover full strs: 1808
Iter 0 took: 12.9233 seconds

Running ethylene_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  571
  num selected half strs:  571
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.061676 seconds
  Subspace dimension: 571 x 571 = 326_041
  Operator projection took: 5.444631 seconds
  CSR matrix memory: 1733.943211 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 43%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                              | 464/1080 [4:16:57<1:50:18, 10.74s/it]

  Eigensolving took: 0.8066 seconds
  Electronic Energy: [-111.29377783]
  Total Energy: [-78.07595843]
  num carryover full strs: 1873
Iter 0 took: 6.3584 seconds

Running ethylene_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  695
  num selected half strs:  695
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.103606 seconds
  Subspace dimension: 695 x 695 = 483_025
  Operator projection took: 9.124970 seconds
  CSR matrix memory: 3008.629093 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 43%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                                              | 465/1080 [4:17:09<1:52:55, 11.02s/it]

  Eigensolving took: 1.3545 seconds
  Electronic Energy: [-111.29400847]
  Total Energy: [-78.07618907]
  num carryover full strs: 1513
Iter 0 took: 10.6507 seconds

Running ethylene_LUCJ_L1_cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  643
  num selected half strs:  643
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.086584 seconds
  Subspace dimension: 643 x 643 = 413_449
  Operator projection took: 7.490889 seconds
  CSR matrix memory: 2341.872364 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 43%|███████████████████████████████████████████████████████████████████████████████████▋                                                                                                              | 466/1080 [4:17:18<1:48:46, 10.63s/it]

  Eigensolving took: 1.0669 seconds
  Electronic Energy: [-111.29506071]
  Total Energy: [-78.0772413]
  num carryover full strs: 1550
Iter 0 took: 8.7017 seconds

Running ethylene_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  1100
  num selected half strs:  1000
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.262591 seconds
  Subspace dimension: 1000 x 1000 = 1_000_000
  Operator projection took: 25.962465 seconds
  CSR matrix memory: 6846.679569 MBs
  Initial guess vector v0 construction took: 0.0013 seconds
  Starting eigensolving ...

 43%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 467/1080 [4:17:49<2:49:09, 16.56s/it]

  Eigensolving took: 2.9148 seconds
  Electronic Energy: [-111.27968968]
  Total Energy: [-78.06187027]
  num carryover full strs: 344
Iter 0 took: 29.2622 seconds

Running ethylene_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  309
  num selected half strs:  309
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016529 seconds
  Subspace dimension: 309 x 309 = 95_481
  Operator projection took: 1.333313 seconds
  CSR matrix memory: 461.112904 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1885 seconds
  Electronic Energy: [-111.29432691]
  Total Energy: [-78.0765075]
  num carryover full strs: 1179
Iter 0 took: 1.5556 seconds

 43%|████████████████████████████████████████████████████████████████████████████████████                                                                                                              | 468/1080 [4:17:51<2:06:00, 12.35s/it]

Running ethylene_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  738
  num selected half strs:  738
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.127792 seconds
  Subspace dimension: 738 x 738 = 544_644
  Operator projection took: 9.420149 seconds
  CSR matrix memory: 2522.116245 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 43%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                                             | 469/1080 [4:18:03<2:03:43, 12.15s/it]

  Eigensolving took: 1.0596 seconds
  Electronic Energy: [-110.38138441]
  Total Energy: [-77.16356501]
  num carryover full strs: 1453
Iter 0 took: 10.6845 seconds

Running ethylene_LUCJ_L2_STO-3G_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  708
  num selected half strs:  708
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.111251 seconds
  Subspace dimension: 708 x 708 = 501_264
  Operator projection took: 8.639482 seconds
  CSR matrix memory: 2427.132252 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 44%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                                             | 470/1080 [4:18:14<1:59:25, 11.75s/it]

  Eigensolving took: 1.0493 seconds
  Electronic Energy: [-110.41748009]
  Total Energy: [-77.19966069]
  num carryover full strs: 3193
Iter 0 took: 9.8694 seconds

Running ethylene_LUCJ_L2_STO-3G_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  756
  num selected half strs:  756
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.126435 seconds
  Subspace dimension: 756 x 756 = 571_536
  Operator projection took: 10.330028 seconds
  CSR matrix memory: 2893.888187 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 44%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                             | 471/1080 [4:18:26<2:02:13, 12.04s/it]

  Eigensolving took: 1.2349 seconds
  Electronic Energy: [-110.41245093]
  Total Energy: [-77.19463153]
  num carryover full strs: 2583
Iter 0 took: 11.7705 seconds

Running ethylene_LUCJ_L2_STO-3G_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  712
  num selected half strs:  712
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.108322 seconds
  Subspace dimension: 712 x 712 = 506_944
  Operator projection took: 8.643589 seconds
  CSR matrix memory: 2343.947224 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 44%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                                             | 472/1080 [4:18:37<1:58:12, 11.66s/it]

  Eigensolving took: 0.9615 seconds
  Electronic Energy: [-110.37728075]
  Total Energy: [-77.15946134]
  num carryover full strs: 1536
Iter 0 took: 9.7808 seconds

Running ethylene_LUCJ_L2_STO-3G_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  767
  num selected half strs:  767
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.134344 seconds
  Subspace dimension: 767 x 767 = 588_289
  Operator projection took: 10.467928 seconds
  CSR matrix memory: 2661.678242 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 44%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                                             | 473/1080 [4:18:50<2:00:11, 11.88s/it]

  Eigensolving took: 0.7576 seconds
  Electronic Energy: [-110.32043797]
  Total Energy: [-77.10261856]
  num carryover full strs: 754
Iter 0 took: 11.4408 seconds

Running ethylene_LUCJ_L2_STO-3G_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  274
  num selected half strs:  274
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.013539 seconds
  Subspace dimension: 274 x 274 = 75_076

 44%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                                            | 474/1080 [4:18:52<1:30:16,  8.94s/it]

  Operator projection took: 1.006442 seconds
  CSR matrix memory: 352.480015 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1457 seconds
  Electronic Energy: [-110.43651524]
  Total Energy: [-77.21869584]
  num carryover full strs: 2710
Iter 0 took: 1.1794 seconds

Running ethylene_LUCJ_L2_aug-cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  728
  num selected half strs:  728
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117314 seconds
  Subspace dimension: 728 x 728 = 529_984
  Operator projection took: 8.742886 seconds
  CSR matrix memory: 2359.088627 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 44%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                                            | 475/1080 [4:19:03<1:35:59,  9.52s/it]

  Eigensolving took: 0.6381 seconds
  Electronic Energy: [-111.26297515]
  Total Energy: [-78.04515575]
  num carryover full strs: 136
Iter 0 took: 9.5757 seconds

Running ethylene_LUCJ_L2_aug-cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  771
  num selected half strs:  771
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.136116 seconds
  Subspace dimension: 771 x 771 = 594_441
  Operator projection took: 10.992400 seconds
  CSR matrix memory: 2908.005894 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 44%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                                            | 476/1080 [4:19:16<1:47:44, 10.70s/it]

  Eigensolving took: 0.8346 seconds
  Electronic Energy: [-111.26278365]
  Total Energy: [-78.04496424]
  num carryover full strs: 138
Iter 0 took: 12.0497 seconds

Running ethylene_LUCJ_L2_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  850
  num selected half strs:  850
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.167700 seconds
  Subspace dimension: 850 x 850 = 722_500
  Operator projection took: 14.358809 seconds
  CSR matrix memory: 4071.754368 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 44%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                                            | 477/1080 [4:19:33<2:06:51, 12.62s/it]

  Eigensolving took: 1.1422 seconds
  Electronic Energy: [-111.26312759]
  Total Energy: [-78.04530818]
  num carryover full strs: 183
Iter 0 took: 15.7817 seconds

Running ethylene_LUCJ_L2_aug-cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  780
  num selected half strs:  780
  Half strs construction took: 0.0003 seconds
  Subspace construction took: 0.164958 seconds
  Subspace dimension: 780 x 780 = 608_400
  Operator projection took: 11.523519 seconds
  CSR matrix memory: 3224.609577 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 44%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                            | 478/1080 [4:19:47<2:11:11, 13.08s/it]

  Eigensolving took: 0.8686 seconds
  Electronic Energy: [-111.26286453]
  Total Energy: [-78.04504512]
  num carryover full strs: 169
Iter 0 took: 12.6493 seconds

Running ethylene_LUCJ_L2_aug-cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  792
  num selected half strs:  792
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.148605 seconds
  Subspace dimension: 792 x 792 = 627_264
  Operator projection took: 10.523454 seconds
  CSR matrix memory: 2727.026325 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...

 44%|██████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 479/1080 [4:20:00<2:10:06, 12.99s/it]

  Eigensolving took: 0.7170 seconds
  Electronic Energy: [-111.26092646]
  Total Energy: [-78.04310705]
  num carryover full strs: 38
Iter 0 took: 11.4740 seconds

Running ethylene_LUCJ_L2_aug-cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  254
  num selected half strs:  254
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.010896 seconds
  Subspace dimension: 254 x 254 = 64_516

 44%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                                           | 480/1080 [4:20:02<1:37:22,  9.74s/it]

  Operator projection took: 0.786903 seconds
  CSR matrix memory: 288.532490 MBs
  Initial guess vector v0 construction took: 0.0001 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0839 seconds
  Electronic Energy: [-111.26317152]
  Total Energy: [-78.04535211]
  num carryover full strs: 237
Iter 0 took: 0.8946 seconds

Running ethylene_LUCJ_L2_cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  762
  num selected half strs:  762
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.129320 seconds
  Subspace dimension: 762 x 762 = 580_644
  Operator projection took: 10.108579 seconds
  CSR matrix memory: 2631.139072 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 45%|██████████████████████████████████████████████████████████████████████████████████████▍                                                                                                           | 481/1080 [4:20:14<1:44:07, 10.43s/it]

  Eigensolving took: 0.7355 seconds
  Electronic Energy: [-111.2622011]
  Total Energy: [-78.04438169]
  num carryover full strs: 296
Iter 0 took: 11.0556 seconds

Running ethylene_LUCJ_L2_cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  723
  num selected half strs:  723
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117295 seconds
  Subspace dimension: 723 x 723 = 522_729
  Operator projection took: 8.892916 seconds
  CSR matrix memory: 2379.286472 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 45%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                                           | 482/1080 [4:20:25<1:46:05, 10.64s/it]

  Eigensolving took: 1.0619 seconds
  Electronic Energy: [-111.29203218]
  Total Energy: [-78.07421278]
  num carryover full strs: 835
Iter 0 took: 10.1462 seconds

Running ethylene_LUCJ_L2_cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  753
  num selected half strs:  753
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.127452 seconds
  Subspace dimension: 753 x 753 = 567_009
  Operator projection took: 10.016711 seconds
  CSR matrix memory: 2638.731998 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 45%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 483/1080 [4:20:37<1:49:50, 11.04s/it]

  Eigensolving took: 0.7339 seconds
  Electronic Energy: [-111.26260639]
  Total Energy: [-78.04478698]
  num carryover full strs: 340
Iter 0 took: 10.9650 seconds

Running ethylene_LUCJ_L2_cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  752
  num selected half strs:  752
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.126579 seconds
  Subspace dimension: 752 x 752 = 565_504
  Operator projection took: 9.808084 seconds
  CSR matrix memory: 2648.518040 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 45%|██████████████████████████████████████████████████████████████████████████████████████▉                                                                                                           | 484/1080 [4:20:49<1:52:39, 11.34s/it]

  Eigensolving took: 1.0264 seconds
  Electronic Energy: [-111.28282322]
  Total Energy: [-78.06500382]
  num carryover full strs: 427
Iter 0 took: 11.0388 seconds

Running ethylene_LUCJ_L2_cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  845
  num selected half strs:  845
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.169322 seconds
  Subspace dimension: 845 x 845 = 714_025
  Operator projection took: 13.601358 seconds
  CSR matrix memory: 3576.811634 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 45%|███████████████████████████████████████████████████████████████████████████████████████                                                                                                           | 485/1080 [4:21:05<2:06:18, 12.74s/it]

  Eigensolving took: 0.9845 seconds
  Electronic Energy: [-111.26332554]
  Total Energy: [-78.04550613]
  num carryover full strs: 144
Iter 0 took: 14.8532 seconds

Running ethylene_LUCJ_L2_cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  312
  num selected half strs:  312
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.016565 seconds
  Subspace dimension: 312 x 312 = 97_344
  Operator projection took: 1.377126 seconds
  CSR matrix memory: 517.697117 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...

 45%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                                          | 486/1080 [4:21:08<1:35:53,  9.69s/it]

  Eigensolving took: 0.2026 seconds
  Electronic Energy: [-111.29403664]
  Total Energy: [-78.07621723]
  num carryover full strs: 1314
Iter 0 took: 1.6145 seconds

Running ethylene_LUCJ_L3_STO-3G_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  722
  num selected half strs:  722
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117072 seconds
  Subspace dimension: 722 x 722 = 521_284
  Operator projection took: 8.688965 seconds
  CSR matrix memory: 2108.878300 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 45%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                                          | 487/1080 [4:21:18<1:37:53,  9.90s/it]

  Eigensolving took: 0.5961 seconds
  Electronic Energy: [-110.34277784]
  Total Energy: [-77.12495844]
  num carryover full strs: 280
Iter 0 took: 9.4747 seconds

Running ethylene_LUCJ_L3_STO-3G_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  589
  num selected half strs:  589
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.067725 seconds
  Subspace dimension: 589 x 589 = 346_921
  Operator projection took: 5.242473 seconds
  CSR matrix memory: 1089.455494 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 45%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                          | 488/1080 [4:21:25<1:28:26,  8.96s/it]

  Eigensolving took: 0.4910 seconds
  Electronic Energy: [-110.36537725]
  Total Energy: [-77.14755785]
  num carryover full strs: 358
Iter 0 took: 5.8511 seconds

Running ethylene_LUCJ_L3_STO-3G_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  680
  num selected half strs:  680
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.099077 seconds
  Subspace dimension: 680 x 680 = 462_400
  Operator projection took: 7.292778 seconds
  CSR matrix memory: 1800.619694 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 45%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                          | 489/1080 [4:21:34<1:28:02,  8.94s/it]

  Eigensolving took: 0.5037 seconds
  Electronic Energy: [-110.30629382]
  Total Energy: [-77.08847441]
  num carryover full strs: 503
Iter 0 took: 7.9587 seconds

Running ethylene_LUCJ_L3_STO-3G_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  615
  num selected half strs:  615
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.076053 seconds
  Subspace dimension: 615 x 615 = 378_225
  Operator projection took: 5.890091 seconds
  CSR matrix memory: 1284.671268 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 45%|████████████████████████████████████████████████████████████████████████████████████████                                                                                                          | 490/1080 [4:21:41<1:23:19,  8.47s/it]

  Eigensolving took: 0.3880 seconds
  Electronic Energy: [-110.32448527]
  Total Energy: [-77.10666586]
  num carryover full strs: 547
Iter 0 took: 6.4128 seconds

Running ethylene_LUCJ_L3_STO-3G_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  664
  num selected half strs:  664
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.093954 seconds
  Subspace dimension: 664 x 664 = 440_896
  Operator projection took: 7.021264 seconds
  CSR matrix memory: 1654.308079 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 45%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                         | 491/1080 [4:21:50<1:23:27,  8.50s/it]

  Eigensolving took: 0.4526 seconds
  Electronic Energy: [-110.31441866]
  Total Energy: [-77.09659925]
  num carryover full strs: 381
Iter 0 took: 7.6304 seconds

Running ethylene_LUCJ_L3_STO-3G_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  252
  num selected half strs:  252
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011275 seconds
  Subspace dimension: 252 x 252 = 63_504

 46%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                         | 492/1080 [4:21:52<1:03:49,  6.51s/it]

  Operator projection took: 0.838239 seconds
  CSR matrix memory: 300.860508 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1150 seconds
  Electronic Energy: [-110.43409527]
  Total Energy: [-77.21627587]
  num carryover full strs: 2645
Iter 0 took: 0.9772 seconds

Running ethylene_LUCJ_L3_aug-cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  733
  num selected half strs:  733
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.120613 seconds
  Subspace dimension: 733 x 733 = 537_289
  Operator projection took: 8.580447 seconds
  CSR matrix memory: 2224.606266 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 46%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                         | 493/1080 [4:22:03<1:15:58,  7.77s/it]

  Eigensolving took: 0.6316 seconds
  Electronic Energy: [-111.26147681]
  Total Energy: [-78.04365741]
  num carryover full strs: 151
Iter 0 took: 9.4021 seconds

Running ethylene_LUCJ_L3_aug-cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  743
  num selected half strs:  743
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.122989 seconds
  Subspace dimension: 743 x 743 = 552_049
  Operator projection took: 8.946938 seconds
  CSR matrix memory: 2334.404087 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 46%|████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                         | 494/1080 [4:22:14<1:25:57,  8.80s/it]

  Eigensolving took: 0.6713 seconds
  Electronic Energy: [-111.26267115]
  Total Energy: [-78.04485174]
  num carryover full strs: 82
Iter 0 took: 9.8099 seconds

Running ethylene_LUCJ_L3_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  658
  num selected half strs:  658
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.096702 seconds
  Subspace dimension: 658 x 658 = 432_964
  Operator projection took: 6.523179 seconds
  CSR matrix memory: 1576.108768 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 46%|████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                         | 495/1080 [4:22:22<1:24:48,  8.70s/it]

  Eigensolving took: 0.4609 seconds
  Electronic Energy: [-111.26141748]
  Total Energy: [-78.04359808]
  num carryover full strs: 132
Iter 0 took: 7.1488 seconds

Running ethylene_LUCJ_L3_aug-cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  744
  num selected half strs:  744
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.122567 seconds
  Subspace dimension: 744 x 744 = 553_536
  Operator projection took: 9.075620 seconds
  CSR matrix memory: 2448.543049 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 46%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                                         | 496/1080 [4:22:33<1:32:06,  9.46s/it]

  Eigensolving took: 0.6679 seconds
  Electronic Energy: [-111.26303604]
  Total Energy: [-78.04521664]
  num carryover full strs: 135
Iter 0 took: 9.9422 seconds

Running ethylene_LUCJ_L3_aug-cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  639
  num selected half strs:  639
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.084628 seconds
  Subspace dimension: 639 x 639 = 408_321
  Operator projection took: 6.126451 seconds
  CSR matrix memory: 1341.321354 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 46%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                        | 497/1080 [4:22:41<1:27:36,  9.02s/it]

  Eigensolving took: 0.4073 seconds
  Electronic Energy: [-111.26120797]
  Total Energy: [-78.04338856]
  num carryover full strs: 56
Iter 0 took: 6.6767 seconds

Running ethylene_LUCJ_L3_aug-cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  295
  num selected half strs:  295
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015330 seconds
  Subspace dimension: 295 x 295 = 87_025

 46%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                        | 498/1080 [4:22:44<1:08:46,  7.09s/it]

  Operator projection took: 1.178238 seconds
  CSR matrix memory: 468.050968 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1329 seconds
  Electronic Energy: [-111.2631619]
  Total Energy: [-78.0453425]
  num carryover full strs: 234
Iter 0 took: 1.3420 seconds

Running ethylene_LUCJ_L3_cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  697
  num selected half strs:  697
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.109330 seconds
  Subspace dimension: 697 x 697 = 485_809
  Operator projection took: 8.197503 seconds
  CSR matrix memory: 1946.036839 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 46%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 499/1080 [4:22:54<1:17:00,  7.95s/it]

  Eigensolving took: 0.5597 seconds
  Electronic Energy: [-111.26433291]
  Total Energy: [-78.0465135]
  num carryover full strs: 241
Iter 0 took: 8.9677 seconds

Running ethylene_LUCJ_L3_cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  648
  num selected half strs:  648
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.094119 seconds
  Subspace dimension: 648 x 648 = 419_904
  Operator projection took: 6.415095 seconds
  CSR matrix memory: 1518.681614 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 46%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                        | 500/1080 [4:23:02<1:17:01,  7.97s/it]

  Eigensolving took: 0.4362 seconds
  Electronic Energy: [-111.27939481]
  Total Energy: [-78.0615754]
  num carryover full strs: 186
Iter 0 took: 6.9980 seconds

Running ethylene_LUCJ_L3_cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  640
  num selected half strs:  640
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.081098 seconds
  Subspace dimension: 640 x 640 = 409_600
  Operator projection took: 6.485901 seconds
  CSR matrix memory: 1450.208561 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 46%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                        | 501/1080 [4:23:10<1:17:42,  8.05s/it]

  Eigensolving took: 0.6176 seconds
  Electronic Energy: [-111.28416819]
  Total Energy: [-78.06634878]
  num carryover full strs: 283
Iter 0 took: 7.2404 seconds

Running ethylene_LUCJ_L3_cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  637
  num selected half strs:  637
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.088447 seconds
  Subspace dimension: 637 x 637 = 405_769
  Operator projection took: 6.369287 seconds
  CSR matrix memory: 1399.673374 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 46%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                       | 502/1080 [4:23:18<1:18:09,  8.11s/it]

  Eigensolving took: 0.6232 seconds
  Electronic Energy: [-111.28379555]
  Total Energy: [-78.06597614]
  num carryover full strs: 320
Iter 0 took: 7.1412 seconds

Running ethylene_LUCJ_L3_cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  696
  num selected half strs:  696
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.110390 seconds
  Subspace dimension: 696 x 696 = 484_416
  Operator projection took: 7.829889 seconds
  CSR matrix memory: 1892.336246 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 47%|██████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 503/1080 [4:23:28<1:22:05,  8.54s/it]

  Eigensolving took: 0.5266 seconds
  Electronic Energy: [-111.26049548]
  Total Energy: [-78.04267607]
  num carryover full strs: 134
Iter 0 took: 8.5298 seconds

Running ethylene_LUCJ_L3_cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  325
  num selected half strs:  325
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.018502 seconds
  Subspace dimension: 325 x 325 = 105_625
  Operator projection took: 1.517676 seconds
  CSR matrix memory: 585.365955 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...

 47%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                       | 504/1080 [4:23:31<1:05:16,  6.80s/it]

  Eigensolving took: 0.2380 seconds
  Electronic Energy: [-111.29496355]
  Total Energy: [-78.07714415]
  num carryover full strs: 1485
Iter 0 took: 1.7908 seconds

Running ethylene_LUCJ_L4_STO-3G_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  607
  num selected half strs:  607
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.081976 seconds
  Subspace dimension: 607 x 607 = 368_449
  Operator projection took: 5.606388 seconds
  CSR matrix memory: 1190.278400 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 47%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                       | 505/1080 [4:23:38<1:05:49,  6.87s/it]

  Eigensolving took: 0.3621 seconds
  Electronic Energy: [-110.30208683]
  Total Energy: [-77.08426743]
  num carryover full strs: 423
Iter 0 took: 6.1024 seconds

Running ethylene_LUCJ_L4_STO-3G_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  681
  num selected half strs:  681
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.104660 seconds
  Subspace dimension: 681 x 681 = 463_761
  Operator projection took: 7.321985 seconds
  CSR matrix memory: 1774.049885 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 47%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                       | 506/1080 [4:23:47<1:12:22,  7.57s/it]

  Eigensolving took: 0.7457 seconds
  Electronic Energy: [-110.34871186]
  Total Energy: [-77.13089246]
  num carryover full strs: 498
Iter 0 took: 8.2352 seconds

Running ethylene_LUCJ_L4_STO-3G_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  656
  num selected half strs:  656
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.097218 seconds
  Subspace dimension: 656 x 656 = 430_336
  Operator projection took: 6.774851 seconds
  CSR matrix memory: 1554.401020 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 47%|███████████████████████████████████████████████████████████████████████████████████████████                                                                                                       | 507/1080 [4:23:55<1:14:22,  7.79s/it]

  Eigensolving took: 0.4304 seconds
  Electronic Energy: [-110.36302033]
  Total Energy: [-77.14520093]
  num carryover full strs: 342
Iter 0 took: 7.3666 seconds

Running ethylene_LUCJ_L4_STO-3G_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  642
  num selected half strs:  642
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.089344 seconds
  Subspace dimension: 642 x 642 = 412_164
  Operator projection took: 6.514385 seconds
  CSR matrix memory: 1461.247425 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 47%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                      | 508/1080 [4:24:03<1:15:01,  7.87s/it]

  Eigensolving took: 0.4141 seconds
  Electronic Energy: [-110.31671671]
  Total Energy: [-77.0988973]
  num carryover full strs: 478
Iter 0 took: 7.0764 seconds

Running ethylene_LUCJ_L4_STO-3G_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  686
  num selected half strs:  686
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.103197 seconds
  Subspace dimension: 686 x 686 = 470_596
  Operator projection took: 7.707816 seconds
  CSR matrix memory: 1814.476200 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 47%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                      | 509/1080 [4:24:13<1:19:03,  8.31s/it]

  Eigensolving took: 0.5216 seconds
  Electronic Energy: [-110.2998576]
  Total Energy: [-77.08203819]
  num carryover full strs: 206
Iter 0 took: 8.3987 seconds

Running ethylene_LUCJ_L4_STO-3G_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  269
  num selected half strs:  269
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.012437 seconds
  Subspace dimension: 269 x 269 = 72_361

 47%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                      | 510/1080 [4:24:15<1:01:13,  6.44s/it]

  Operator projection took: 0.983648 seconds
  CSR matrix memory: 352.091190 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1436 seconds
  Electronic Energy: [-110.43926111]
  Total Energy: [-77.22144171]
  num carryover full strs: 2867
Iter 0 took: 1.1553 seconds

Running ethylene_LUCJ_L4_aug-cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  724
  num selected half strs:  724
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.114272 seconds
  Subspace dimension: 724 x 724 = 524_176
  Operator projection took: 8.201479 seconds
  CSR matrix memory: 2125.451954 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 47%|███████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                      | 511/1080 [4:24:25<1:12:18,  7.62s/it]

  Eigensolving took: 0.5925 seconds
  Electronic Energy: [-111.2626934]
  Total Energy: [-78.04487399]
  num carryover full strs: 100
Iter 0 took: 8.9790 seconds

Running ethylene_LUCJ_L4_aug-cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  727
  num selected half strs:  727
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.119073 seconds
  Subspace dimension: 727 x 727 = 528_529
  Operator projection took: 8.243562 seconds
  CSR matrix memory: 2159.873676 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 47%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                      | 512/1080 [4:24:35<1:19:54,  8.44s/it]

  Eigensolving took: 0.6070 seconds
  Electronic Energy: [-111.26278936]
  Total Energy: [-78.04496995]
  num carryover full strs: 61
Iter 0 took: 9.0412 seconds

Running ethylene_LUCJ_L4_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  703
  num selected half strs:  703
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.113592 seconds
  Subspace dimension: 703 x 703 = 494_209
  Operator projection took: 7.632488 seconds
  CSR matrix memory: 1894.661884 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 48%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                     | 513/1080 [4:24:45<1:23:14,  8.81s/it]

  Eigensolving took: 0.5492 seconds
  Electronic Energy: [-111.26092798]
  Total Energy: [-78.04310858]
  num carryover full strs: 50
Iter 0 took: 8.3691 seconds

Running ethylene_LUCJ_L4_aug-cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  706
  num selected half strs:  706
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.107393 seconds
  Subspace dimension: 706 x 706 = 498_436
  Operator projection took: 7.643341 seconds
  CSR matrix memory: 1919.699909 MBs
  Initial guess vector v0 construction took: 0.0009 seconds
  Starting eigensolving ...

 48%|████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                     | 514/1080 [4:24:55<1:25:29,  9.06s/it]

  Eigensolving took: 0.5373 seconds
  Electronic Energy: [-111.26136837]
  Total Energy: [-78.04354897]
  num carryover full strs: 61
Iter 0 took: 8.3603 seconds

Running ethylene_LUCJ_L4_aug-cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  658
  num selected half strs:  658
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.094668 seconds
  Subspace dimension: 658 x 658 = 432_964
  Operator projection took: 6.360426 seconds
  CSR matrix memory: 1496.169407 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 48%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                     | 515/1080 [4:25:03<1:23:03,  8.82s/it]

  Eigensolving took: 0.4400 seconds
  Electronic Energy: [-111.26092967]
  Total Energy: [-78.04311027]
  num carryover full strs: 23
Iter 0 took: 6.9544 seconds

Running ethylene_LUCJ_L4_aug-cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  298
  num selected half strs:  298
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.015481 seconds
  Subspace dimension: 298 x 298 = 88_804
  Operator projection took: 1.164673 seconds
  CSR matrix memory: 438.708683 MBs
  Initial guess vector v0 construction took: 0.0002 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1855 seconds
  Electronic Energy: [-111.26311477]
  Total Energy: [-78.04529536]
  num carryover full strs: 227
Iter 0 took: 1.3803 seconds

 48%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                     | 516/1080 [4:25:06<1:05:37,  6.98s/it]

Running ethylene_LUCJ_L4_cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  593
  num selected half strs:  593
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.073713 seconds
  Subspace dimension: 593 x 593 = 351_649
  Operator projection took: 5.251161 seconds
  CSR matrix memory: 1104.992176 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 48%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                     | 517/1080 [4:25:12<1:04:44,  6.90s/it]

  Eigensolving took: 0.3299 seconds
  Electronic Energy: [-111.25832269]
  Total Energy: [-78.04050328]
  num carryover full strs: 74
Iter 0 took: 5.7043 seconds

Running ethylene_LUCJ_L4_cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  694
  num selected half strs:  694
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.114611 seconds
  Subspace dimension: 694 x 694 = 481_636
  Operator projection took: 7.821876 seconds
  CSR matrix memory: 1869.684788 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 48%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 518/1080 [4:25:22<1:11:58,  7.68s/it]

  Eigensolving took: 0.5246 seconds
  Electronic Energy: [-111.26033174]
  Total Energy: [-78.04251234]
  num carryover full strs: 155
Iter 0 took: 8.5312 seconds

Running ethylene_LUCJ_L4_cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  705
  num selected half strs:  705
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.109388 seconds
  Subspace dimension: 705 x 705 = 497_025
  Operator projection took: 8.012629 seconds
  CSR matrix memory: 1972.757359 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 48%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                    | 519/1080 [4:25:32<1:17:39,  8.31s/it]

  Eigensolving took: 0.5649 seconds
  Electronic Energy: [-111.26095146]
  Total Energy: [-78.04313206]
  num carryover full strs: 240
Iter 0 took: 8.7570 seconds

Running ethylene_LUCJ_L4_cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  634
  num selected half strs:  634
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.081172 seconds
  Subspace dimension: 634 x 634 = 401_956
  Operator projection took: 6.363440 seconds
  CSR matrix memory: 1385.794117 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 48%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                    | 520/1080 [4:25:40<1:16:39,  8.21s/it]

  Eigensolving took: 0.4052 seconds
  Electronic Energy: [-111.25965971]
  Total Energy: [-78.04184031]
  num carryover full strs: 133
Iter 0 took: 6.9010 seconds

Running ethylene_LUCJ_L4_cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  680
  num selected half strs:  680
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.105332 seconds
  Subspace dimension: 680 x 680 = 462_400
  Operator projection took: 7.370483 seconds
  CSR matrix memory: 1744.729633 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 48%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                    | 521/1080 [4:25:49<1:18:56,  8.47s/it]

  Eigensolving took: 0.5264 seconds
  Electronic Energy: [-111.26040749]
  Total Energy: [-78.04258808]
  num carryover full strs: 149
Iter 0 took: 8.0616 seconds

Running ethylene_LUCJ_L4_cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  316
  num selected half strs:  316
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017769 seconds
  Subspace dimension: 316 x 316 = 99_856
  Operator projection took: 1.388519 seconds
  CSR matrix memory: 495.992588 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 48%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 522/1080 [4:25:51<1:02:23,  6.71s/it]

  Eigensolving took: 0.2029 seconds
  Electronic Energy: [-111.29502917]
  Total Energy: [-78.07720976]
  num carryover full strs: 1374
Iter 0 took: 1.6275 seconds

Running ethylene_LUCJ_L5_STO-3G_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  642
  num selected half strs:  642
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.084116 seconds
  Subspace dimension: 642 x 642 = 412_164
  Operator projection took: 6.867061 seconds
  CSR matrix memory: 1449.746708 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 48%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                    | 523/1080 [4:26:00<1:06:55,  7.21s/it]

  Eigensolving took: 0.4146 seconds
  Electronic Energy: [-110.32362864]
  Total Energy: [-77.10580923]
  num carryover full strs: 386
Iter 0 took: 7.4198 seconds

Running ethylene_LUCJ_L5_STO-3G_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  702
  num selected half strs:  702
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.117980 seconds
  Subspace dimension: 702 x 702 = 492_804
  Operator projection took: 7.998005 seconds
  CSR matrix memory: 1932.586170 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 49%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                   | 524/1080 [4:26:09<1:13:41,  7.95s/it]

  Eigensolving took: 0.5583 seconds
  Electronic Energy: [-110.3033113]
  Total Energy: [-77.0854919]
  num carryover full strs: 405
Iter 0 took: 8.7468 seconds

Running ethylene_LUCJ_L5_STO-3G_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  601
  num selected half strs:  601
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.071806 seconds
  Subspace dimension: 601 x 601 = 361_201
  Operator projection took: 5.499692 seconds
  CSR matrix memory: 1168.751698 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 49%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                   | 525/1080 [4:26:16<1:10:37,  7.64s/it]

  Eigensolving took: 0.3517 seconds
  Electronic Energy: [-110.31065177]
  Total Energy: [-77.09283237]
  num carryover full strs: 249
Iter 0 took: 5.9726 seconds

Running ethylene_LUCJ_L5_STO-3G_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  665
  num selected half strs:  665
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.097606 seconds
  Subspace dimension: 665 x 665 = 442_225
  Operator projection took: 6.976691 seconds
  CSR matrix memory: 1637.147434 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 49%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                   | 526/1080 [4:26:25<1:13:00,  7.91s/it]

  Eigensolving took: 0.4744 seconds
  Electronic Energy: [-110.31177525]
  Total Energy: [-77.09395584]
  num carryover full strs: 472
Iter 0 took: 7.6073 seconds

Running ethylene_LUCJ_L5_STO-3G_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  596
  num selected half strs:  596
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.075759 seconds
  Subspace dimension: 596 x 596 = 355_216
  Operator projection took: 5.480225 seconds
  CSR matrix memory: 1163.027042 MBs
  Initial guess vector v0 construction took: 0.0003 seconds
  Starting eigensolving ...

 49%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                   | 527/1080 [4:26:32<1:10:13,  7.62s/it]

  Eigensolving took: 0.3997 seconds
  Electronic Energy: [-110.29437386]
  Total Energy: [-77.07655446]
  num carryover full strs: 173
Iter 0 took: 6.0093 seconds

Running ethylene_LUCJ_L5_STO-3G_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  249
  num selected half strs:  249
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.011187 seconds
  Subspace dimension: 249 x 249 = 62_001

 49%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 528/1080 [4:26:34<54:14,  5.90s/it]

  Operator projection took: 0.813180 seconds
  CSR matrix memory: 286.956532 MBs
  Initial guess vector v0 construction took: 0.0006 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1192 seconds
  Electronic Energy: [-110.42856179]
  Total Energy: [-77.21074238]
  num carryover full strs: 2509
Iter 0 took: 0.9567 seconds

Running ethylene_LUCJ_L5_aug-cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  688
  num selected half strs:  688
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.105145 seconds
  Subspace dimension: 688 x 688 = 473_344
  Operator projection took: 7.076026 seconds
  CSR matrix memory: 1741.621372 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 49%|███████████████████████████████████████████████████████████████████████████████████████████████                                                                                                   | 529/1080 [4:26:43<1:03:01,  6.86s/it]

  Eigensolving took: 0.4800 seconds
  Electronic Energy: [-111.26131703]
  Total Energy: [-78.04349762]
  num carryover full strs: 56
Iter 0 took: 7.7242 seconds

Running ethylene_LUCJ_L5_aug-cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  673
  num selected half strs:  673
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.101889 seconds
  Subspace dimension: 673 x 673 = 452_929
  Operator projection took: 6.747866 seconds
  CSR matrix memory: 1583.906910 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 49%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                  | 530/1080 [4:26:52<1:08:00,  7.42s/it]

  Eigensolving took: 0.4758 seconds
  Electronic Energy: [-111.2609074]
  Total Energy: [-78.04308799]
  num carryover full strs: 32
Iter 0 took: 7.3874 seconds

Running ethylene_LUCJ_L5_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  750
  num selected half strs:  750
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.130326 seconds
  Subspace dimension: 750 x 750 = 562_500
  Operator projection took: 9.072205 seconds
  CSR matrix memory: 2341.174580 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 49%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                  | 531/1080 [4:27:03<1:18:25,  8.57s/it]

  Eigensolving took: 0.6681 seconds
  Electronic Energy: [-111.26089273]
  Total Energy: [-78.04307333]
  num carryover full strs: 26
Iter 0 took: 9.9484 seconds

Running ethylene_LUCJ_L5_aug-cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  731
  num selected half strs:  731
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.120089 seconds
  Subspace dimension: 731 x 731 = 534_361
  Operator projection took: 8.446122 seconds
  CSR matrix memory: 2151.499073 MBs
  Initial guess vector v0 construction took: 0.0007 seconds
  Starting eigensolving ...

 49%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                  | 532/1080 [4:27:13<1:23:41,  9.16s/it]

  Eigensolving took: 0.6173 seconds
  Electronic Energy: [-111.26252981]
  Total Energy: [-78.04471041]
  num carryover full strs: 39
Iter 0 took: 9.2540 seconds

Running ethylene_LUCJ_L5_aug-cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  677
  num selected half strs:  677
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.107044 seconds
  Subspace dimension: 677 x 677 = 458_329
  Operator projection took: 7.072577 seconds
  CSR matrix memory: 1657.624531 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 49%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 533/1080 [4:27:22<1:23:15,  9.13s/it]

  Eigensolving took: 0.4928 seconds
  Electronic Energy: [-111.26088352]
  Total Energy: [-78.04306412]
  num carryover full strs: 27
Iter 0 took: 7.7378 seconds

Running ethylene_LUCJ_L5_aug-cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  283
  num selected half strs:  283
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.014185 seconds
  Subspace dimension: 283 x 283 = 80_089

 49%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                  | 534/1080 [4:27:25<1:04:57,  7.14s/it]

  Operator projection took: 1.061478 seconds
  CSR matrix memory: 412.892460 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...
  Eigensolving took: 0.1248 seconds
  Electronic Energy: [-111.26318966]
  Total Energy: [-78.04537025]
  num carryover full strs: 254
Iter 0 took: 1.2158 seconds

Running ethylene_LUCJ_L5_cc-pVDZ_CCSD
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  672
  num selected half strs:  672
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.098371 seconds
  Subspace dimension: 672 x 672 = 451_584
  Operator projection took: 7.124269 seconds
  CSR matrix memory: 1678.219715 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 50%|████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                  | 535/1080 [4:27:34<1:09:14,  7.62s/it]

  Eigensolving took: 0.4778 seconds
  Electronic Energy: [-111.25777497]
  Total Energy: [-78.03995556]
  num carryover full strs: 46
Iter 0 took: 7.7621 seconds

Running ethylene_LUCJ_L5_cc-pVDZ_ML
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  646
  num selected half strs:  646
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.086312 seconds
  Subspace dimension: 646 x 646 = 417_316
  Operator projection took: 6.654572 seconds
  CSR matrix memory: 1438.182514 MBs
  Initial guess vector v0 construction took: 0.0005 seconds
  Starting eigensolving ...

 50%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                 | 536/1080 [4:27:42<1:10:52,  7.82s/it]

  Eigensolving took: 0.4266 seconds
  Electronic Energy: [-111.25937913]
  Total Energy: [-78.04155973]
  num carryover full strs: 66
Iter 0 took: 7.2287 seconds

Running ethylene_LUCJ_L5_cc-pVDZ_ML_exact
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  632
  num selected half strs:  632
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.078468 seconds
  Subspace dimension: 632 x 632 = 399_424
  Operator projection took: 6.261414 seconds
  CSR matrix memory: 1359.754276 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 50%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                 | 537/1080 [4:27:50<1:10:37,  7.80s/it]

  Eigensolving took: 0.3839 seconds
  Electronic Energy: [-111.2594438]
  Total Energy: [-78.04162439]
  num carryover full strs: 111
Iter 0 took: 6.7740 seconds

Running ethylene_LUCJ_L5_cc-pVDZ_MP2
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  668
  num selected half strs:  668
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.126023 seconds
  Subspace dimension: 668 x 668 = 446_224
  Operator projection took: 7.139451 seconds
  CSR matrix memory: 1661.595173 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 50%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                 | 538/1080 [4:27:59<1:13:32,  8.14s/it]

  Eigensolving took: 0.4677 seconds
  Electronic Energy: [-111.26021224]
  Total Energy: [-78.04239283]
  num carryover full strs: 144
Iter 0 took: 7.7898 seconds

Running ethylene_LUCJ_L5_cc-pVDZ_random
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  690
  num selected half strs:  690
  Half strs construction took: 0.0002 seconds
  Subspace construction took: 0.104813 seconds
  Subspace dimension: 690 x 690 = 476_100
  Operator projection took: 7.658653 seconds
  CSR matrix memory: 1856.919804 MBs
  Initial guess vector v0 construction took: 0.0008 seconds
  Starting eigensolving ...

 50%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                 | 539/1080 [4:28:08<1:16:45,  8.51s/it]

  Eigensolving took: 0.5357 seconds
  Electronic Energy: [-111.2587025]
  Total Energy: [-78.0408831]
  num carryover full strs: 102
Iter 0 took: 8.3658 seconds

Running ethylene_LUCJ_L5_cc-pVDZ_zeroes
Active Space Orbitals: 14, Electrons: 16, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  316
  num selected half strs:  316
  Half strs construction took: 0.0001 seconds
  Subspace construction took: 0.017277 seconds
  Subspace dimension: 316 x 316 = 99_856
  Operator projection took: 1.425689 seconds
  CSR matrix memory: 522.847294 MBs
  Initial guess vector v0 construction took: 0.0004 seconds
  Starting eigensolving ...

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 540/1080 [4:28:11<1:01:01,  6.78s/it]

  Eigensolving took: 0.2844 seconds
  Electronic Energy: [-111.29390255]
  Total Energy: [-78.07608315]
  num carryover full strs: 1347
Iter 0 took: 1.7462 seconds

Running fluoroform_LUCJ_L1_STO-3G_CCSD
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  5
  num selected half strs:  5
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000015 seconds
  Subspace dimension: 5 x 5 = 25

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                | 541/1080 [4:28:22<1:13:13,  8.15s/it]

  Operator projection took: 0.235220 seconds
  CSR matrix memory: 0.000889 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0004 seconds
  Electronic Energy: [-464.48595707]
  Total Energy: [-332.09809655]
  num carryover full strs: 2
Iter 0 took: 0.2392 seconds

Running fluoroform_LUCJ_L1_STO-3G_ML
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  7
  num selected half strs:  7
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000021 seconds
  Subspace dimension: 7 x 7 = 49

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 542/1080 [4:28:33<1:21:45,  9.12s/it]

  Operator projection took: 0.238621 seconds
  CSR matrix memory: 0.001713 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0004 seconds
  Electronic Energy: [-464.48545326]
  Total Energy: [-332.09759274]
  num carryover full strs: 3
Iter 0 took: 0.2428 seconds

Running fluoroform_LUCJ_L1_STO-3G_ML_exact
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  7
  num selected half strs:  7
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000019 seconds
  Subspace dimension: 7 x 7 = 49

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                | 543/1080 [4:28:45<1:27:29,  9.78s/it]

  Operator projection took: 0.236840 seconds
  CSR matrix memory: 0.002033 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0004 seconds
  Electronic Energy: [-464.48547775]
  Total Energy: [-332.09761723]
  num carryover full strs: 3
Iter 0 took: 0.2408 seconds

Running fluoroform_LUCJ_L1_STO-3G_MP2
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                | 544/1080 [4:28:56<1:31:53, 10.29s/it]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  11
  num selected half strs:  11
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000033 seconds
  Subspace dimension: 11 x 11 = 121
  Operator projection took: 0.253919 seconds
  CSR matrix memory: 0.006428 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0002 seconds
  Electronic Energy: [-464.48545368]
  Total Energy: [-332.09759316]
  num carryover full strs: 3
Iter 0 took: 0.2577 seconds

Running fluoroform_LUCJ_L1_STO-3G_random
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  7
  num selected half strs:  7
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000023 seconds
  Subspace dimension: 7 x 7 = 49

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                | 545/1080 [4:29:08<1:34:22, 10.58s/it]

  Operator projection took: 0.238393 seconds
  CSR matrix memory: 0.001392 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0004 seconds
  Electronic Energy: [-464.48545301]
  Total Energy: [-332.09759249]
  num carryover full strs: 1
Iter 0 took: 0.2430 seconds

Running fluoroform_LUCJ_L1_STO-3G_zeroes
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  51
  num selected half strs:  51
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000448 seconds
  Subspace dimension: 51 x 51 = 2_601

 51%|██████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                | 546/1080 [4:29:20<1:38:08, 11.03s/it]

  Operator projection took: 0.803899 seconds
  CSR matrix memory: 1.152241 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0023 seconds
  Electronic Energy: [-464.49631178]
  Total Energy: [-332.10845126]
  num carryover full strs: 242
Iter 0 took: 0.8108 seconds

Running fluoroform_LUCJ_L1_aug-cc-pVDZ_CCSD
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  16
  num selected half strs:  16
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000055 seconds
  Subspace dimension: 16 x 16 = 256

 51%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                               | 547/1080 [4:29:32<1:40:18, 11.29s/it]

  Operator projection took: 0.278788 seconds
  CSR matrix memory: 0.016544 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0014 seconds
  Electronic Energy: [-469.20065028]
  Total Energy: [-336.81278976]
  num carryover full strs: 1
Iter 0 took: 0.2835 seconds

Running fluoroform_LUCJ_L1_aug-cc-pVDZ_ML
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  12
  num selected half strs:  12
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000038 seconds
  Subspace dimension: 12 x 12 = 144

 51%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 548/1080 [4:29:43<1:41:53, 11.49s/it]

  Operator projection took: 0.248467 seconds
  CSR matrix memory: 0.009388 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0013 seconds
  Electronic Energy: [-469.20065097]
  Total Energy: [-336.81279045]
  num carryover full strs: 4
Iter 0 took: 0.2530 seconds

Running fluoroform_LUCJ_L1_aug-cc-pVDZ_ML_exact
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  34
  num selected half strs:  34
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000217 seconds
  Subspace dimension: 34 x 34 = 1_156

 51%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                               | 549/1080 [4:29:56<1:43:20, 11.68s/it]

  Operator projection took: 0.466410 seconds
  CSR matrix memory: 0.154240 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0020 seconds
  Electronic Energy: [-469.20065105]
  Total Energy: [-336.81279053]
  num carryover full strs: 5
Iter 0 took: 0.4722 seconds

Running fluoroform_LUCJ_L1_aug-cc-pVDZ_MP2
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  23
  num selected half strs:  23
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000102 seconds
  Subspace dimension: 23 x 23 = 529

 51%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                               | 550/1080 [4:30:08<1:44:09, 11.79s/it]

  Operator projection took: 0.332780 seconds
  CSR matrix memory: 0.044193 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0018 seconds
  Electronic Energy: [-469.20065048]
  Total Energy: [-336.81278996]
  num carryover full strs: 2
Iter 0 took: 0.3384 seconds

Running fluoroform_LUCJ_L1_aug-cc-pVDZ_random
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  3
  num selected half strs:  3
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000013 seconds
  Subspace dimension: 3 x 3 = 9

 51%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                               | 551/1080 [4:30:19<1:44:07, 11.81s/it]

  Operator projection took: 0.223729 seconds
  CSR matrix memory: 0.000141 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0003 seconds
  Electronic Energy: [-469.20065028]
  Total Energy: [-336.81278976]
  num carryover full strs: 1
Iter 0 took: 0.2276 seconds

Running fluoroform_LUCJ_L1_aug-cc-pVDZ_zeroes
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  67
  num selected half strs:  67
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000765 seconds
  Subspace dimension: 67 x 67 = 4_489

 51%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 552/1080 [4:30:32<1:44:34, 11.88s/it]

  Operator projection took: 0.347153 seconds
  CSR matrix memory: 2.703297 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0045 seconds
  Electronic Energy: [-469.20066801]
  Total Energy: [-336.8128075]
  num carryover full strs: 45
Iter 0 took: 0.3565 seconds

Running fluoroform_LUCJ_L1_cc-pVDZ_CCSD
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

 51%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                              | 553/1080 [4:30:43<1:43:05, 11.74s/it]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  17
  num selected half strs:  17
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000062 seconds
  Subspace dimension: 17 x 17 = 289
  Operator projection took: 0.292932 seconds
  CSR matrix memory: 0.022724 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0016 seconds
  Electronic Energy: [-469.17551185]
  Total Energy: [-336.78765133]
  num carryover full strs: 7
Iter 0 took: 0.2981 seconds

Running fluoroform_LUCJ_L1_cc-pVDZ_ML
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

 51%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 554/1080 [4:30:54<1:41:52, 11.62s/it]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  3
  num selected half strs:  3
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000014 seconds
  Subspace dimension: 3 x 3 = 9
  Operator projection took: 0.234435 seconds
  CSR matrix memory: 0.000141 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0001 seconds
  Electronic Energy: [-469.17464405]
  Total Energy: [-336.78678353]
  num carryover full strs: 1
Iter 0 took: 0.2379 seconds

Running fluoroform_LUCJ_L1_cc-pVDZ_ML_exact
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  5
  num selected half strs:  5
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000015 seconds
  Subspace dimension: 5 x 5 = 25

 51%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 555/1080 [4:31:06<1:40:49, 11.52s/it]

  Operator projection took: 0.233463 seconds
  CSR matrix memory: 0.001072 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0004 seconds
  Electronic Energy: [-469.17464407]
  Total Energy: [-336.78678355]
  num carryover full strs: 1
Iter 0 took: 0.2378 seconds

Running fluoroform_LUCJ_L1_cc-pVDZ_MP2
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  9
  num selected half strs:  9
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000029 seconds
  Subspace dimension: 9 x 9 = 81

 51%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                              | 556/1080 [4:31:17<1:40:21, 11.49s/it]

  Operator projection took: 0.247890 seconds
  CSR matrix memory: 0.004124 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0005 seconds
  Electronic Energy: [-469.17464405]
  Total Energy: [-336.78678354]
  num carryover full strs: 1
Iter 0 took: 0.2519 seconds

Running fluoroform_LUCJ_L1_cc-pVDZ_random
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

 52%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                              | 557/1080 [4:31:28<1:39:50, 11.45s/it]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  7
  num selected half strs:  7
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000020 seconds
  Subspace dimension: 7 x 7 = 49
  Operator projection took: 0.236859 seconds
  CSR matrix memory: 0.001759 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0002 seconds
  Electronic Energy: [-469.17464405]
  Total Energy: [-336.78678353]
  num carryover full strs: 1
Iter 0 took: 0.2404 seconds

Running fluoroform_LUCJ_L1_cc-pVDZ_zeroes
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0
  num total half strs:  69
  num selected half strs:  69
  Half strs construction took: 0.0000 seconds
  Subspace construction took: 0.000815 seconds
  Subspace dimension: 69 x 69 = 4_761

 52%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 558/1080 [4:31:40<1:39:41, 11.46s/it]

  Operator projection took: 0.367299 seconds
  CSR matrix memory: 3.732426 MBs
  Initial guess vector v0 construction took: 0.0000 seconds
  Starting eigensolving ...
  Eigensolving took: 0.0039 seconds
  Electronic Energy: [-469.17852899]
  Total Energy: [-336.79066847]
  num carryover full strs: 263
Iter 0 took: 0.3767 seconds

Running fluoroform_LUCJ_L2_STO-3G_CCSD
Active Space Orbitals: 21, Electrons: 34, Frozen: 0
Active indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

 52%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                             | 558/1080 [4:31:51<4:14:19, 29.23s/it]

use_recovery=False: overriding max_iterations=100 -> 1
ITERATION 0

ValueError: samples_per_batch (= 0) must > 0

In [20]:
# sanity check on the last file processed
name, layers, basis, injection, energy, subspace_dimension = energy_data[-1]
print(f"{name} (L={layers}, {basis}, {injection}): E = {energy:.6f} Ha, subspace dim = {subspace_dimension}")

fluoroform (L=1, cc-pVDZ, zeroes): E = -336.790668 Ha, subspace dim = 4761

In [21]:
norecovery_df = pd.DataFrame(
    energy_data,
    columns=['Name', 'L', 'Basis', 'Injection', 'Energy_NoRecovery', 'SubspaceDim_NoRecovery'],
)
norecovery_df.to_excel("Energies_NoRecovery.xlsx")
norecovery_df

,Name,L,Basis,Injection,Energy_NoRecovery,SubspaceDim_NoRecovery
0,(Z)-1-fluoroprop-1-ene,1,STO-3G,CCSD,-213.116485,71289
1,(Z)-1-fluoroprop-1-ene,1,STO-3G,ML,-213.116475,29929
2,(Z)-1-fluoroprop-1-ene,1,STO-3G,ML_exact,-213.116469,39204
3,(Z)-1-fluoroprop-1-ene,1,STO-3G,MP2,-213.116469,5929
4,(Z)-1-fluoroprop-1-ene,1,STO-3G,random,-213.116469,25921
...,...,...,...,...,...,...
553,fluoroform,1,cc-pVDZ,ML,-336.786784,9
554,fluoroform,1,cc-pVDZ,ML_exact,-336.786784,25
555,fluoroform,1,cc-pVDZ,MP2,-336.786784,81
556,fluoroform,1,cc-pVDZ,random,-336.786784,49
557,fluoroform,1,cc-pVDZ,zeroes,-336.790668,4761