# Verifying Amplitudes and Correlation Energies

TODO:
- Create a pandas dataframe with the following structure:

structure | basis set | PySCF_Corr | Psi4_Corr | PySCF_norm_t1 | Psi4_norm_t1 | PySCF_norm_t2 | Psi4_norm_t2

- Populate the data frame with the provided code
- Use a try-except to handle linalg error, save a list of faulty structures
- Calculate the mean error for each structure basis combo

In [45]:
import psutil
import sys
# !{sys.executable} --version
# !{sys.executable} -m pip install shap --upgrade 
import joblib
import time
from shutil import copy
#import tensorflow as tf
import os
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm


from glob import glob
import psi4
from helper_CC_ML_spacial import *

import pyscf
import pyscf.cc
import pyscf.mcscf

In [46]:
import pandas as pd
import numpy as np
import glob
import os
from numpy.linalg import LinAlgError
import psi4
import pyscf
from pyscf import gto, scf, cc

# Import HelperCCEnergy for Psi4

# Path to XYZ files
xyz_folder = 'diatomics'
xyz_files = glob.glob(os.path.join(xyz_folder, '*.xyz'))

# Extract structure names and contents
structures = []
structure_contents = {}

for file_path in xyz_files:
    structure_name = os.path.splitext(os.path.basename(file_path))[0]
    structures.append(structure_name)
    with open(file_path, 'r') as f:
        structure_contents[structure_name] = f.read()

# Basis sets to iterate over

basis_sets = ['STO-3G','cc-pVDZ','aug-cc-pVDZ']

results = []
failures = []

for structure in structures:
    xyz_path = os.path.join(xyz_folder, f'{structure}.xyz')
    with open(xyz_path, 'r') as f:
        xyz_text = f.read()

    for basis in basis_sets:
        # Initialize default values
        psi4_corr = np.nan
        pyscf_corr = np.nan
        norm_t1_psi4 = np.nan
        norm_t2_psi4 = np.nan
        norm_t1_pyscf = np.nan
        norm_t2_pyscf = np.nan

        ##### PSI4 Processing #####
        try:
            qmol = psi4.qcdb.Molecule.from_string(xyz_text, dtype='xyz')
            mol_psi4 = psi4.geometry(qmol.create_psi4_string_from_molecule() + 'symmetry c1')

            psi4.core.clean()
            psi4.core.be_quiet()

            psi4.set_options({
                'basis': basis,
                'scf_type': 'pk',
                'reference': 'rhf',
                'mp2_type': 'conv',
                'e_convergence': 1e-8,
                'd_convergence': 1e-8
            })

            rhf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
            scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
            A = HelperCCEnergy(mol_psi4, rhf_e, scf_wfn, freeze_core=False)

            try:
                A.compute_energy()
                psi4_corr = A.FinalEnergy
            except LinAlgError:
                failures.append({'structure': structure, 'basis set': basis, 'method': 'Psi4_Corr'})

            # Extract amplitudes
            norm_t1_psi4 = np.linalg.norm(A.t1)
            norm_t2_psi4 = np.linalg.norm(A.t1)

        except Exception as e:
            failures.append({'structure': structure, 'basis set': basis, 'method': 'Psi4_Setup', 'error': str(e)})

        ##### PYSCF Processing #####
        try:
            mol_pyscf = gto.Mole()
            mol_pyscf.build(atom=xyz_path, basis=basis, symmetry='c1')

            # Define active space (assuming no frozen orbitals for simplicity)
            n_frozen = 0
            active_space = range(n_frozen, mol_pyscf.nao_nr())
            scf_calc = scf.RHF(mol_pyscf).run()
            

            # Compute CCSD
            ccsd_calc = cc.CCSD(scf_calc, frozen=[i for i in range(mol_pyscf.nao_nr()) if i not in active_space]).run()
            pyscf_corr = ccsd_calc.e_corr

            t1_pyscf = ccsd_calc.t1
            t2_pyscf = ccsd_calc.t2
            norm_t1_pyscf = np.linalg.norm(t1_pyscf)
            norm_t2_pyscf = np.linalg.norm(t2_pyscf)

        except LinAlgError:
            failures.append({'structure': structure, 'basis set': basis, 'method': 'PySCF_Corr'})
        except Exception as e:
            failures.append({'structure': structure, 'basis set': basis, 'method': 'PySCF_Setup', 'error': str(e)})

        # Store results
        results.append({
            'structure': structure,
            'basis set': basis,
            'PySCF_Corr': pyscf_corr,
            'Psi4_Corr': psi4_corr,
            'PySCF_norm_t1': norm_t1_pyscf,
            'Psi4_norm_t1': norm_t1_psi4,
            'PySCF_norm_t2': norm_t2_pyscf,
            'Psi4_norm_t2': norm_t2_psi4
        })

# Create and display final DataFrame
df = pd.DataFrame(results)
print("\nFinal DataFrame:")
print(df)

if failures:
    print("\nFailures Encountered:")
    for failure in failures:
        print(f"Structure: {failure['structure']}, Basis Set: {failure['basis set']}, Method: {failure['method']}, Error: {failure.get('error', '')}")

# Optional: Save results to CSV
# df.to_csv('amplitude_correlation_results.csv', index=False)

Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 6 basis functions.
(6, 6)
(6, 6)
Building initial guess...

..initialized CCSD in 0.013 seconds.

CCSD Iteration   0: CCSD correlation = -0.026326310201129   dE =  2.63263E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.036474688643062   dE = -1.01484E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.040882897046905   dE = -4.40821E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.044820008618742   dE = -3.93711E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.045713492152981   dE = -8.93484E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.046573303575851   dE = -8.59811E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.050046718490928   dE = -3.47341E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.070574298008330   dE = -2.05276E-02   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.056069359416175   dE =  1.45049E-02   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.059264650531132   dE = -3.19529E-03   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.062824455332269   dE = -3.55980E-03   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.061728621079711   dE =  1.09583E-03   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.061975849358438   dE = -2.47228E-04   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.061992560940884   dE = -1.67116E-05   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.061980548042914   dE =  1.20129E-05   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.061979415597380   dE =  1.13245E-06   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.061979392979612   dE =  2.26178E-08   DIIS = 7

CCSD has converged in 0.084 seconds!

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:552: RuntimeWarning: divide by zero encountered in log10
  self.t2mag=np.log10(np.absolute(self.t2))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:593: RuntimeWarning: divide by zero encountered in log10
  self.Jia1mag=np.log10(np.absolute(self.Jia1))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:594: RuntimeWarning: divide by zero encountered in log10
  self.Jia2mag=np.log10(np.absolute(self.Jia2))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:595: RuntimeWarning: divide by zero encountered in log10
  self.Kia1mag=np.log10(np.absolute(self.Kia1))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:596: RuntimeWarning: divide by zero encountered in log10
  self.Kia2mag=np.log10(np.absolute(self.Kia2))

converged SCF energy = -54.1350442502145
E(CCSD) = -54.19702330469029  E_corr = -0.06197905447580512
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 19 basis functions.
(19, 19)
(19, 19)
Building initial guess...

..initialized CCSD in 0.126 seconds.

CCSD Iteration   0: CCSD correlation = -0.122121706141825   dE =  1.22122E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.139831956897877   dE = -1.77103E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.144717986038950   dE = -4.88603E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.148116404578771   dE = -3.39842E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.149517727652401   dE = -1.40132E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.150508874095065   dE = -9.91146E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.152189534087983   dE = -1.68066E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.153348478175646   dE = -1.15894E-03   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.153665381650199   dE = -3.16903E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.153704061131485   dE = -3.86795E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.153711970247018   dE = -7.90912E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.153711406322950   dE =  5.63924E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.153711335741110   dE =  7.05818E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.153711265757577   dE =  6.99835E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.153711266764177   dE = -1.00660E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.153711253112731   dE =  1.36514E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.153711232744430   dE =  2.03683E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.153711208470210   dE =  2.42742E-08   DIIS = 7

CCSD has converged in 0.154 seconds!
converged SCF energy = -54.8574063406849
E(CCSD) = -55.0111175382542  E_corr = -0.1537111975693163
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 32 basis functions.
(32, 32)
(32, 32)
Building initial guess...

..initialized CCSD in 0.305 seconds.

CCSD Iteration   0: CCSD correlation = -0.130904508474464   dE =  1.30905E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.148399055532320   dE = -1.74945E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.153560478518923   dE = -5.16142E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.156727263906044   dE = -3.16679E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.158017876899926   dE = -1.29061E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.158951712207641   dE = -9.33835E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.160282416035327   dE = -1.33070E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.161240376541914   dE = -9.57961E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.161649676267107   dE = -4.09300E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.161750262961034   dE = -1.00587E-04   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.161763946870759   dE = -1.36839E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.161766580084747   dE = -2.63321E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.161767861056415   dE = -1.28097E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.161768576457291   dE = -7.15401E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.161768913268086   dE = -3.36811E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.161769077829583   dE = -1.64561E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.161769186773919   dE = -1.08944E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.161769301624760   dE = -1.14851E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.161769426362725   dE = -1.24738E-07   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.161769571299313   dE = -1.44937E-07   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.161769680822892   dE = -1.09524E-07   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.161769713203202   dE = -3.23803E-08   DIIS = 7

CCSD has converged in 1.499 seconds!
converged SCF energy = -54.8653658017596
E(CCSD) = -55.02713553082824  E_corr = -0.1617697290686429
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.032 seconds.

CCSD Iteration   0: CCSD correlation = -0.044217490444022   dE =  4.42175E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.061637385061993   dE = -1.74199E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.071475602595048   dE = -9.83822E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.079189993094706   dE = -7.71439E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.084662905930048   dE = -5.47291E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.085875553294056   dE = -1.21265E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.086800287160570   dE = -9.24734E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.086638094225754   dE =  1.62193E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.086558516883270   dE =  7.95773E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.086621398656722   dE = -6.28818E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.086605225660583   dE =  1.61730E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.086614459566142   dE = -9.23391E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.086611063059028   dE =  3.39651E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.086610998346052   dE =  6.47130E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.086611558256642   dE = -5.59911E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.086611413064792   dE =  1.45192E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.086611374008393   dE =  3.90564E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.086611335813562   dE =  3.81948E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.086611329741514   dE =  6.07205E-09   DIIS = 7

CCSD has converged in 0.122 seconds!
converged SCF energy = -31.4753096751028
E(CCSD) = -31.56192098970947  E_corr = -0.08661131460665804
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.618 seconds.

CCSD Iteration   0: CCSD correlation = -0.065335902788366   dE =  6.53359E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.081822970229611   dE = -1.64871E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.088100119795280   dE = -6.27715E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.091799219900730   dE = -3.69910E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.093777545734849   dE = -1.97833E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.094822531490588   dE = -1.04499E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.095079758301956   dE = -2.57227E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.095099041714044   dE = -1.92834E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.095093735861644   dE =  5.30585E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.095137883842804   dE = -4.41480E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.095135302743553   dE =  2.58110E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.095135680697001   dE = -3.77953E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.095135064134374   dE =  6.16563E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.095134078316578   dE =  9.85818E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.095135356487464   dE = -1.27817E-06   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.095135541745042   dE = -1.85258E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.095135723834336   dE = -1.82089E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.095135652534051   dE =  7.13003E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.095135519570049   dE =  1.32964E-07   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.095135437325263   dE =  8.22448E-08   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.095135383548804   dE =  5.37765E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.095135364531441   dE =  1.90174E-08   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.095135371815169   dE = -7.28373E-09   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.095135374170506   dE = -2.35534E-09   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.095135375886836   dE = -1.71633E-09   DIIS = 7

CCSD has converged in 0.862 seconds!
converged SCF energy = -31.9526830379026
E(CCSD) = -32.04791502632962  E_corr = -0.09523198842702052
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.399 seconds.

CCSD Iteration   0: CCSD correlation = -0.067781476658122   dE =  6.77815E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.084307422470345   dE = -1.65259E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.090451618102025   dE = -6.14420E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.094104047973081   dE = -3.65243E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.095822865066022   dE = -1.71882E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.096771494790149   dE = -9.48630E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.097044715158637   dE = -2.73220E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.097098729092726   dE = -5.40139E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.097090445519764   dE =  8.28357E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.097121703605243   dE = -3.12581E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.097133546310786   dE = -1.18427E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.097132513664032   dE =  1.03265E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.097133140933842   dE = -6.27270E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.097129269613860   dE =  3.87132E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.097128451055137   dE =  8.18559E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.097127981612404   dE =  4.69443E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.097127754477651   dE =  2.27135E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.097127663730001   dE =  9.07476E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.097127535307074   dE =  1.28423E-07   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.097127395818466   dE =  1.39489E-07   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.097127306013371   dE =  8.98051E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.097127239806514   dE =  6.62069E-08   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.097127220501761   dE =  1.93048E-08   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.097127217433204   dE =  3.06856E-09   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.097127222320524   dE = -4.88732E-09   DIIS = 7
CCSD Iteration  25: CCSD correlation = -0.097127226056289   dE = -3.73576E-09   DIIS = 7
CCSD Iteration  26: CCSD correlation = -0.097127227568787   dE = -1.51250E-09   DIIS = 7

CCSD has converged in 2.760 seconds!
converged SCF energy = -31.9547919485978
E(CCSD) = -32.051970734401  E_corr = -0.09717878580324837
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 6 basis functions.
(6, 6)
(6, 6)
Building initial guess...

..initialized CCSD in 0.009 seconds.

CCSD Iteration   0: CCSD correlation = -0.017685146064346   dE =  1.76851E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.023233455903078   dE = -5.54831E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.025221898736036   dE = -1.98844E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.026418353290155   dE = -1.19645E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.026437479004237   dE = -1.91257E-05   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.026439848171469   dE = -2.36917E-06   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.026439549559911   dE =  2.98612E-07   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.026439630949488   dE = -8.13896E-08   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.026439606150873   dE =  2.47986E-08   DIIS = 7

CCSD has converged in 0.037 seconds!
converged SCF energy = -98.5715503330481
E(CCSD) = -98.5979899101155  E_corr = -0.02643957706742003
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 19 basis functions.
(19, 19)
(19, 19)
Building initial guess...

..initialized CCSD in 0.113 seconds.

CCSD Iteration   0: CCSD correlation = -0.204113016187579   dE =  2.04113E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.205700450275532   dE = -1.58743E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.208295648663307   dE = -2.59520E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.208797005406206   dE = -5.01357E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.209053661127873   dE = -2.56656E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.209062361023981   dE = -8.69990E-06   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.209063297278196   dE = -9.36254E-07   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.209063063999497   dE =  2.33279E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.209062943279460   dE =  1.20720E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.209062952972774   dE = -9.69331E-09   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.209062947618015   dE =  5.35476E-09   DIIS = 7

CCSD has converged in 0.103 seconds!
converged SCF energy = -100.019053852468
E(CCSD) = -100.2281168466598  E_corr = -0.2090629941918827
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 32 basis functions.
(32, 32)
(32, 32)
Building initial guess...

..initialized CCSD in 0.328 seconds.

CCSD Iteration   0: CCSD correlation = -0.225012308463486   dE =  2.25012E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.223500146172360   dE =  1.51216E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.227894291723581   dE = -4.39415E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.227901737120631   dE = -7.44540E-06   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.228424310115143   dE = -5.22573E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.228445844176192   dE = -2.15341E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.228444046932056   dE =  1.79724E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.228444420027071   dE = -3.73095E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.228444351861088   dE =  6.81660E-08   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.228444315833751   dE =  3.60273E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.228444326379494   dE = -1.05457E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.228444327181520   dE = -8.02027E-10   DIIS = 7

CCSD has converged in 1.588 seconds!
converged SCF energy = -100.033082435615
E(CCSD) = -100.2615267872045  E_corr = -0.228444351589065
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.019 seconds.

CCSD Iteration   0: CCSD correlation = -0.138082366856706   dE =  1.38082E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.111513405189107   dE =  2.65690E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.135787348784581   dE = -2.42739E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.127870769867647   dE =  7.91658E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.129960455845753   dE = -2.08969E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.132239511793270   dE = -2.27906E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.132369209197145   dE = -1.29697E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.132950512837676   dE = -5.81304E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.133203117758887   dE = -2.52605E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.133108634197330   dE =  9.44836E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.133124185749448   dE = -1.55516E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.133123097098831   dE =  1.08865E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.133121656100535   dE =  1.44100E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.133121812619984   dE = -1.56519E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.133121764454034   dE =  4.81659E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.133121762550081   dE =  1.90395E-09   DIIS = 7

CCSD has converged in 0.089 seconds!
converged SCF energy = -88.1813797930413
E(CCSD) = -88.31450159842085  E_corr = -0.1331218053795915
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.669 seconds.

CCSD Iteration   0: CCSD correlation = -0.247009672200278   dE =  2.47010E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.224758191517721   dE =  2.22515E-02   DIIS = 0

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:552: RuntimeWarning: divide by zero encountered in log10
  self.t2mag=np.log10(np.absolute(self.t2))

CCSD Iteration   2: CCSD correlation = -0.242341321791107   dE = -1.75831E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.238126920611718   dE =  4.21440E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.239623647504479   dE = -1.49673E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.240846112356744   dE = -1.22246E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.240950244241453   dE = -1.04132E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.241126262858956   dE = -1.76019E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.241238523909002   dE = -1.12261E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.241251222242491   dE = -1.26983E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.241250247605213   dE =  9.74637E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.241257978125492   dE = -7.73052E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.241256199983179   dE =  1.77814E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.241256333947709   dE = -1.33965E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.241256239774032   dE =  9.41737E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.241256291319872   dE = -5.15458E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.241256286747896   dE =  4.57198E-09   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.241256297601439   dE = -1.08535E-08   DIIS = 7

CCSD has converged in 2.342 seconds!
converged SCF energy = -89.4101339883117
E(CCSD) = -89.65142651419529  E_corr = -0.2412925258836156
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.661 seconds.

CCSD Iteration   0: CCSD correlation = -0.262780990400890   dE =  2.62781E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.240617941160366   dE =  2.21630E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.256976254161906   dE = -1.63583E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.253244182474878   dE =  3.73207E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.254453075116729   dE = -1.20889E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.255536079041692   dE = -1.08300E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.255630198159652   dE = -9.41191E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.255732251362360   dE = -1.02053E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.255821383976494   dE = -8.91326E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.255833479222193   dE = -1.20952E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.255833019980205   dE =  4.59242E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.255845317223851   dE = -1.22972E-05   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.255843527148352   dE =  1.79008E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.255844448810726   dE = -9.21662E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.255844388903353   dE =  5.99074E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.255844486633709   dE = -9.77304E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.255844520488695   dE = -3.38550E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.255844530743461   dE = -1.02548E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.255844545636181   dE = -1.48927E-08   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.255844549515361   dE = -3.87918E-09   DIIS = 7

CCSD has converged in 9.639 seconds!
converged SCF energy = -89.4193777147552
E(CCSD) = -89.67523224190721  E_corr = -0.2558545271520561
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.084 seconds.

CCSD Iteration   0: CCSD correlation = -0.016755973041712   dE =  1.67560E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.022607713804897   dE = -5.85174E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.025140752958183   dE = -2.53304E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.027557713644710   dE = -2.41696E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.028191600509153   dE = -6.33887E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.028292352790605   dE = -1.00752E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.028283569864343   dE =  8.78293E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.028281514941508   dE =  2.05492E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.028284908528108   dE = -3.39359E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.028284657966453   dE =  2.50562E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.028284725371017   dE = -6.74046E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.028284713973686   dE =  1.13973E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.028284721364374   dE = -7.39069E-09   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.028284720801418   dE =  5.62957E-10   DIIS = 7

CCSD has converged in 0.210 seconds!
converged SCF energy = -14.6386265804001
E(CCSD) = -14.6669113147904  E_corr = -0.02828473439029536
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 1.718 seconds.

CCSD Iteration   0: CCSD correlation = -0.019882261977721   dE =  1.98823E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.025763745804325   dE = -5.88148E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.028437328245442   dE = -2.67358E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.031022260131907   dE = -2.58493E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.031306629805519   dE = -2.84370E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.031436907176932   dE = -1.30277E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.031432466221386   dE =  4.44096E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.031429807792570   dE =  2.65843E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.031432442748998   dE = -2.63496E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.031431984096722   dE =  4.58652E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.031432087501308   dE = -1.03405E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.031432070368882   dE =  1.71324E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.031432094755156   dE = -2.43863E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.031432104990628   dE = -1.02355E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.031432106792212   dE = -1.80158E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.031432105788676   dE =  1.00354E-09   DIIS = 7

CCSD has converged in 0.539 seconds!
converged SCF energy = -14.8699493731253
E(CCSD) = -14.9013316303432  E_corr = -0.03138225721791545
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.616 seconds.

CCSD Iteration   0: CCSD correlation = -0.020237684834370   dE =  2.02377E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.025897224009518   dE = -5.65954E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.028540764161699   dE = -2.64354E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.031122348185661   dE = -2.58158E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.031393234799384   dE = -2.70887E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.031526586397197   dE = -1.33352E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.031534202283051   dE = -7.61589E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.031529661146197   dE =  4.54114E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.031531659713877   dE = -1.99857E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.031532011629416   dE = -3.51916E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.031532070893698   dE = -5.92643E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.031532002927204   dE =  6.79665E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.031531989717421   dE =  1.32098E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.031532008974612   dE = -1.92572E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.031532016821234   dE = -7.84662E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.031532019431534   dE = -2.61030E-09   DIIS = 7

CCSD has converged in 2.657 seconds!
converged SCF energy = -14.870266054773
E(CCSD) = -14.90183043707993  E_corr = -0.03156438230687635
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.055 seconds.

CCSD Iteration   0: CCSD correlation = -0.129076052603754   dE =  1.29076E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.122017677224833   dE =  7.05838E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.130657351805450   dE = -8.63967E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.130038463826139   dE =  6.18888E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.131213587591223   dE = -1.17512E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.131250444855493   dE = -3.68573E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.131261231921865   dE = -1.07871E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.131258198356257   dE =  3.03357E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.131258886326176   dE = -6.87970E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.131258815964961   dE =  7.03612E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.131258814155103   dE =  1.80986E-09   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.131258814677018   dE = -5.21915E-10   DIIS = 7

CCSD has converged in 0.130 seconds!
converged SCF energy = -111.224790358509
E(CCSD) = -111.3560492602827  E_corr = -0.1312589017739394
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.497 seconds.

CCSD Iteration   0: CCSD correlation = -0.291199715302716   dE =  2.91200E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.284720019206135   dE =  6.47970E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.297158590631484   dE = -1.24386E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.296591756075129   dE =  5.66835E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.298244230364411   dE = -1.65247E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.298360306582840   dE = -1.16076E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.298369924078359   dE = -9.61750E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.298372368397884   dE = -2.44432E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.298372234068945   dE =  1.34329E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.298372409083180   dE = -1.75014E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.298372420785597   dE = -1.17024E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.298372400415399   dE =  2.03702E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.298372400108484   dE =  3.06916E-10   DIIS = 7

CCSD has converged in 1.621 seconds!
converged SCF energy = -112.749075709252
E(CCSD) = -113.0474481272369  E_corr = -0.2983724179848097
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 2.122 seconds.

CCSD Iteration   0: CCSD correlation = -0.304422157886926   dE =  3.04422E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.296922982449636   dE =  7.49918E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.309741303390760   dE = -1.28183E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.309037732951105   dE =  7.03570E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.310731748609296   dE = -1.69402E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.310867205758936   dE = -1.35457E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.310876446188268   dE = -9.24043E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.310879412224353   dE = -2.96604E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.310879256554979   dE =  1.55669E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.310879432364074   dE = -1.75809E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.310879540397244   dE = -1.08033E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.310879465050886   dE =  7.53464E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.310879454492879   dE =  1.05580E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.310879448894190   dE =  5.59869E-09   DIIS = 7

CCSD has converged in 2.596 seconds!
converged SCF energy = -112.754496533042
E(CCSD) = -113.0653760156844  E_corr = -0.3108794826425704
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.033 seconds.

CCSD Iteration   0: CCSD correlation = -0.246176177045906   dE =  2.46176E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.197944400802151   dE =  4.82318E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.233312974086074   dE = -3.53686E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.232014372389447   dE =  1.29860E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.248943160633824   dE = -1.69288E-02   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.253193766705557   dE = -4.25061E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.252793628489973   dE =  4.00138E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.253803346815572   dE = -1.00972E-03   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.253355474834284   dE =  4.47872E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.253472428043460   dE = -1.16953E-04   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.253488014723137   dE = -1.55867E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.253486226703003   dE =  1.78802E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.253486021201194   dE =  2.05502E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.253485831868213   dE =  1.89333E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.253485808848838   dE =  2.30194E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.253485821903048   dE = -1.30542E-08   DIIS = 7

CCSD has converged in 0.142 seconds!
converged SCF energy = -74.4209992122191
E(CCSD) = -74.67448546934514  E_corr = -0.2534862571260514
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.500 seconds.

CCSD Iteration   0: CCSD correlation = -0.315804352682120   dE =  3.15804E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.271427064844400   dE =  4.43773E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.310493944993932   dE = -3.90669E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.304863834173649   dE =  5.63011E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.313796044168935   dE = -8.93221E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.315794761836495   dE = -1.99872E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.315892267017949   dE = -9.75052E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.316001245242410   dE = -1.08978E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.316009407718265   dE = -8.16248E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.316003588529936   dE =  5.81919E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.316015917115337   dE = -1.23286E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.316015069323623   dE =  8.47792E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.316014734583892   dE =  3.34740E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.316014447078903   dE =  2.87505E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.316014490157731   dE = -4.30788E-08   DIIS = 7

CCSD has converged in 1.512 seconds!
converged SCF energy = -75.3869924906461
E(CCSD) = -75.70300695503904  E_corr = -0.3160144643929769
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.277 seconds.

CCSD Iteration   0: CCSD correlation = -0.321649488837281   dE =  3.21649E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.276355275197918   dE =  4.52942E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.315758324454495   dE = -3.94030E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.309907938814249   dE =  5.85039E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.318715517659192   dE = -8.80758E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.320587619193215   dE = -1.87210E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.320768756491594   dE = -1.81137E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.320852084838536   dE = -8.33283E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.320869049339847   dE = -1.69645E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.320858197388590   dE =  1.08520E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.320871268168700   dE = -1.30708E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.320871563259124   dE = -2.95090E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.320871887746828   dE = -3.24488E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.320871200046664   dE =  6.87700E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.320871205683179   dE = -5.63651E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.320871211989098   dE = -6.30592E-09   DIIS = 7

CCSD has converged in 10.187 seconds!
converged SCF energy = -75.3883231883779
E(CCSD) = -75.70919434851322  E_corr = -0.3208711601352769
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.031 seconds.

CCSD Iteration   0: CCSD correlation = -0.155061420630924   dE =  1.55061E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.148170615574892   dE =  6.89081E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.151591272068594   dE = -3.42066E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.152603974293334   dE = -1.01270E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.153645400039369   dE = -1.04143E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.153808865037418   dE = -1.63465E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.153803728829191   dE =  5.13621E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.153806755691138   dE = -3.02686E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.153806524231531   dE =  2.31460E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.153806586918892   dE = -6.26874E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.153806589737243   dE = -2.81835E-09   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.153806593131858   dE = -3.39462E-09   DIIS = 7

CCSD has converged in 0.065 seconds!
converged SCF energy = -107.496598623389
E(CCSD) = -107.6504052261533  E_corr = -0.1538066027647601
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.502 seconds.

CCSD Iteration   0: CCSD correlation = -0.311401066722719   dE =  3.11401E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.300023983905853   dE =  1.13771E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.312344047031149   dE = -1.23201E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.312160561080525   dE =  1.83486E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.313573900545840   dE = -1.41334E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.313669875533362   dE = -9.59750E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.313680098452294   dE = -1.02229E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.313679236168220   dE =  8.62284E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.313679359672871   dE = -1.23505E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.313679346821920   dE =  1.28510E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.313679347744688   dE = -9.22768E-10   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.313679349051943   dE = -1.30726E-09   DIIS = 7

CCSD has converged in 0.898 seconds!
converged SCF energy = -108.953737019543
E(CCSD) = -109.2674163404626  E_corr = -0.3136793209193935
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.185 seconds.

CCSD Iteration   0: CCSD correlation = -0.322730598542257   dE =  3.22731E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.310347010768059   dE =  1.23836E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.323205121456132   dE = -1.28581E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.322973960040149   dE =  2.31161E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.324516416282276   dE = -1.54246E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.324623730198679   dE = -1.07314E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.324638449829896   dE = -1.47196E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.324639100651161   dE = -6.50821E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.324639184167894   dE = -8.35167E-08   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.324639238473367   dE = -5.43055E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.324639238097231   dE =  3.76136E-10   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.324639227448844   dE =  1.06484E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.324639230752117   dE = -3.30327E-09   DIIS = 7

CCSD has converged in 2.314 seconds!
converged SCF energy = -108.960279009454
E(CCSD) = -109.2849182193981  E_corr = -0.32463920994388
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.037 seconds.

CCSD Iteration   0: CCSD correlation = -0.051387490747396   dE =  5.13875E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.076703510863994   dE = -2.53160E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.089685611311063   dE = -1.29821E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.103092414576999   dE = -1.34068E-02   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.102393902444938   dE =  6.98512E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.103004060916930   dE = -6.10158E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.103214310896379   dE = -2.10250E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.103025773523222   dE =  1.88537E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.103123303111865   dE = -9.75296E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.103102384123315   dE =  2.09190E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.103106912249699   dE = -4.52813E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.103107132071249   dE = -2.19822E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.103107231325609   dE = -9.92544E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.103107202712972   dE =  2.86126E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.103107185867472   dE =  1.68455E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.103107193351539   dE = -7.48407E-09   DIIS = 7

CCSD has converged in 0.118 seconds!
converged SCF energy = -28.6999769940247
E(CCSD) = -28.80308420225191  E_corr = -0.103107208227184
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.882 seconds.

CCSD Iteration   0: CCSD correlation = -0.062780627615711   dE =  6.27806E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.081397791103988   dE = -1.86172E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.089133974826785   dE = -7.73618E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.096179396579097   dE = -7.04542E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.097523428696921   dE = -1.34403E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.097871165687576   dE = -3.47737E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.097881779516145   dE = -1.06138E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.097836897298620   dE =  4.48822E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.097873551405876   dE = -3.66541E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.097860103579212   dE =  1.34478E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.097861754037082   dE = -1.65046E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.097862119721647   dE = -3.65685E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.097862188745250   dE = -6.90236E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.097862167752238   dE =  2.09930E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.097862190461459   dE = -2.27092E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.097862190853032   dE = -3.91574E-10   DIIS = 7

CCSD has converged in 1.017 seconds!
converged SCF energy = -29.1336213261561
E(CCSD) = -29.23147682514339  E_corr = -0.09785549898729019
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.693 seconds.

CCSD Iteration   0: CCSD correlation = -0.063557866101797   dE =  6.35579E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.081858402646960   dE = -1.83005E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.089487012267800   dE = -7.62861E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.096431537431876   dE = -6.94453E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.097806406710527   dE = -1.37487E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.098185740809630   dE = -3.79334E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.098205810346876   dE = -2.00695E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.098163477526019   dE =  4.23328E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.098188473459292   dE = -2.49959E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.098184526829439   dE =  3.94663E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.098184448263911   dE =  7.85655E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.098184280037703   dE =  1.68226E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.098184767440679   dE = -4.87403E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.098184837711516   dE = -7.02708E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.098184785368658   dE =  5.23429E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.098184772519550   dE =  1.28491E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.098184778308664   dE = -5.78911E-09   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.098184783499128   dE = -5.19046E-09   DIIS = 7

CCSD has converged in 1.951 seconds!
converged SCF energy = -29.1339934316104
E(CCSD) = -29.23215572123847  E_corr = -0.09816228962807724
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.026 seconds.

CCSD Iteration   0: CCSD correlation = -0.109723428580377   dE =  1.09723E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.116183852682722   dE = -6.46042E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.132916205919195   dE = -1.67324E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.133392198362144   dE = -4.75992E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.142226966592030   dE = -8.83477E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.143729821799765   dE = -1.50286E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.144167215021866   dE = -4.37393E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.144194523941067   dE = -2.73089E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.144163665215960   dE =  3.08587E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.144207153848214   dE = -4.34886E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.144204055402833   dE =  3.09845E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.144206667449127   dE = -2.61205E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.144226719904342   dE = -2.00525E-05   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.144224890343178   dE =  1.82956E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.144224577181893   dE =  3.13161E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.144222120674363   dE =  2.45651E-06   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.144221228302032   dE =  8.92372E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.144221125874703   dE =  1.02427E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.144221263144793   dE = -1.37270E-07   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.144221354056760   dE = -9.09120E-08   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.144221377676359   dE = -2.36196E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.144221374027598   dE =  3.64876E-09   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.144221367630104   dE =  6.39749E-09   DIIS = 7

CCSD has converged in 0.120 seconds!
converged SCF energy = -51.4797510790213
E(CCSD) = -51.62397256866348  E_corr = -0.1442214896422017
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.612 seconds.

CCSD Iteration   0: CCSD correlation = -0.151994469815007   dE =  1.51994E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.160870592904509   dE = -8.87612E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.172882968895743   dE = -1.20124E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.173227670514011   dE = -3.44702E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.178759185752950   dE = -5.53152E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.179697673611172   dE = -9.38488E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.180056707066429   dE = -3.59033E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.180245723607502   dE = -1.89017E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.180224273167754   dE =  2.14504E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.180354064489284   dE = -1.29791E-04   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.180355622467006   dE = -1.55798E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.180367789520755   dE = -1.21671E-05   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.180373839978334   dE = -6.05046E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.180372062932465   dE =  1.77705E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.180372498074496   dE = -4.35142E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.180372300306095   dE =  1.97768E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.180372547391015   dE = -2.47085E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.180372514394033   dE =  3.29970E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.180372487815192   dE =  2.65788E-08   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.180372265717948   dE =  2.22097E-07   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.180372175747735   dE =  8.99702E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.180372060474170   dE =  1.15274E-07   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.180372029662128   dE =  3.08120E-08   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.180372022123316   dE =  7.53881E-09   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.180372024026247   dE = -1.90293E-09   DIIS = 7
CCSD Iteration  25: CCSD correlation = -0.180372026102393   dE = -2.07615E-09   DIIS = 7

CCSD has converged in 1.585 seconds!
converged SCF energy = -52.2009029384354
E(CCSD) = -52.38129977929317  E_corr = -0.180396840857808
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.412 seconds.

CCSD Iteration   0: CCSD correlation = -0.156070073208442   dE =  1.56070E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.165198082349102   dE = -9.12801E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.176593394574400   dE = -1.13953E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.176966261139884   dE = -3.72867E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.182240156947090   dE = -5.27390E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.183251098073517   dE = -1.01094E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.183560133596816   dE = -3.09036E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.183752090200581   dE = -1.91957E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.183745095981311   dE =  6.99422E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.183844157993590   dE = -9.90620E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.183880042068441   dE = -3.58841E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.183888007451650   dE = -7.96538E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.183896903013944   dE = -8.89556E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.183887160705595   dE =  9.74231E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.183887057942657   dE =  1.02763E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.183886013771953   dE =  1.04417E-06   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.183886085686284   dE = -7.19143E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.183886294339934   dE = -2.08654E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.183886156350308   dE =  1.37990E-07   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.183885884116073   dE =  2.72234E-07   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.183885785329316   dE =  9.87868E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.183885541970771   dE =  2.43359E-07   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.183885433249807   dE =  1.08721E-07   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.183885353844894   dE =  7.94049E-08   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.183885347255896   dE =  6.58900E-09   DIIS = 7
CCSD Iteration  25: CCSD correlation = -0.183885350285127   dE = -3.02923E-09   DIIS = 7
CCSD Iteration  26: CCSD correlation = -0.183885351699746   dE = -1.41462E-09   DIIS = 7
CCSD Iteration  27: CCSD correlation = -0.183885355517423   dE = -3.81768E-09   DIIS = 7
CCSD Iteration  28: CCSD correlation = -0.183885358948934   dE = -3.43151E-09   DIIS = 7

CCSD has converged in 4.897 seconds!
converged SCF energy = -52.2046392142157
E(CCSD) = -52.38856805556802  E_corr = -0.1839288413523453
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 6 basis functions.
(6, 6)
(6, 6)
Building initial guess...

..initialized CCSD in 0.020 seconds.

CCSD Iteration   0: CCSD correlation = -0.012820234508819   dE =  1.28202E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.017233719593113   dE = -4.41349E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.018915463053995   dE = -1.68174E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.020021797559389   dE = -1.10633E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.020218432015929   dE = -1.96634E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.020281103576966   dE = -6.26716E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.020276708358629   dE =  4.39522E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.020275843069931   dE =  8.65289E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.020275917484958   dE = -7.44150E-08   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.020275918899704   dE = -1.41475E-09   DIIS = 7

CCSD has converged in 0.081 seconds!

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:552: RuntimeWarning: divide by zero encountered in log10
  self.t2mag=np.log10(np.absolute(self.t2))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:593: RuntimeWarning: divide by zero encountered in log10
  self.Jia1mag=np.log10(np.absolute(self.Jia1))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:594: RuntimeWarning: divide by zero encountered in log10
  self.Jia2mag=np.log10(np.absolute(self.Jia2))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:595: RuntimeWarning: divide by zero encountered in log10
  self.Kia1mag=np.log10(np.absolute(self.Kia1))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:596: RuntimeWarning: divide by zero encountered in log10
  self.Kia2mag=np.log10(np.absolute(self.Kia2))

converged SCF energy = -7.86219514126873
E(CCSD) = -7.882471061194734  E_corr = -0.02027591992600007
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 19 basis functions.
(19, 19)
(19, 19)
Building initial guess...

..initialized CCSD in 0.175 seconds.

CCSD Iteration   0: CCSD correlation = -0.022764066090049   dE =  2.27641E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.028298150022826   dE = -5.53408E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.029998340875171   dE = -1.70019E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.030875361651751   dE = -8.77021E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.030979111487165   dE = -1.03750E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.031026301230377   dE = -4.71897E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.031025193226698   dE =  1.10800E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.031024679417992   dE =  5.13809E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.031025698572869   dE = -1.01915E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.031025858246408   dE = -1.59674E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.031025851155299   dE =  7.09111E-09   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.031025843758837   dE =  7.39646E-09   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.031025842821816   dE =  9.37021E-10   DIIS = 7

CCSD has converged in 0.111 seconds!
converged SCF energy = -7.98357803827267
E(CCSD) = -8.014686914906243  E_corr = -0.03110887663357371
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 32 basis functions.
(32, 32)
(32, 32)
Building initial guess...

..initialized CCSD in 0.385 seconds.

CCSD Iteration   0: CCSD correlation = -0.027610073540819   dE =  2.76101E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.034036730042852   dE = -6.42666E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.035997044040125   dE = -1.96031E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.036987089722842   dE = -9.90046E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.037056489144086   dE = -6.93994E-05   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.037092827664713   dE = -3.63385E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.037095875477339   dE = -3.04781E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.037094922652817   dE =  9.52825E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.037095341438015   dE = -4.18785E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.037095612923987   dE = -2.71486E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.037095637521559   dE = -2.45976E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.037095626140361   dE =  1.13812E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.037095611013123   dE =  1.51272E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.037095603585039   dE =  7.42808E-09   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.037095601691140   dE =  1.89390E-09   DIIS = 7

CCSD has converged in 0.453 seconds!
converged SCF energy = -7.98411790924306
E(CCSD) = -8.021230413622659  E_corr = -0.03711250437959424
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.027 seconds.

CCSD Iteration   0: CCSD correlation = -0.134528523262270   dE =  1.34529E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.148574891096501   dE = -1.40464E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.163585234029586   dE = -1.50103E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.170287766935894   dE = -6.70253E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.179572402048287   dE = -9.28464E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.182756520770729   dE = -3.18412E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.183019942079467   dE = -2.63421E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.183325442589060   dE = -3.05501E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.183167629114099   dE =  1.57813E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.183190397500434   dE = -2.27684E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.183206542006446   dE = -1.61445E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.183189195510803   dE =  1.73465E-05   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.183192374232483   dE = -3.17872E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.183188013937725   dE =  4.36029E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.183189610134538   dE = -1.59620E-06   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.183193807855887   dE = -4.19772E-06   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.183194945487188   dE = -1.13763E-06   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.183195143922664   dE = -1.98435E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.183195140345559   dE =  3.57711E-09   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.183195118867430   dE =  2.14781E-08   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.183195084812340   dE =  3.40551E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.183195059626257   dE =  2.51861E-08   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.183195061300321   dE = -1.67406E-09   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.183195068720973   dE = -7.42065E-09   DIIS = 7

CCSD has converged in 0.109 seconds!
converged SCF energy = -48.2917153783531
E(CCSD) = -48.47491052730417  E_corr = -0.1831951489510539
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.467 seconds.

CCSD Iteration   0: CCSD correlation = -0.156321957243276   dE =  1.56322E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.171259108793283   dE = -1.49372E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.183137687069503   dE = -1.18786E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.187035384313976   dE = -3.89770E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.192022486230531   dE = -4.98710E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.193518698867846   dE = -1.49621E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.193666512290185   dE = -1.47813E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.193764899193172   dE = -9.83869E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.193742398367041   dE =  2.25008E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.193752991262113   dE = -1.05929E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.193748528213754   dE =  4.46305E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.193749312943278   dE = -7.84730E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.193748251526698   dE =  1.06142E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.193751085478540   dE = -2.83395E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.193751550452283   dE = -4.64974E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.193752355351306   dE = -8.04899E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.193752294729843   dE =  6.06215E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.193752203688051   dE =  9.10418E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.193752119904284   dE =  8.37838E-08   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.193752111456786   dE =  8.44750E-09   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.193752125114776   dE = -1.36580E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.193752135135891   dE = -1.00211E-08   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.193752145901498   dE = -1.07656E-08   DIIS = 7

CCSD has converged in 1.002 seconds!
converged SCF energy = -49.0379954742015
E(CCSD) = -49.2317474900361  E_corr = -0.1937520158346385
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.107 seconds.

CCSD Iteration   0: CCSD correlation = -0.158993119349629   dE =  1.58993E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.173591755917359   dE = -1.45986E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.185407733425098   dE = -1.18160E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.189198682565790   dE = -3.79095E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.194253114715761   dE = -5.05443E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.195687141587747   dE = -1.43403E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.195864602027869   dE = -1.77460E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.195955885799294   dE = -9.12838E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.195944701491871   dE =  1.11843E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.195946928768011   dE = -2.22728E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.195945349468414   dE =  1.57930E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.195943460581868   dE =  1.88889E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.195942988566881   dE =  4.72015E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.195945904725759   dE = -2.91616E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.195947436332685   dE = -1.53161E-06   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.195948216518156   dE = -7.80185E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.195948113267980   dE =  1.03250E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.195947936743295   dE =  1.76525E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.195947865522520   dE =  7.12208E-08   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.195947882275796   dE = -1.67533E-08   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.195947946901594   dE = -6.46258E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.195947976219138   dE = -2.93175E-08   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.195947992966559   dE = -1.67474E-08   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.195947999316757   dE = -6.35020E-09   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.195947999499563   dE = -1.82806E-10   DIIS = 7

CCSD has converged in 3.547 seconds!
converged SCF energy = -49.0388850965103
E(CCSD) = -49.23483308566859  E_corr = -0.1959479891583331
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.025 seconds.

CCSD Iteration   0: CCSD correlation = -0.058721862610023   dE =  5.87219E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.041382132054922   dE =  1.73397E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.061662953102057   dE = -2.02808E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.052968685857909   dE =  8.69427E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.054963052237601   dE = -1.99437E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.054965310778878   dE = -2.25854E-06   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.054774238015168   dE =  1.91073E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.054834545238258   dE = -6.03072E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.054890045593404   dE = -5.55004E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.054870639918379   dE =  1.94057E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.054867685710116   dE =  2.95421E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.054867599259140   dE =  8.64510E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.054867430167978   dE =  1.69091E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.054867458088457   dE = -2.79205E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.054867516378343   dE = -5.82899E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.054867514282849   dE =  2.09549E-09   DIIS = 7

CCSD has converged in 0.100 seconds!
converged SCF energy = -105.366240701175
E(CCSD) = -105.4211082997688  E_corr = -0.05486759859400393
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.619 seconds.

CCSD Iteration   0: CCSD correlation = -0.209163216327057   dE =  2.09163E-01   MP2

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:552: RuntimeWarning: divide by zero encountered in log10
  self.t2mag=np.log10(np.absolute(self.t2))

CCSD Iteration   1: CCSD correlation = -0.203616867668166   dE =  5.54635E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.208892195457758   dE = -5.27533E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.208389439872905   dE =  5.02756E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.209058231416232   dE = -6.68792E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.209191701980716   dE = -1.33471E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.209180623295870   dE =  1.10787E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.209177006581414   dE =  3.61671E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.209178028908306   dE = -1.02233E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.209178216307402   dE = -1.87399E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.209178165043681   dE =  5.12637E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.209178521263384   dE = -3.56220E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.209178455596808   dE =  6.56666E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.209178480361245   dE = -2.47644E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.209178478536753   dE =  1.82449E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.209178474066574   dE =  4.47018E-09   DIIS = 7

CCSD has converged in 2.445 seconds!
converged SCF energy = -106.944300345455
E(CCSD) = -107.1534253193619  E_corr = -0.2091249739070332
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.426 seconds.

CCSD Iteration   0: CCSD correlation = -0.237048300110736   dE =  2.37048E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.230940491631633   dE =  6.10781E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.237296979923087   dE = -6.35649E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.236499191763548   dE =  7.97788E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.237125456070773   dE = -6.26264E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.237246315175259   dE = -1.20859E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.237237519320632   dE =  8.79585E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.237235254742455   dE =  2.26458E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.237236416570866   dE = -1.16183E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.237236467327493   dE = -5.07566E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.237236422168714   dE =  4.51588E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.237236633960626   dE = -2.11792E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.237236620619880   dE =  1.33407E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.237236641065481   dE = -2.04456E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.237236647702868   dE = -6.63739E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.237236645049341   dE =  2.65353E-09   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.237236644166329   dE =  8.83012E-10   DIIS = 7

CCSD has converged in 2.222 seconds!
converged SCF energy = -106.956450680255
E(CCSD) = -107.193679735539  E_corr = -0.2372290552839474
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.027 seconds.

CCSD Iteration   0: CCSD correlation = -0.062872574118442   dE =  6.28726E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.070353433926117   dE = -7.48086E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.078016586568328   dE = -7.66315E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.079429032882395   dE = -1.41245E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.081962683315215   dE = -2.53365E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.082574932114096   dE = -6.12249E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.083443392666447   dE = -8.68461E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.084930684578395   dE = -1.48729E-03   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.086715461279610   dE = -1.78478E-03   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.087003784625847   dE = -2.88323E-04   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.086990274376204   dE =  1.35102E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.087024794800487   dE = -3.45204E-05   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.087018771807478   dE =  6.02299E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.087020891307412   dE = -2.11950E-06   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.087020454375219   dE =  4.36932E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.087020893846808   dE = -4.39472E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.087020866878560   dE =  2.69682E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.087020930302571   dE = -6.34240E-08   DIIS = 7

CCSD has converged in 0.085 seconds!
converged SCF energy = -151.620132629919

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:552: RuntimeWarning: divide by zero encountered in log10
  self.t2mag=np.log10(np.absolute(self.t2))

E(CCSD) = -151.7071535432611  E_corr = -0.08702091334223425
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.461 seconds.

CCSD Iteration   0: CCSD correlation = -0.320229441356388   dE =  3.20229E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.322908064970528   dE = -2.67862E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.336322875067375   dE = -1.34148E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.336075643470081   dE =  2.47232E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.339244734591510   dE = -3.16909E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.339979448418590   dE = -7.34714E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.340415897215064   dE = -4.36449E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.340966813335039   dE = -5.50916E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.341157740580964   dE = -1.90927E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.341237529000741   dE = -7.97884E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.341236643381954   dE =  8.85619E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.341226651098141   dE =  9.99228E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.341230176903392   dE = -3.52581E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.341229583321340   dE =  5.93582E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.341229892488894   dE = -3.09168E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.341230007924744   dE = -1.15436E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.341230014913149   dE = -6.98840E-09   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.341230006308701   dE =  8.60445E-09   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.341229992253408   dE =  1.40553E-08   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.341229974937280   dE =  1.73161E-08   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.341229957305242   dE =  1.76320E-08   DIIS = 7

CCSD has converged in 1.175 seconds!
converged SCF energy = -153.684565437666
E(CCSD) = -154.0257960397303  E_corr = -0.3412306020641342
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.147 seconds.

CCSD Iteration   0: CCSD correlation = -0.342936488976437   dE =  3.42936E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.343994761534680   dE = -1.05827E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.358853418613963   dE = -1.48587E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.358302855342984   dE =  5.50563E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.361597413279009   dE = -3.29456E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.362365295436188   dE = -7.67882E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.362784330518863   dE = -4.19035E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.363218871321225   dE = -4.34541E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.363438513828156   dE = -2.19643E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.363512673040467   dE = -7.41592E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.363520058803233   dE = -7.38576E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.363508684793338   dE =  1.13740E-05   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.363511854943303   dE = -3.17015E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.363510909727232   dE =  9.45216E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.363511137452879   dE = -2.27726E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.363511199685574   dE = -6.22327E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.363511217001300   dE = -1.73157E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.363511199230297   dE =  1.77710E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.363511184926738   dE =  1.43036E-08   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.363511150768731   dE =  3.41580E-08   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.363511119498782   dE =  3.12699E-08   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.363511101816261   dE =  1.76825E-08   DIIS = 7

CCSD has converged in 4.481 seconds!
converged SCF energy = -153.697338261765
E(CCSD) = -154.0608494325833  E_corr = -0.3635111708187024
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 6 basis functions.
(6, 6)
(6, 6)
Building initial guess...

..initialized CCSD in 0.008 seconds.

CCSD Iteration   0: CCSD correlation = -0.029748201729273   dE =  2.97482E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.043002520136006   dE = -1.32543E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.049617238414656   dE = -6.61472E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.057164134109537   dE = -7.54690E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.057281810609263   dE = -1.17676E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.057470870184663   dE = -1.89060E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.057393688166229   dE =  7.71820E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.057413994047722   dE = -2.03059E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.057411743687210   dE =  2.25036E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.057412100266787   dE = -3.56580E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.057412076129854   dE =  2.41369E-08   DIIS = 7

CCSD has converged in 0.046 seconds!
converged SCF energy = -24.7524640061769
E(CCSD) = -24.80987609041853  E_corr = -0.05741208424164231
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 19 basis functions.
(19, 19)
(19, 19)
Building initial guess...

..initialized CCSD in 0.102 seconds.

CCSD Iteration   0: CCSD correlation = -0.061875485290270   dE =  6.18755E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.078327398104860   dE = -1.64519E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.083937621390834   dE = -5.61022E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.088182257281903   dE = -4.24464E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.089095981641365   dE = -9.13724E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.089177725125100   dE = -8.17435E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.089139467290205   dE =  3.82578E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.089154566009229   dE = -1.50987E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.089156114505947   dE = -1.54850E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.089154958491677   dE =  1.15601E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.089154992446764   dE = -3.39551E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.089155031365024   dE = -3.89183E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.089155019291809   dE =  1.20732E-08   DIIS = 7

CCSD has converged in 0.104 seconds!
converged SCF energy = -25.1253095421762
E(CCSD) = -25.21446466424177  E_corr = -0.08915512206558958
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 32 basis functions.
(32, 32)
(32, 32)
Building initial guess...

..initialized CCSD in 0.264 seconds.

CCSD Iteration   0: CCSD correlation = -0.063904819411726   dE =  6.39048E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.080393689571977   dE = -1.64889E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.085994017453615   dE = -5.60033E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.090209678083186   dE = -4.21566E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.091110636541293   dE = -9.00958E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.091211450751028   dE = -1.00814E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.091197485893644   dE =  1.39649E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.091194936941974   dE =  2.54895E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.091200634595917   dE = -5.69765E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.091199845507463   dE =  7.89088E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.091199657640025   dE =  1.87867E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.091199596634906   dE =  6.10051E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.091199643298399   dE = -4.66635E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.091199654461903   dE = -1.11635E-08   DIIS = 7

CCSD has converged in 0.508 seconds!
converged SCF energy = -25.1263766457167
E(CCSD) = -25.21757628976743  E_corr = -0.09119964405077641
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.023 seconds.

CCSD Iteration   0: CCSD correlation = -0.123119239540758   dE =  1.23119E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.133494305115205   dE = -1.03751E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.136817910002207   dE = -3.32360E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.139770260223673   dE = -2.95235E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.140629377935281   dE = -8.59118E-04   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.140771696096955   dE = -1.42318E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.141935192400075   dE = -1.16350E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.142464884143702   dE = -5.29692E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.142479014726897   dE = -1.41306E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.142508391363903   dE = -2.93766E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.142500616499538   dE =  7.77486E-06   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.142502611658160   dE = -1.99516E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.142502963475877   dE = -3.51818E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.142502978417539   dE = -1.49417E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.142502972041345   dE =  6.37619E-09   DIIS = 7

CCSD has converged in 0.060 seconds!
converged SCF energy = -147.550568009312
E(CCSD) = -147.6930709994964  E_corr = -0.1425029901844091
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.493 seconds.

CCSD Iteration   0: CCSD correlation = -0.379714902989892   dE =  3.79715E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.363858907225847   dE =  1.58560E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.379762281472149   dE = -1.59034E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.379263468424174   dE =  4.98813E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.381466737293033   dE = -2.20327E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.381688608498256   dE = -2.21871E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.381845230651009   dE = -1.56622E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.381948185893864   dE = -1.02955E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.381976411055322   dE = -2.82252E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.381977430311758   dE = -1.01926E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.381977902352575   dE = -4.72041E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.381978030413320   dE = -1.28061E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.381978089759100   dE = -5.93458E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.381978096750767   dE = -6.99167E-09   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.381978105824521   dE = -9.07375E-09   DIIS = 7

CCSD has converged in 1.973 seconds!
converged SCF energy = -149.5440130236
E(CCSD) = -149.9259912352559  E_corr = -0.3819782116555602
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.250 seconds.

CCSD Iteration   0: CCSD correlation = -0.398983730656403   dE =  3.98984E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.381311874098355   dE =  1.76719E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.398709020112950   dE = -1.73971E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.397994678748490   dE =  7.14341E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.400456102776978   dE = -2.46142E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.400684953181225   dE = -2.28850E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.400811065900025   dE = -1.26113E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.400906820372511   dE = -9.57545E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.400936813178066   dE = -2.99928E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.400941016423855   dE = -4.20325E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.400941609362624   dE = -5.92939E-07   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.400941192453134   dE =  4.16909E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.400941389668103   dE = -1.97215E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.400941332281003   dE =  5.73871E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.400941327657967   dE =  4.62304E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.400941327695627   dE = -3.76597E-11   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.400941326340699   dE =  1.35493E-09   DIIS = 7

CCSD has converged in 2.181 seconds!
converged SCF energy = -149.557602796943
E(CCSD) = -149.9585441862423  E_corr = -0.4009413892991344
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.023 seconds.

CCSD Iteration   0: CCSD correlation = -0.062742484278416   dE =  6.27425E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.066499109717105   dE = -3.75663E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.075511302912676   dE = -9.01219E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.076093217885451   dE = -5.81915E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.078622726840779   dE = -2.52951E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.078599595993895   dE =  2.31308E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.078633976462764   dE = -3.43805E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.078624933957708   dE =  9.04251E-06   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.078625144273002   dE = -2.10315E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.078625322204206   dE = -1.77931E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.078625310413526   dE =  1.17907E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.078625309267788   dE =  1.14574E-09   DIIS = 7

CCSD has converged in 0.077 seconds!
converged SCF energy = -122.355507259078
E(CCSD) = -122.4341325720865  E_corr = -0.0786253130086591
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.472 seconds.

CCSD Iteration   0: CCSD correlation = -0.253687312540370   dE =  2.53687E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.257054441929049   dE = -3.36713E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.266336705419638   dE = -9.28226E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.267163515990348   dE = -8.26811E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.269265850806771   dE = -2.10233E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.269360065834162   dE = -9.42150E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.269361546298106   dE = -1.48046E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.269361236568594   dE =  3.09730E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.269359738429680   dE =  1.49814E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.269359867522733   dE = -1.29093E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.269359869870623   dE = -2.34789E-09   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.269359858850339   dE =  1.10203E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.269359854438474   dE =  4.41186E-09   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.269359848738116   dE =  5.70036E-09   DIIS = 7

CCSD has converged in 0.839 seconds!
converged SCF energy = -124.107544895386
E(CCSD) = -124.3769047254206  E_corr = -0.2693598300345387
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.145 seconds.

CCSD Iteration   0: CCSD correlation = -0.269809633652083   dE =  2.69810E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.272358846119709   dE = -2.54921E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.282028648132523   dE = -9.66980E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.282645510011733   dE = -6.16862E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.284833005131326   dE = -2.18750E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.284943283051161   dE = -1.10278E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.284944835165381   dE = -1.55211E-06   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.284944349839918   dE =  4.85325E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.284942905255849   dE =  1.44458E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.284942851560944   dE =  5.36949E-08   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.284942894029015   dE = -4.24681E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.284942933003142   dE = -3.89741E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.284942914033726   dE =  1.89694E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.284942904930649   dE =  9.10308E-09   DIIS = 7

CCSD has converged in 1.863 seconds!
converged SCF energy = -124.115034914325
E(CCSD) = -124.3999778020806  E_corr = -0.284942887755907
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 2 basis functions.
(2, 2)
(2, 2)
Building initial guess...

..initialized CCSD in 0.009 seconds.

CCSD Iteration   0: CCSD correlation = -0.013634166972161   dE =  1.36342E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.018648738994972   dE = -5.01457E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.020454743156119   dE = -1.80600E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.021462221037727   dE = -1.00748E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.021462221037727   dE =  0.00000E+00   DIIS = 3
converged SCF energy = -1.11530095740978
E(CCSD) = -1.136758365213703  E_corr = -0.02145740780392735
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.011 seconds.

CCSD Iteration   0: CCSD correlation = -0.026560109895749   dE =  2.65601E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.032557535204071   dE = -5.99743E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.034211167891435   dE = -1.65363E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.034990432339510   dE = -7.79264E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.035044207469183   dE = -5.37751E-05   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.035044436923669   dE = -2.29454E-07   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.035044121507297   dE =  3.15416E-07   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.035044186855145   dE = -6.53478E-08   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.035044172799406   dE =  1.40557E-08   DIIS = 7

CCSD has converged in 0.043 seconds!
converged SCF energy = -1.1286288045752

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:552: RuntimeWarning: divide by zero encountered in log10
  self.t2mag=np.log10(np.absolute(self.t2))

E(CCSD) = -1.163672986852609  E_corr = -0.03504418227740903
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 18 basis functions.
(18, 18)
(18, 18)
Building initial guess...

..initialized CCSD in 0.027 seconds.

CCSD Iteration   0: CCSD correlation = -0.027479342138495   dE =  2.74793E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.033626208260791   dE = -6.14687E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.035330119989960   dE = -1.70391E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.036132439713100   dE = -8.02320E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.036185882519209   dE = -5.34428E-05   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.036186426919642   dE = -5.44400E-07   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.036186082663200   dE =  3.44256E-07   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.036186089231675   dE = -6.56848E-09   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.036186109399133   dE = -2.01675E-08   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.036186107629778   dE =  1.76935E-09   DIIS = 7

CCSD has converged in 0.045 seconds!
converged SCF energy = -1.1287130143406
E(CCSD) = -1.16489910196647  E_corr = -0.0361860876258719
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.033 seconds.

CCSD Iteration   0: CCSD correlation = -0.060639957680846   dE =  6.06400E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.061101382348393   dE = -4.61425E-04   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.070841397768236   dE = -9.74002E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.070408673337085   dE =  4.32724E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.073001090489156   dE = -2.59242E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.073853333453305   dE = -8.52243E-04   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.075989342866709   dE = -2.13601E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.077718336826716   dE = -1.72899E-03   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.077714321222978   dE =  4.01560E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.077739976934772   dE = -2.56557E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.077752057285006   dE = -1.20804E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.077755611536412   dE = -3.55425E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.077757015332208   dE = -1.40380E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.077756828213807   dE =  1.87118E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.077756659684005   dE =  1.68530E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.077756714890682   dE = -5.52067E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.077756690912221   dE =  2.39785E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.077756703269241   dE = -1.23570E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.077756699142095   dE =  4.12715E-09   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.077756689336171   dE =  9.80592E-09   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.077756673229388   dE =  1.61068E-08   DIIS = 7

CCSD has converged in 0.107 seconds!
converged SCF energy = -60.8730319698649
E(CCSD) = -60.94960228996572  E_corr = -0.07657032010081023
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.589 seconds.

CCSD Iteration   0: CCSD correlation = -0.132107694415509   dE =  1.32108E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.146242034671168   dE = -1.41343E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.151911780300137   dE = -5.66975E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.154143942201997   dE = -2.23216E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.156604541367049   dE = -2.46060E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.158089252265299   dE = -1.48471E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.159678959497944   dE = -1.58971E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.161171914674976   dE = -1.49296E-03   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.161383543548282   dE = -2.11629E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.161406698610472   dE = -2.31551E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.161417938117810   dE = -1.12395E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.161412144829577   dE =  5.79329E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.161412224218635   dE = -7.93891E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.161412060584034   dE =  1.63635E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.161412727467636   dE = -6.66884E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.161412842181271   dE = -1.14714E-07   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.161412568569402   dE =  2.73612E-07   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.161412120068369   dE =  4.48501E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.161411486248691   dE =  6.33820E-07   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.161410882829324   dE =  6.03419E-07   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.161410727021171   dE =  1.55808E-07   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.161410684295399   dE =  4.27258E-08   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.161410670726618   dE =  1.35688E-08   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.161410660658434   dE =  1.00682E-08   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.161410655368334   dE =  5.29010E-09   DIIS = 7

CCSD has converged in 1.112 seconds!
converged SCF energy = -61.7050309368926
E(CCSD) = -61.85929465059041  E_corr = -0.1542637136977843
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.290 seconds.

CCSD Iteration   0: CCSD correlation = -0.140365654216008   dE =  1.40366E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.156240051054594   dE = -1.58744E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.161546119563007   dE = -5.30607E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.163991774988107   dE = -2.44566E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.165791993691704   dE = -1.80022E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.166954147360648   dE = -1.16215E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.168017098623332   dE = -1.06295E-03   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.168820149709189   dE = -8.03051E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.168977826013486   dE = -1.57676E-04   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.169023368930042   dE = -4.55429E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.169038406237104   dE = -1.50373E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.169036293286153   dE =  2.11295E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.169035235734957   dE =  1.05755E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.169034648419344   dE =  5.87316E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.169036190272450   dE = -1.54185E-06   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.169038473302820   dE = -2.28303E-06   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.169040674651435   dE = -2.20135E-06   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.169040838063919   dE = -1.63412E-07   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.169039213860237   dE =  1.62420E-06   DIIS = 7
CCSD Iteration  19: CCSD correlation = -0.169035643258884   dE =  3.57060E-06   DIIS = 7
CCSD Iteration  20: CCSD correlation = -0.169032284708002   dE =  3.35855E-06   DIIS = 7
CCSD Iteration  21: CCSD correlation = -0.169031008567742   dE =  1.27614E-06   DIIS = 7
CCSD Iteration  22: CCSD correlation = -0.169030743762438   dE =  2.64805E-07   DIIS = 7
CCSD Iteration  23: CCSD correlation = -0.169030630191248   dE =  1.13571E-07   DIIS = 7
CCSD Iteration  24: CCSD correlation = -0.169030614504506   dE =  1.56867E-08   DIIS = 7
CCSD Iteration  25: CCSD correlation = -0.169030587287652   dE =  2.72169E-08   DIIS = 7
CCSD Iteration  26: CCSD correlation = -0.169030537326456   dE =  4.99612E-08   DIIS = 7
CCSD Iteration  27: CCSD correlation = -0.169030459488010   dE =  7.78384E-08   DIIS = 7
CCSD Iteration  28: CCSD correlation = -0.169030393574371   dE =  6.59136E-08   DIIS = 7
CCSD Iteration  29: CCSD correlation = -0.169030365534121   dE =  2.80402E-08   DIIS = 7
CCSD Iteration  30: CCSD correlation = -0.169030378383558   dE = -1.28494E-08   DIIS = 7
CCSD Iteration  31: CCSD correlation = -0.169030413292919   dE = -3.49094E-08   DIIS = 7
CCSD Iteration  32: CCSD correlation = -0.169030455851158   dE = -4.25582E-08   DIIS = 7
CCSD Iteration  33: CCSD correlation = -0.169030473960241   dE = -1.81091E-08   DIIS = 7
CCSD Iteration  34: CCSD correlation = -0.169030479981709   dE = -6.02147E-09   DIIS = 7
CCSD Iteration  35: CCSD correlation = -0.169030481137716   dE = -1.15601E-09   DIIS = 7

CCSD has converged in 2.740 seconds!
converged SCF energy = -61.7177088065282
E(CCSD) = -61.88686362577447  E_corr = -0.1691548192463257
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.030 seconds.

CCSD Iteration   0: CCSD correlation = -0.050240800307265   dE =  5.02408E-02   MP2
CCSD Iteration   1: CCSD correlation = -0.067399211987220   dE = -1.71584E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.073924796621329   dE = -6.52558E-03   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.078294238721917   dE = -4.36944E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.078382108539325   dE = -8.78698E-05   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.078453342543571   dE = -7.12340E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.078419614953629   dE =  3.37276E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.078448148959091   dE = -2.85340E-05   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.078439611620595   dE =  8.53734E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.078443030318467   dE = -3.41870E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.078443000908710   dE =  2.94098E-08   DIIS = 7

CCSD has converged in 0.039 seconds!
converged SCF energy = -195.971669612661
E(CCSD) = -196.0501126103158  E_corr = -0.07844299765451741
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 1.431 seconds.

CCSD Iteration   0: CCSD correlation = -0.396131541701583   dE =  3.96132E-01   MP2

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:595: RuntimeWarning: divide by zero encountered in log10
  self.Kia1mag=np.log10(np.absolute(self.Kia1))
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:596: RuntimeWarning: divide by zero encountered in log10
  self.Kia2mag=np.log10(np.absolute(self.Kia2))

CCSD Iteration   1: CCSD correlation = -0.391439126001352   dE =  4.69242E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.402082684622406   dE = -1.06436E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.402732916277307   dE = -6.50232E-04   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.404328124523488   dE = -1.59521E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.404386948850892   dE = -5.88243E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.404401976529534   dE = -1.50277E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.404401289749946   dE =  6.86780E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.404402815521766   dE = -1.52577E-06   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.404403007565545   dE = -1.92044E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.404402981756854   dE =  2.58087E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.404402960321868   dE =  2.14350E-08   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.404402964321564   dE = -3.99970E-09   DIIS = 7

CCSD has converged in 0.927 seconds!
converged SCF energy = -198.687118223689
E(CCSD) = -199.091521274996  E_corr = -0.4044030513070224
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.128 seconds.

CCSD Iteration   0: CCSD correlation = -0.430265158664105   dE =  4.30265E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.421858175497171   dE =  8.40698E-03   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.435211427916024   dE = -1.33533E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.435244813112443   dE = -3.33852E-05   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.437101022456375   dE = -1.85621E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.437173716195835   dE = -7.26937E-05   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.437190938158418   dE = -1.72220E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.437191591301705   dE = -6.53143E-07   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.437192228177196   dE = -6.36875E-07   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.437192957170198   dE = -7.28993E-07   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.437193042789065   dE = -8.56189E-08   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.437192866307977   dE =  1.76481E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.437192823977923   dE =  4.23301E-08   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.437192804888600   dE =  1.90893E-08   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.437192803662406   dE =  1.22619E-09   DIIS = 7

CCSD has converged in 2.530 seconds!
converged SCF energy = -198.700530356783
E(CCSD) = -199.1377231620355  E_corr = -0.4371928052529975
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 10 basis functions.
(10, 10)
(10, 10)
Building initial guess...

..initialized CCSD in 0.030 seconds.

CCSD Iteration   0: CCSD correlation = -0.213294471719363   dE =  2.13294E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.163296898936199   dE =  4.99976E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.206869295067322   dE = -4.35724E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.196401421636421   dE =  1.04679E-02   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.207106089866467   dE = -1.07047E-02   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.211409691153762   dE = -4.30360E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.211309901307862   dE =  9.97898E-05   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.211812201477656   dE = -5.02300E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.211890004153050   dE = -7.78027E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.211883030123910   dE =  6.97403E-06   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.211872055767559   dE =  1.09744E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.211869678652109   dE =  2.37712E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.211871338059481   dE = -1.65941E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.211871333843258   dE =  4.21622E-09   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.211871395324609   dE = -6.14814E-08   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.211871398790922   dE = -3.46631E-09   DIIS = 7

CCSD has converged in 0.068 seconds!
converged SCF energy = -77.844534496196
E(CCSD) = -78.05640605320772  E_corr = -0.2118715570117604
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 28 basis functions.
(28, 28)
(28, 28)
Building initial guess...

..initialized CCSD in 0.488 seconds.

CCSD Iteration   0: CCSD correlation = -0.294619018151936   dE =  2.94619E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.250382839574891   dE =  4.42362E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.290160710381002   dE = -3.97779E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.280061011382206   dE =  1.00997E-02   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.284768190988494   dE = -4.70718E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.289699576317932   dE = -4.93139E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.290283973348879   dE = -5.84397E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.290486431086653   dE = -2.02458E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.290564652109172   dE = -7.82210E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.290574981413222   dE = -1.03293E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.290561855542344   dE =  1.31259E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.290560801883679   dE =  1.05366E-06   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.290561819194027   dE = -1.01731E-06   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.290562016345041   dE = -1.97151E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.290562014015707   dE =  2.32933E-09   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.290562011079680   dE =  2.93603E-09   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.290561981598206   dE =  2.94815E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.290562003683250   dE = -2.20850E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.290562006254923   dE = -2.57167E-09   DIIS = 7

CCSD has converged in 0.890 seconds!
converged SCF energy = -78.8892561240802
E(CCSD) = -79.17981786148752  E_corr = -0.290561737407306
Computing RHF reference.

/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:293: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'SCF_TYPE': 'PK'})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:294: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'E_CONVERGENCE': 10e-10})
/home/amousso3/DDLUCJ/check_amplitudes/helper_CC_ML_spacial.py:295: FutureWarning: Using `psi4.set_module_options(<module>, {<key>: <val>})` instead of `psi4.set_options({<module>__<key>: <val>})` is deprecated, and as soon as 1.5 it will stop working

  psi4.set_module_options('SCF', {'D_CONVERGENCE': 10e-10})

Initalizing CCSD object...

Starting AO ->  MO transformation...
Size of the ERI tensor is 0.00 GB, 46 basis functions.
(46, 46)
(46, 46)
Building initial guess...

..initialized CCSD in 1.143 seconds.

CCSD Iteration   0: CCSD correlation = -0.301731793457221   dE =  3.01732E-01   MP2
CCSD Iteration   1: CCSD correlation = -0.257685818595398   dE =  4.40460E-02   DIIS = 0
CCSD Iteration   2: CCSD correlation = -0.296578253009507   dE = -3.88924E-02   DIIS = 1
CCSD Iteration   3: CCSD correlation = -0.286631626820871   dE =  9.94663E-03   DIIS = 2
CCSD Iteration   4: CCSD correlation = -0.291046067513962   dE = -4.41444E-03   DIIS = 3
CCSD Iteration   5: CCSD correlation = -0.296004834244568   dE = -4.95877E-03   DIIS = 4
CCSD Iteration   6: CCSD correlation = -0.296572549777457   dE = -5.67716E-04   DIIS = 5
CCSD Iteration   7: CCSD correlation = -0.296825803820292   dE = -2.53254E-04   DIIS = 6
CCSD Iteration   8: CCSD correlation = -0.296897183486463   dE = -7.13797E-05   DIIS = 7
CCSD Iteration   9: CCSD correlation = -0.296930593493525   dE = -3.34100E-05   DIIS = 7
CCSD Iteration  10: CCSD correlation = -0.296916605675156   dE =  1.39878E-05   DIIS = 7
CCSD Iteration  11: CCSD correlation = -0.296915672838454   dE =  9.32837E-07   DIIS = 7
CCSD Iteration  12: CCSD correlation = -0.296915219377137   dE =  4.53461E-07   DIIS = 7
CCSD Iteration  13: CCSD correlation = -0.296915696001136   dE = -4.76624E-07   DIIS = 7
CCSD Iteration  14: CCSD correlation = -0.296915896100844   dE = -2.00100E-07   DIIS = 7
CCSD Iteration  15: CCSD correlation = -0.296915820701249   dE =  7.53996E-08   DIIS = 7
CCSD Iteration  16: CCSD correlation = -0.296915856050619   dE = -3.53494E-08   DIIS = 7
CCSD Iteration  17: CCSD correlation = -0.296915826091121   dE =  2.99595E-08   DIIS = 7
CCSD Iteration  18: CCSD correlation = -0.296915826387833   dE = -2.96712E-10   DIIS = 7

CCSD has converged in 1.902 seconds!
converged SCF energy = -78.8933300601035
E(CCSD) = -79.19024595047883  E_corr = -0.2969158903752994

Final DataFrame:
    structure    basis set  PySCF_Corr  Psi4_Corr  PySCF_norm_t1  \
0          CN       STO-3G         NaN        NaN            NaN
1          CN      cc-pVDZ         NaN        NaN            NaN
2          CN  aug-cc-pVDZ         NaN        NaN            NaN
3          HN       STO-3G   -0.061979  -0.061979       0.008507
4          HN      cc-pVDZ   -0.153711  -0.153711       0.015478
..        ...          ...         ...        ...            ...
103        HO      cc-pVDZ         NaN        NaN            NaN
104        HO  aug-cc-pVDZ         NaN        NaN            NaN
105       BeH       STO-3G         NaN        NaN            NaN
106       BeH      cc-pVDZ         NaN        NaN            NaN
107       BeH  aug-cc-pVDZ         NaN        NaN            NaN

     Psi4_norm_t1  PySCF_norm_t2  Psi4_norm_t2
0             NaN            NaN           NaN
1             NaN            NaN           NaN
2             NaN            NaN           NaN
3        0.008507       1.006604      0.008507
4        0.015479       0.426481      0.015479
..            ...            ...           ...
103           NaN            NaN           NaN
104           NaN            NaN           NaN
105           NaN            NaN           NaN
106           NaN            NaN           NaN
107           NaN            NaN           NaN

[108 rows x 8 columns]

Failures Encountered:
Structure: CN, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CN, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CN, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CN, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CN, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CN, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BO, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BO, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BO, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BO, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BO, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BO, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CLi, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CLi, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 9 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CLi, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CLi, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 9 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CLi, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CLi, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 9 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeN, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeN, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 11 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeN, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeN, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 11 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeN, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeN, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 11 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BBe, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BBe, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 9 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BBe, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BBe, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 9 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BBe, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BBe, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 9 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: LiO, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: LiO, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 11 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: LiO, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: LiO, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 11 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: LiO, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: LiO, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 11 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CF, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CF, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 15 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CF, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CF, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 15 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CF, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CF, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 15 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CH, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CH, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 7 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CH, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CH, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 7 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: CH, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: CH, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 7 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeF, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeF, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeF, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeF, Basis Set: cc-pVDZ, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeF, Basis Set: aug-cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeF, Basis Set: aug-cc-pVDZ, Method: PySCF_Setup, Error: Electron number 13 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeLi, Basis Set: STO-3G, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.
Error occurred in file: /home/conda/feedstock_root/build_artifacts/psi4_1746393050636/work/psi4/src/psi4/libscf_solver/rhf.cc on line: 92
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)

Structure: BeLi, Basis Set: STO-3G, Method: PySCF_Setup, Error: Electron number 7 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
Structure: BeLi, Basis Set: cc-pVDZ, Method: Psi4_Setup, Error:
Fatal Error: RHF: RHF reference is only for singlets.

In [47]:
failures_df =pd.DataFrame(failures)

In [48]:
df

,structure,basis set,PySCF_Corr,Psi4_Corr,PySCF_norm_t1,Psi4_norm_t1,PySCF_norm_t2,Psi4_norm_t2
0,CN,STO-3G,NaN,NaN,NaN,NaN,NaN,NaN
1,CN,cc-pVDZ,NaN,NaN,NaN,NaN,NaN,NaN
2,CN,aug-cc-pVDZ,NaN,NaN,NaN,NaN,NaN,NaN
3,HN,STO-3G,-0.061979,-0.061979,0.008507,0.008507,1.006604,0.008507
4,HN,cc-pVDZ,-0.153711,-0.153711,0.015478,0.015479,0.426481,0.015479
...,...,...,...,...,...,...,...,...
103,HO,cc-pVDZ,NaN,NaN,NaN,NaN,NaN,NaN
104,HO,aug-cc-pVDZ,NaN,NaN,NaN,NaN,NaN,NaN
105,BeH,STO-3G,NaN,NaN,NaN,NaN,NaN,NaN
106,BeH,cc-pVDZ,NaN,NaN,NaN,NaN,NaN,NaN
107,BeH,aug-cc-pVDZ,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df.to_csv('results.csv')

In [50]:
df.loc[df['structure'] == 'BB']

,structure,basis set,PySCF_Corr,Psi4_Corr,PySCF_norm_t1,Psi4_norm_t1,PySCF_norm_t2,Psi4_norm_t2
66,BB,STO-3G,-0.183195,-0.183195,0.124924,0.124924,0.582370,0.124924
67,BB,cc-pVDZ,-0.193752,-0.193752,0.096490,0.096490,0.516084,0.096490
68,BB,aug-cc-pVDZ,-0.195948,-0.195948,0.098257,0.098256,0.517198,0.098256